### ISSUE TITLE
"posixAccount_primaryGroupAsSecondary" in combination with "posixGroup_autoSyncGon" does not propagate primary group to "member" record

### ISSUE THREAD

**Issue by steffen-moser** [LDAPAccountManager/lam#100]
We run LAM Pro 7.2 (on Solaris 11.4 SRU 21, PHP 7.3.15, and OpenLDAP 2.4.48) and are currently in the process of migrating from pure posixGroups to RFC2307bis-02 groups. Our users have accounts of the type _posixAccount_. We have had a setup where a user's primary group record _(gidNumber)_ automatically leads to a _memberUid_ entry in the related group object for many years and we plan to continue with this setting. To achieve this, we have been using the option _posixAccount_primaryGroupAsSecondary_ in LAM.

Now when migrating from posixGroups to groupOfMembers (the same goes for groupOfNames, so I don't see a relation to issue #98), we found that _posixAccount_primaryGroupAsSecondary_ in combination with _posixGroup_autoSyncGon_ will lead to inconsistencies. While it still synchronizes successfully from the user's primaryGroup property to the _memberUid_ in the (secondary) group, LAM does not seem to touch the "member" attribute of the group, neither when using _groupOfNames_ nor _groupOfMembers_. 

For this reason, the groups are getting into an unsynchronized state which we would like to avoid. 

Expected behavior: I'd suggest that when propagating the primaryGroup setting from the user's _posixAccount_ record to the group, something like the _posixGroup_autoSyncGon_ feature should be called to ensure a fully synchronized directory. 

Maybe it can make sense to activate/deactivate this behavior in the configuration settings of the posixAccount, because maybe not everybody wants to have this behavior.

**Comment by steffen-moser** [comment]
One possibility to solve this issue could be to call a (slightly modified) version of 

`$typeId = $this->getAccountContainer()->get_type()->getId(); 
 $this->manualSyncUnixToGon($typeId);
`

at the end of _function save_attributes()_. This would lead to a transfer of the carried out _memberUid_ settings into the according _member_ attributes. But I still have to test whether it is robust. With "slightly modified", I mean that I don't need this condition:

`(isset($_POST['syncDeleteGroups']) && ($_POST['syncDeleteGroups'] == 'on'))
`

in this case. I would like to delete _member_ attributes in any case if the according _memberUid_ attributes have been deleted. 

Are there any better ideas to fix this or do I maybe observe the issue only due to a configuration misunderstanding or error?

**Comment by gruberroland** [comment]
This is a bit more complicated. I think syncGonToGroups() should be called in save_attributes(). Afterwards, the groupOfMembers that matches the primary group can be added. I will have a closer look after my vacation.

**Comment by gruberroland** [comment]
Hi Steffen,

can you try the following file?

https://raw.githubusercontent.com/LDAPAccountManager/lam/develop/lam/lib/modules/posixAccount.inc

You need to install it in /usr/share/ldap-account-manager/lib/modules/posixAccount.inc.

Best regards
Roland

**Comment by gruberroland** [comment]
Seems to be fixed
