### ISSUE TITLE
docker-compose.yml issue

### ISSUE THREAD

**Issue by peyoot** [LDAPAccountManager/lam#109]
I copied docker-compose.yml and .env from lam-packing/docker and change volumns to use local mapping one, so that I can store data inside the folder where docker-compose.yml located.  It just couldn't work.

here's the major error : " sed: can't read /etc/ldap-account-manager/config.cfg: No such file or directory "

I would like a demo that can be up with docker-compose itself, without the need to change folder privileges or group, etc.

here's the docker-compose.yml. Can you guys share a docker-compose.yml file that can work?

```

version: '3.5'
services:
  ldap-account-manager:
#    build:
#      context: .
    image: ldapaccountmanager/lam:7.3
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./lametc/:/etc/ldap-account-manager
      - ./lamconfig/:/var/lib/ldap-account-manager/config
      - ./lamsession/:/var/lib/ldap-account-manager/sess
    environment:
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LAM_LANG=en_US
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - ADMIN_USER=cn=admin,${LDAP_BASE_DN}
      - DEBUG=true
  ldap:
    image: osixia/openldap:latest
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
    command: "--loglevel info --copy-service"
    volumes:
      - ./ldap:/var/lib/ldap
      - ./slapd:/etc/ldap/slapd.d

```

**Comment by gruberroland** [comment]
Please skip the lametc volume.
For lamconfig please prefill this directory with the config directory content of the tar.bz2 download: https://www.ldap-account-manager.org/lamcms/releases
LAM will not work with an empty config directory.

If you have any more issues please provide more details what is not working.
