### ISSUE TITLE
unable to use(shows some php error)

### ISSUE THREAD

**Issue by vadirajks** [LDAPAccountManager/lam#115]
tired installing diff vers through rpm in centos and not sure if any dependence i need to install further
getting this below error and site shows bank:
[Mon Nov 30 08:27:31.467765 2020] [:error] [pid 22886] [client 10.250.1.241:35004] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /usr/share/ldap-account-manager/lib/selfService.inc on line 538
any help will be grateful.. Thanks all!!

**Comment by gruberroland** [comment]
Please provide more details:
* on what page do you get the error?
* what is your PHP version?
* what is your LAM Pro version?
