### ISSUE TITLE
lamdaemonTest.php fails SSH connect?

### ISSUE THREAD

**Issue by aboschke** [LDAPAccountManager/lam#120]
Trying to configure lamdaemon.pl and it fails to properly connect over SSH. 
It seems lib/remote.inc might not be getting setup properly. 

Our environment:  LAM is running on an Ubuntu 18.04 server, 'webfrontend.local', and NFS is running on a CentOS7 (SELinux permissive) server, 'nfs.local'

Followed instructions to setup lamdaemon.pl:
[ https://www.ldap-account-manager.org/static/doc/manual/apds02.html ]

But while verifying setup with Tools>Tests>lamdaemon test, it seems not to connect properly over SSH:
[ https://webfrontend.local/lam/templates/tests/lamdaemonTest.php  ] 

Confirmed components work properly:
SSH:  from shell    webfrontend.local >> user@nfs.local with using both password and publickey
SUDO: user@nfs.local  is set to NOT require_tty and NOT reset_env , also NOPASSWORD
LAM:  from shell   lamdaemon.pl works when used directly 
   -locally on user@nfs.local:   % sudo /usr/share/ldap-account-manager/lib/lamdaemon.pl +###x##y##x###test###x##y##x###quota  
   -remotely over SSH from webfrontend.local:   % ssh  user@nfs.local  "sudo /usr/share/ldap-account-manager/lib/lamdaemon.pl +###x##y##x###test###x##y##x###quota" 

Problem:
   LAM allows one to either connect with using password or publickey. however both fail with different errors from webfrontend.local:
      password:   error >> "sudo: no tty present and no askpass program specified" 
      (I did manage to dig into lib/remote.inc and this will execute properly, if 'exec' does NOT use sudo)
      publickey:   fails to connect at all; 
       (Documentation is NOT clear on even where to put the SSH private key so that webserver can even reach it)
       
       I can't seem to tickle out any logging what is  incorrectly configured. 
       Please let me know if I can provide any further details.
       
       Appreciate you looking into this issue.

**Comment by gruberroland** [comment]
Please check that in your LAM server profile the path to lamdaemon.pl is correct ( /usr/share/ldap-account-manager/lib/lamdaemon.pl). This is on first tab.
Here you can also set the path and password for the SSH private key. There is no restriction on where this file is located. But it must be readable by the webserver.
Please also check if you have SELinux/AppArmor activated. This might block the webserver to execute the script.

From the error message I guess it is either wrong path to lamdaemon.pl configured or SELinux/AppArmor.

**Comment by aboschke** [comment]
Thanks for quick reply. 

LAM frontend:  Does have AppArmor enabled.  
It makes sense that running the "lamdaemon test” script would require an additional AppArmor profile.
An example doesn’t seem to be provided in the DEB package. Do you have an example (for Ubuntu 20.04)?

 In the LAM server profile, options as follows:
 'Path to external script’ matches the path  from RPM installation correctly — /usr/share/ldap-account-manager/lib/lamdaemon.pl
 'SSH key file’ lists a path accessible by the web server and file is owned by process running web server — /usr/share/ldap-account-manager/lam.pem
( I recall otherwise the test script would not upload it) 

NFS server: SELinux is in PERMISSIVE-mode. 
lamdaemon.pl is installed using the RPM package — /usr/share/ldap-account-manager/lib/lamdaemon.pl

I appreciate your help.

**Comment by gruberroland** [comment]
Unfortunately, we do not provide any AppArmor examples yet.
As you get the sudo error the SSH connection is fine.

Please also take a look at /var/log/sudo.log on the target server. Maybe the command is called with wrong user or you see some other error there.
