### ISSUE TITLE
Docker install failed: The main config file (config.cfg) does not exist

### ISSUE THREAD

**Issue by nicolasgoudard** [LDAPAccountManager/lam#124]
Hello.
On Debian 10 the installation with Docker does not work

"The main config file (config.cfg) does not exist"

I extract the tarball as specified in the documentation (https://hub.docker.com/r/ldapaccountmanager/lam)  but it does not work.

`docker run -p 8080:80 -it -d  --volume /export/docker/lam/data/config:/var/lib/ldap-account-manager/config  --env LAM_SKIP_PRECONFIGURE=true ldapaccountmanager/lam:stable`

If I run like that it works : 
`docker run -p 8080:80 -it -d  ldapaccountmanager/lam:stable`

Then If I copy from docker to outside the container  then, I restart with mounting  the volume it does not work . 
If I mount /etc/ldap-account-manager and /var/lib/ldap-account-manager it does not work
If I replace the config.php symlink by the real file it does not work too...

So what I can do ??
Have you tested the image ? 

Best regards

**Comment by gruberroland** [comment]
Hi Nicolas,

I guess the mounted volume is an empty directory? Then you need to provision the config files first:

> In case you need to provision from scratch please download the tar.bz2 file first. Then use the content of its config folder for the config volume.

**Comment by nicolasgoudard** [comment]
Hi, thanks for your answer. I have made it  already. But it does not work. 
Have you got a tutorial step by step ?

**Comment by gruberroland** [comment]
This is pretty straight forward:
* extract the tar.bz2 archive
* copy all files and folders from the archive's config folder to /export/docker/lam/data/config/

You should have e.g. a  /export/docker/lam/data/config/config.cfg file then (regular file, no link).
No need to mount  /etc/ldap-account-manager in this case.
