### ISSUE TITLE
docker service failed  with http://localhost/lam : apache error 404

### ISSUE THREAD

**Issue by niko2** [LDAPAccountManager/lam#125]
Hi,

I have justed started lam using docker, and I get an error 404 after URL rewrited to /lam

I jumped into the container and noticed /etc/ldap-acount-mamager/apache.conf is missing

I cannot find this configuration file in the tar.bz2 archive...

**Comment by gruberroland** [comment]
Can you provide the full docker command and any environment variables you used?

**Comment by niko2** [comment]
I am mounting external volume on /etc/ldap-account-manager, as in your docker-compose.yml file, but it is not necessary and even wrong. I removed this bind and it works like a charm !

**Comment by gruberroland** [comment]
Thanks for the feedback. I will remove etc+sess volumes in next release.
