### ISSUE TITLE
docker mount volume ，php init error。

### ISSUE THREAD

**Issue by jeffaryhe** [LDAPAccountManager/lam#128]
![image](https://user-images.githubusercontent.com/26104831/112925702-d7d81b80-9144-11eb-99e1-1a8ea3e249ac.png)

I execute the configuration directory of docker mount Lam, unable to mount.

command：
docker run -it  --name ldapweb --rm -p 8080:80 --volume /data/lam/config:/var/lib/ldap-account-manager/config  ldapaccountmanager/lam:7.4

**Comment by jeffaryhe** [comment]
I think your configuration template is put together with the generated configuration file and needs to be changed

**Comment by gruberroland** [comment]
What is the output of "ls -l /data/lam/config"?

**Comment by jeffaryhe** [comment]
You can test the startup, and the output is empty, mainly because your template and the output are correctly configured in the same path.

**Comment by gruberroland** [comment]
What files are in /data/lam/config? You need to copy there everything from config directory of LAM's tar.bz2 download.
