### ISSUE TITLE
set default list options

### ISSUE THREAD

**Issue by drlight17** [LDAPAccountManager/lam#130]
Hello.
Is there any way to set default list options (show account status, max list rows and GID to group name)?

**Comment by gruberroland** [comment]
There is no config setting for this. But the setting is stored in a cookie for one year when you change it.

**Comment by drlight17** [comment]
> There is no config setting for this. But the setting is stored in a cookie for one year when you change it.

Yes, I've already figured this out. So I implemented a small jquery script to edit cookies for every new log into LAM.
Anyway, thanks for the reply.
