### ISSUE TITLE
[Feature Request] Docker images for arm cpus

### ISSUE THREAD

**Issue by kaysond** [LDAPAccountManager/lam#142]
This could potentially be done via multi-arch images:
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
https://www.docker.com/blog/multi-arch-build-what-about-circleci/

**Comment by gruberroland** [comment]
Sorry, we do not plan to support ARM for the moment. :(
You can find our Docker files here: https://github.com/LDAPAccountManager/lam/tree/develop/lam-packaging/docker
If you can update the files yourself we are happy to receive a pull request.
