### ISSUE TITLE
LAM admin login "Wrong password/user name combination. Please try again."

### ISSUE THREAD

**Issue by matthewmkim** [LDAPAccountManager/lam#146]
I have tried many times and all the possible ways that I found on Google but still, the login is not successful.
I can log in using another company tool (phpLDAP admin) and also ldapwhoami command is working with the same password that I tested.
Can you please let me know, how I can check the password setup for the LAM (such as which file) and how I can reset the password if that is possible?

![Screen Shot 2021-08-20 at 2 38 45 am](https://user-images.githubusercontent.com/78717320/130112587-6aefa368-6936-4f6e-ba76-1139b4441f36.png)
![Screen Shot 2021-08-20 at 2 40 10 am](https://user-images.githubusercontent.com/78717320/130112598-4a260e9b-5a41-49a2-8786-8975f0d23f88.png)

**Comment by gruberroland** [comment]
Can you post a screenshot from your server profile, first tab, "Security settings"? Maybe there is some other DN configured that also starts with LAM.

**Comment by matthewmkim** [comment]
Thanks for your response,

I added the screenshot of the Security settings.
Please let me know if you need any other information.

[image: Screen Shot 2021-08-20 at 11.04.37 am.png]
![Screen Shot 2021-08-20 at 11 04 37 am](https://user-images.githubusercontent.com/78717320/130163109-0b3e4e97-3242-4c62-bae7-ccad2077ef49.png)


Regards,
Matthew

**Comment by gruberroland** [comment]
The admin DN in server profile is different ("dc=company" vs "dc=example"). Please adjust server profile to match your LDAP suffix.

**Comment by matthewmkim** [comment]
Thank you for your response, with your suggestion the PW problem is now
solved.
Thanks again.

Regards,
Matthew
