### ISSUE TITLE
[Feature] Bypass login page for use with external authentication

### ISSUE THREAD

**Issue by loelkes** [LDAPAccountManager/lam#147]
I would like to use OpenID Connect to login. LAM would then talk with a fixed user to the LDAP server. In the current setup I use Oauth2-Proxy with access limited to a specific group and inject the fixed user and password in the header but users still need to click "Login".

How about skipping the "Login" if the credentials are set in the headers? Why the extra Login-Button click?

**Comment by gruberroland** [comment]
Hi,

we plan integration of OpenID for next release.

To use LAM with basic authentication you need to activate it in your server profile:

https://www.ldap-account-manager.org/static/doc/manual/ch03s02.html#idm857

Choose login method "LDAP search" in security settings. Then activate HTTP authentication. This will take the credentials from Apache.

Example Apache config:
https://www.ldap-account-manager.org/static/doc/manual/apbs07.html#apache_http_auth

Best regards

Roland

**Comment by loelkes** [comment]
Hi Roland,

> To use LAM with basic authentication you need to activate it in your server profile:
> 
> https://www.ldap-account-manager.org/static/doc/manual/ch03s02.html#idm857
> 
> Choose login method "LDAP search" in security settings. Then activate HTTP authentication. This will take the credentials from Apache.

Thanks, I know. But I don't want BasicAuth nor do I want use Apache, I would like the possibility to use a full external authentication/authorisation method. Right now I have a fixed account that I manually inject after successful OAuth2 authentication so that LAM thinks there was a basic auth with (nginx)

```
fastcgi_param PHP_AUTH_USER 'admin';
fastcgi_param PHP_AUTH_PW 'password';
```

My wish: a feature to fully disable any login method and customise the logout button. As of now, I've manually patched the template with a custom link.

**Comment by gruberroland** [comment]
But if there is no login, how should LAM authenticate the user at the LDAP server?

**Comment by loelkes** [comment]
There are two questions here, maybe we need to split them in issues:

1. If LAM receives a user and password through `PHP_AUTH_USER` and `PHP_AUTH_PW` why do I still need to press the login button? I would except to be logged in directly. LAM still receives credentials for bindings trough headers. IMHO LAM should skip the login page if these credentials are provided. 

2. It would be nice to customise the logout button link for the use with external auth. If I can login externally I should also be able to log out externally.

I'm looking forward to the OpenID integration.

**Comment by gruberroland** [comment]
1. If the login is automatically then you cannot access e.g. LAM's configuration or change the server profile.
2. I think this would be very annoying for users when they logout in LAM to update e.g. the server profile. They would end up each time on the external system without a way back. This would be something that can be solved using a custom JavaScript: https://www.ldap-account-manager.org/static/doc/manual/apf.html
