### ISSUE TITLE
Mass upload CSV turns the page blank

### ISSUE THREAD

**Issue by abhisheksahnii** [LDAPAccountManager/lam#153]
LAM 7.7
OS - CentOS release 8
PHP 8.0.13 (cli) (built: Nov 16 2021 18:07:21) ( NTS gcc x86_64 )
SELINUX Disabled
DIR - /var/www/html/lam/

While uploading a CSV file for mass group creation, LAM pages ended up showing nothing.

Increasing debug level showing some errors;

- Webpage,

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /var/www/html/lam/templates/upload/massBuildAccounts.php:139 Stack trace: #0 [internal function]: array_merge() #1 /var/www/html/lam/templates/upload/massBuildAccounts.php(139): call_user_func_array() #2 {main} thrown in /var/www/html/lam/templates/upload/massBuildAccounts.php on line 139

Console.
Stack trace:
#0 [internal function]: array_merge()
#1 /var/www/html/lam/templates/upload/massBuildAccounts.php(139): call_user_func_array()
#2 {main}
  thrown in /var/www/html/lam/templates/upload/massBuildAccounts.php on line 139

**Comment by gruberroland** [comment]
Looks like PHP 8 is more strict here. This will be fixed in next release this month.

**Comment by abhisheksahnii** [comment]
Thanks a lot, it is working fine after applying the patch.
