### ISSUE TITLE
Sed command contains wrong file reference

### ISSUE THREAD

**Issue by Seennt** [LDAPAccountManager/lam#157]
LS,
Regarding the next line of code:
https://github.com/LDAPAccountManager/lam/blob/0080e4ad80a21fc53cd95b1ea82387fe7de8f13e/lam-packaging/docker/start.sh#L60

I assume the correct file reference should be:
> /var/lib/ldap-account-manager/config/config.cfg

The reason I assume this is when I manually update the /var/lib/ldap-account-manager/config/config.cfg the login for: "Edit general settings" works as it suppose.

As a side note, the log mentioned the following:
> PHP Notice:  A non well formed numeric value encountered in Command line code on line 1

Generated by:
https://github.com/LDAPAccountManager/lam/blob/0080e4ad80a21fc53cd95b1ea82387fe7de8f13e/lam-packaging/docker/start.sh#L45

[SOLVED: See answer premissions] As the default password (Set via LAM_PASSWORD) is now updated and I login to "Edit general settings" I receive a blank page... Any suggestion?

Thanks in advance,
Siggy

**Comment by Seennt** [comment]
LS,

In addition to my own issue, the following errors solved a part of the above mentioned issue (blank page)

> [client 10.##.#.11:51##f6] PHP Warning:  fopen(/usr/share/ldap-account-manager/lib/../config/__lam.webauthn.sqlite): failed to open stream: Permission denied

> [Thu Dec 23 21:30:35.748834 2021] Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /usr/share/ldap-account-manager/lib/webauthn.inc:761

Based on these errors a permission issue on the volume-bind was the problem.

> The /config directory (host) needs to have correct ownership.

Kind regards,
Siggy

**Comment by gruberroland** [comment]
Thanks a lot for the feedback. We will improve the error handling at this location to avoid the blank page issues.
