### ISSUE TITLE
config.cfg not found if used with docker-compose

### ISSUE THREAD

**Issue by Kusig** [LDAPAccountManager/lam#158]
I tried to use LAM with docker-compose example.  Copied the stuff from config folder inside as adviced.

However, when pointing the browser to LAM there comes the message that the config.cfg is missing.  In the logs given, there is no error message visible.

In fact, there is no such file config.cfg available in this default content. So where should this file come from?

Any idea or advice about that problem. Or is the installation instruction incomplete for this?

**Comment by gruberroland** [comment]
Did you copy the file config.cfg.sample to config.cfg? Then it should work.

**Comment by Kusig** [comment]
Yes, tried this as well but no chance. It starts up nicely, at least there are no error messages in the logs. But pointing the browser to it just returns: The main config file (config.cfg) does not exist.

**Comment by gruberroland** [comment]
Please run this inside the container to check if there are config files accessible:
ls -l /usr/share/ldap-account-manager/config
Maybe there is an issue with the volume.

**Comment by Kusig** [comment]
Seems to be empty. But it is mapped.
# ls -al /usr/share/ldap-account-manager/config
lrwxrwxrwx 1 root root 36 Dec 28 10:33 /usr/share/ldap-account-manager/config -> /var/lib/ldap-account-manager/config
# ls -al /var/lib/ldap-account-manager/config
total 4
drwxr-xr-x 2 root root   40 Jan  2 17:14 .
drwxr-xr-x 5 root root 4096 Dec 28 10:33 ..
# 

Probably related to the fact that this is symlink in the image itself?

**Comment by gruberroland** [comment]
How did you mount the folder from outside? Looks like the files are not visible inside the container.

**Comment by Kusig** [comment]
With a simple docker compose mount:
    volumes:
      - /etc/lam/lamconfig:/var/lib/ldap-account-manager/config
      - /var/log/lam:/var/log/apache2

For testing, I added now another directory. And this one works as expected. The apache log file is where it is supposed to be on the host destination.  
Therefore I assume that there is a problem related to the fact that the directory is a linked one. There are many problems known  with docker mounts to linked files/directories. 

It would be helpful to be able to mount to the real directory instead of linked ones in order to keep those problems away.

**Comment by gruberroland** [comment]
Maybe there are issues with file permissions or e.g. AppArmor (as you see no files at all inside docker).

You can also try to mount
- /etc/lam/lamconfig:/usr/share/ldap-account-manager/config

This should work, too.

**Comment by Kusig** [comment]
Tried this already earlier but did it now again. This does as well not work as it just points to the linked source directory. The mounted directory isn't outside of the container in either case.  I could write/read from inside the container without problems there but it isn't mounted outside due to the link. 
As mentioned before. Mounting any other directory which isn't a link does work perfectly.

**Comment by Kusig** [comment]
Problem found.  There was installed snap docker on this system instead of a real docker-ce.   This snap-docker does only support files in /home directory and seems to be quite restrictive ....

After uninstalling and using the real docker-ce it works perfectly.
