### ISSUE TITLE
inetOrgPerson Lock password does nothing.

### ISSUE THREAD

**Issue by xpufx** [LDAPAccountManager/lam#159]
Looking at the code it's supposed to be disabling the user password by adding a ! after the {SSHA} label. However when I check the ldap userPassword it remains unchanged and the user's password still works. No errors on the screen or on the ldap backend as far as I can tell.

User can make this change when tested directly on ldap.

EDIT: Likewise with Remove password.

**Comment by gruberroland** [comment]
I was not able to reproduce this. What other user modules do you have enabled in your LAM server profile?
Which version of LAM do you use?

**Comment by xpufx** [comment]
I am on 7.8.   Am I right in thinking there shouldn't be permission issues in ldap if I can log into ldap with an LDAP client and modify the password hash directly?

I don't have any other modules enabled. I will try debugging it and come back with more info (or fix an error on my side).

**Comment by xpufx** [comment]
@gruberroland I wasn't hitting save after flipping the button. Since it was doing a post I thought it was already doing the change. If there is no technical need for the button it might work better as a checkbox to make it clear that it's part of the form submission process.

Cheers.
