### ISSUE TITLE
Tree view doesn't show details about objects (people, groups,...)

### ISSUE THREAD

**Issue by socka25** [LDAPAccountManager/lam#160]
When I click on any object it won't show me details:

![image](https://user-images.githubusercontent.com/77669833/150675411-2e58cbea-e2af-4bfb-8c23-b95913a89bb7.png)

console shows the same error and I don't know why as all my settings in Server profiles seem to be correct:

![image](https://user-images.githubusercontent.com/77669833/150675533-2f1ef0e6-31ac-43e8-8123-ebc32fd11314.png)

I'm using PHP 8.1 and upgraded LAM from version 7.4 following these steps:

![image](https://user-images.githubusercontent.com/77669833/150675649-909d3224-a10d-4bf4-b884-1bafe33099f7.png)

Only thing that works is Search but I can't open the link of search results neither.

**Comment by gruberroland** [comment]
Please try to downgrade PHP to version 8.0 or 7.4. LAM does not yet fully support PHP 8.1.
If this does not help please check your Apache error.log for any messages when you get the error.

**Comment by socka25** [comment]
That worked. Thank you very much :)
