### ISSUE TITLE
sambaNTPassword not updated after changing password in Self Service

### ISSUE THREAD

**Issue by hb0nes** [LDAPAccountManager/lam#165]
We have a bunch of existing users and we want them to be able to use a Synology Samba share together with our OpenLDAP instance.

In order to do this, we would have to manually add the Samba module to a user and reset their password manually.

However, we thought it might have been easier if we could make every user change their password with self service, which would then add sambaNTPassword field. This doesn't happen. If the user already has an existing sambaNTPassword field, self service also does not update this field (but does change the userPassword field).

This makes the Samba integration semi-unusable, because users wouldn't be able to authenticate with Samba shares after changing their password.

**Comment by gruberroland** [comment]
Hi,
on tab "Page Layout" you can add two invisible Samba sync fields:
* Sync Samba LM password with Unix password
* Sync Samba NT password with Unix password

Then the Samba password will be changed whenever the Unix password is updated.

**Comment by hb0nes** [comment]
![image](https://user-images.githubusercontent.com/38855893/155983232-f278e744-ea24-4b80-a4bb-d27c9d553622.png)

After adding
- Sync Samba NT password with Unix password

The above error appears.

I presume self service binds as the user itself when interacting with LDAP,
however I don't know how to give all users write rights for this specific
property (changing passwords worked without sambaNTPassword).


Op do 24 feb. 2022 om 20:23 schreef gruberroland ***@***.***>:

**Comment by hb0nes** [comment]
Never mind, I believe I fixed it. Thanks a lot!
