### ISSUE TITLE
v7.9 release absent from https://www.ldap-account-manager.org/lamcms/releases ?

### ISSUE THREAD

**Issue by nodiscc** [LDAPAccountManager/lam#166]
Hi,

LAM 7.9 was released 16 days ago (https://github.com/LDAPAccountManager/lam/releases, https://www.ldap-account-manager.org/lamcms/node/442) but still does not appear on https://www.ldap-account-manager.org/lamcms/releases.

I successfully installed/quickly tested the 7.9 tarball (using this [ansible role](https://github.com/nodiscc/xsrv/tree/master/roles/openldap)), but wanted to know if there is something preventing an "official" release or if the releases page is just outdated.

Thanks

**Comment by gruberroland** [comment]
Thanks a lot for the hint! Indeed, a small typo prevented it from appearing. Now it is there.
