### ISSUE TITLE
Debian Packages outdated

### ISSUE THREAD

**Issue by DumpName** [LDAPAccountManager/lam#168]
Hi,
I just noticed that the debian Packeges in the [official Debian repository](https://packages.debian.org/search?keywords=ldap-account-manager) are outdated.
As the insatllation in via the debian repository is expicitly mentioned in the doku either a small hint regarding the version or an update of the packages would be nice.

**Comment by gruberroland** [comment]
Each new version is sent to a Debian developer for check and upload. Unfortunately, sometimes uploads are delayed for various reasons. The people managing Debian are working for the project in their free time.
If you require the most recent version then you can simply download it from the website or Github release page.
