### ISSUE TITLE
gecos attribute doesn't get any values 

### ISSUE THREAD

**Issue by resposit** [LDAPAccountManager/lam#171]
Hello,

I enabled the gecos attribute in posixUser module and when I create a new uses I can see the gecos field in the form.
The help says: "User description. If left empty first and last name will be used."
But If leave it blank it does not gets automatically filled with firstname + lastname.

Am I missing something ?

**Comment by gruberroland** [comment]
Sorry, the help text is wrong. The static filling with first+last name was removed.
You can now use the wildcards that are provided by e.g. "Personal" module:

$firstname $lastname

This will fill the data. Next release will also allow to enter the wildcards in profile editor. This way you do not need to enter them manually for new users.

**Comment by resposit** [comment]
Excelent ! Thanks for clarifying that.
