### ISSUE TITLE
Docker default configuration seems not to use Debian ca-certs

### ISSUE THREAD

**Issue by maecki-maecki** [LDAPAccountManager/lam#173]
When I run a vanilla container with

```
podman run --name lam.my.domain -dit --restart unless-stopped -p 8080:80 \
  -e LDAP_SERVER=ldaps://ldap.my.domain:636 \
  -e LDAP_DOMAIN=my.domain \
  -e LDAP_USER=cn=admin,dc=my,dc=domain \
  -e LAM_LICENSE="" \
  -e LAM_CONFIGURATION_DATABASE="files" \
  -e LAM_CONFIGURATION_DATABASE_NAME="" \
  -e LAM_CONFIGURATION_HOST="" \
  -e LAM_CONFIGURATION_PORT="" \
  -e LAM_CONFIGURATION_USER="" \
  -e LAM_CONFIGURATION_PASSWORD="" \
  docker.io/ldapaccountmanager/lam:stable
```

it will refuse to connect to my ldaps-Server when called in browser. The server uses a letsencrypt certificate.

Though lam configuration screen says ```SSL certificates   use system certificates (?)``` it does not seem to use the default certificates of debian (/etc/ssl/certs) which do include letsencrypt.

Only after 'import from server' in lam configuration's ssl dialog I am able to connect.

Regards
Mäcki

**Comment by gruberroland** [comment]
The Docker image is based on Debian Stable (Bullseye). This does not provide the Let's Encrypt CA certificate.
For custom CA certificates like LE please install them in /etc/ssl/certs or use the LAM configuration.

See https://packages.debian.org/bullseye/all/ca-certificates/filelist

**Comment by gruberroland** [comment]
Please also check if your LDAP server serves the intermediate certificate from LE. This might help already.

`openssl s_client -host localhost -port 636
`
