### ISSUE TITLE
Publish GPG Signing keys for RPMs?

### ISSUE THREAD

**Issue by aboschke** [LDAPAccountManager/lam#175]
Would you please also publish the GPG Signing Key '7f3d136b2bcd7990' with the RPMs in sf.net? 
[ https://sourceforge.net/projects/lam/files/LAM/ ] 

```
Name        : ldap-account-manager
Version     : 7.9.1
Release     : 0.fedora.1
Architecture: noarch
Install Date: (not installed)
Group       : Productivity/Networking/Web/Frontends
Size        : 97260145
License     : GPL
Signature   : RSA/SHA512, Thu 14 Apr 2022 11:39:05 AM PDT, Key ID 7f3d136b2bcd7990
```

**Comment by gruberroland** [comment]
Thanks for the hint. You can find the link to the key on top of this page now:
https://www.ldap-account-manager.org/lamcms/releases
