### ISSUE TITLE
Bugs in v. 7.9.1

### ISSUE THREAD

**Issue by vanken18** [LDAPAccountManager/lam#177]
Encountering bugs in the version 7.9.1:

When I set a user to the primary group it does not add/reflect to the selected group. 
But when I edit the members of the selected group it does not display the user. It is only displayed in the other group list. And vice versa, when I set a user to the other group as primary it does not reflect to the selected other group.
Scenario 1:
![image](https://user-images.githubusercontent.com/106047523/169738041-f94af01a-4070-4ad8-bd37-69614313e72e.png)
![image](https://user-images.githubusercontent.com/106047523/169738117-df77cd7c-f37a-4cfa-8d40-76133544435c.png)
![image](https://user-images.githubusercontent.com/106047523/169738243-43fe56de-f653-43e7-baca-037ed46a1ac8.png)

Scenario 2:
![image](https://user-images.githubusercontent.com/106047523/169737558-7fe102ea-757f-409a-bbc7-a83ebfc0c450.png)
![image](https://user-images.githubusercontent.com/106047523/169737671-ae5990ab-b362-4dd2-9e91-014e9f58fc06.png)

**Comment by gruberroland** [comment]
By default, LAM will not add a user to a group if this is already the user's primary group. This is how it works for local users and groups.
But you can change this in your server profile -> Module settings -> Unix.

**Comment by vanken18** [comment]
Thank you.. It is working now as per your instruction.
