### ISSUE TITLE
captcha issue with 8.0.1

### ISSUE THREAD

**Issue by linuxgambler** [LDAPAccountManager/lam#180]
we are facing issue while upgrading from **7.7 to 8.0.1.** with 7.7 it is working fine after upgrade it is failing. 
In nginx we are getting below error:
Stack trace:
#0 {main}
  thrown in nginx/html/templates/selfService/selfServiceLogin.php on line 327" while reading response header from upstream, client: x.x.x.x, server: selfservice.abc.com, request: "GET /lam/templates/selfService/selfServiceLogin.php?name=SimpleAD_SelfService&scope=user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "selfservice.abc.com"
2022/07/08 12:41:23 [error] 1572#0: *3895 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'htmlReCAPTCHA' not found in nginx/html/templates/selfService/selfServiceLogin.php:327

**Comment by gruberroland** [comment]
I was not able to reproduce this with PHP 8.1. Can you try to restart your PHP FPM?
Maybe some old PHP code is still in cache.

**Comment by contentstack-admin** [comment]
I tried restarting & reinstalling php again but didn't work

**Comment by linuxgambler** [comment]
I tried reinstallating php as well but didn't worked

**Comment by gruberroland** [comment]
Please try to restart your server to make sure all caches are flushed.

**Comment by linuxgambler** [comment]
Have done it but didn't resolve the issue just wanted to check here we have directly copied configs from 7.7 to 8.0.1 so those configs are compatible with 8.0.1? Rest all data we have tested like creating new users, updating existing users etc it is working fine only issue with captcha.

**Comment by gruberroland** [comment]
Could it be that you copied the OpenSource version to your Nginx directory? Maybe you have a mixed installation now where the Pro parts are still on 7.7. Please try to install from here again:

https://www.ldap-account-manager.org/lamcms/LAMProReleases

You can validate the installation by running:

md5sum nginx/html/templates/selfService/selfServiceLogin.php

It should print: 721b362a2b445b013716e65b0ee0b3fb

There is no need to update config files.

**Comment by linuxgambler** [comment]
@gruberroland  I am not able to find selfServiceLogin.php:

I have taken the backup of **html** folder in nginx and have executed the below commands:

sudo ./configure --with-httpd-user=nginx --with-httpd-group=nginx --with-web-root=~/nginx/html && make install

Is there anything I am missing here?

**Comment by gruberroland** [comment]
The file should be /root/nginx/html/templates/selfService/selfServiceLogin.php

Please try to redownload LAM Pro from https://www.ldap-account-manager.org/lamcms/LAMProReleases and rerun the commands. This should fix the issue.

**Comment by linuxgambler** [comment]
Working fine now Thanks @gruberroland  for all the support
