### ISSUE TITLE
lampro 8.0.1 issue while adding new sshkeys public keys 

### ISSUE THREAD

**Issue by linuxgambler** [LDAPAccountManager/lam#181]
Hi Team,
While adding new keys in lampro what we are observing that the old keys are getting flushed automatically. 
To reproduce the issue:
Login to lam self service ---> Add keys in SSH Public keys ---> Save & when we try to add new key again then after clicking on **Add** icon old keys get deleted.
<img width="840" alt="Lam-sshkeys-issue-1" src="https://user-images.githubusercontent.com/96431559/178657051-40403197-0bf3-45d3-bef5-7129ee5f87a5.png">

In  the above screenshot while I am trying to add new keys old keys are flushed. 
Also can we add more then 1 key with latest version?

**Comment by gruberroland** [comment]
Thank you very much for your report. It seems that this is related to PHP 8.1. We are working on a solution.
As a workaround you can downgrade PHP to version 7.4.

**Comment by gruberroland** [comment]
The issue was fixed but as the fix required multiple changes there is no easy patch. For PHP 8.1 you will need to wait for the next release.
Therefore, I suggest to use PHP 7.4 for the moment.

**Comment by linuxgambler** [comment]
That worked for us Thanks @gruberroland !!!
