### ISSUE TITLE
Mass uploading of users endup into fatal error: timeout

### ISSUE THREAD

**Issue by abhisheksahnii** [LDAPAccountManager/lam#185]
LAM 8.0.1
OS - CentOS release 8
PHP 8.0.23 (cli) (built: Nov 16 2021 18:07:21) ( NTS gcc x86_64 )
SELINUX Disabled
logLevel: 7

It has been observed that while uploading the users via mass upload feature, LAM is not able to process duplicates "uid" entries which are already there in the existing LDAP database.  Even though there are only 10-50 entries in the bulk_upload CSV file.

To isolate the issue, I manually deleted the entry from the CSV file and VIOLA! I am able to upload users successfully. 

Expected Result: LAM should show the duplicate UIDs in the CSV  after processing the file. instead of showing a fatal error.

**Comment by gruberroland** [comment]
Thanks a lot for your report. This should not be.
Please provide your list of active user account modules (e.g. screenshot of account modules in server profile). Then we can check and fix this.

**Comment by abhisheksahnii** [comment]
This issue still exists on the lam 8.0.1.

**Comment by gruberroland** [comment]
Please upgrade to the latest version (9.6) and retry. If the issue is still existing try to increase "memory_limit" in your php.ini file.
If that does not help please provide a screenshot as requested before and a sample CSV that causes the issue.
