### ISSUE TITLE
Docker Environment variable LAM_DISABLE_TLS_CHECK breaks container start

### ISSUE THREAD

**Issue by DumpName** [LDAPAccountManager/lam#186]
Since I was experiencing issues connecting my docker installation to my samba server, I figured I might try the  `LAM_DISABLE_TLS_CHECK` variable to temporarily disable tls checking.
However the directory `/etc/ldap/` does not exists in a fresh container, neither does the file `/etc/ldap/ldap.conf`

Therefore on the first container startup lin 27 of the `start.sh` breaks with the error: 
`/usr/local/bin/start.sh: line 28: /etc/ldap/ldap.conf: No such file or directory`

After the first startup fails, all following startups will fail with the message:
 `ln: failed to create symbolic link '/etc/ldap.conf': File exists`
 
Testet in: stable(sha256:841dd7d07183f4f94e74cd098a9db34e611ef5441f3b7813e4c87572ad5e3c73) & latest (sha256:fa797b39a1a5286ebc691d1e11341d50bd8caab93e1bcb8bf0cb17d73ae67352)

**Comment by gruberroland** [comment]
Thank you very much for your report. The Dockerfile and start.sh was updated. This will be part of the 8.1 release.

**Comment by henningkessler** [comment]
I have the same problem with the most current version
