### ISSUE TITLE
LAM and ldappasswd

### ISSUE THREAD

**Issue by PFKlloyd** [LDAPAccountManager/lam#187]
I have installed LAM and have managed to get the UI working perfectly however we are having an issue with applications like SVN and Bugzilla with reference to the LAM openLDAP instance. If we run ldappasswd on the CLI the user can use these applications but if we create an account with LAM we are getting a Authentication failure. What do we need to do to allow LAM to update ldap so we only need to create the account in 1 place rather than create the account in LAM and then run ldappasswd on the CLI.

Many Thanks,
Lloyd

**Comment by gruberroland** [comment]
LAM can create users that can directly authenticate via CLI. We need to dig a bit deeper here.

Please do an LDIF export of such a user before and after the ldappasswd (e.g. with LDIF Import/Export in LAM tools menu). Then check what is the difference after ldappasswd.
If we know which attributes differ then we can check why a login is not possible in first place.
