### ISSUE TITLE
Blank Login Page

### ISSUE THREAD

**Issue by bdunn1100** [LDAPAccountManager/lam#189]
Hello.. I'm trying to get LDAP Account Manager running on a test system before we go ahead with a purchase of the pro edition. It seem like I'm having an issue with getting to the login page. When it loads, all I see is a blank page. In the httpd error logs I get this message:

PHP Parse error:  syntax error, unexpected ':', expecting '{' in /usr/share/ldap-account-manager/templates/login.php on line 198

I'm running version 8.1 on CentOS 7. I also tried revering back to an older version, 7.7, but this does not seem like it's working. I'm getting the same error on a different line. Any help would be greatly appreciated. 

----------------
Sorry, I should read instructions better sometimes. I have it working now.

**Comment by gruberroland** [comment]
Which PHP version do you use? LAM requires at least PHP 7.2.
Very old PHP versions could cause such errors.

**Comment by bdunn1100** [comment]
I figured that I was not using the correct PHP version. Once I installed PHP 7.3 everything starting working. Thanks for getting back to me!
I do have another question. How does/or can LDAP Account Manager add the memberOf attribute to a user? I have the overlay configured properly inside of openLDAP but I do not see it getting applied when I add users to groups. Is this a different feature that can be added or is it added in the Pro version? Bottom line, I need the memberOf attribute listed when my system does a query to LDAP. Thanks!

**Comment by gruberroland** [comment]
Looks like the mail answer was not added to this ticket. Here it is again:

Great that it works now. 😄

The memberOf attribute is a virtual one. It is automatically added by the LDAP server using the overlay.

You can see it with LAM's general information module:

https://www.ldap-account-manager.org/static/doc/manual/ch04s32.html

To manage group of names memberships (that are the base for memberOf) you can use:

https://www.ldap-account-manager.org/static/doc/manual/ch04s06.html
https://www.ldap-account-manager.org/static/doc/manual/ch04s02.html#idm2213

**Comment by gruberroland** [comment]
Great that it works now. :)

The memberOf attribute is a virtual one. It is automatically added by 
the LDAP server using the overlay.

You can see it with LAM's general information module:

https://www.ldap-account-manager.org/static/doc/manual/ch04s32.html

To manage group of names memberships (that are the base for memberOf) 
you can use:

https://www.ldap-account-manager.org/static/doc/manual/ch04s06.html
https://www.ldap-account-manager.org/static/doc/manual/ch04s02.html#idm2213
