### ISSUE TITLE
Error in start.sh for docker-compose

### ISSUE THREAD

**Issue by Magisdn** [LDAPAccountManager/lam#193]
Hi!

When starting the start.sh script, an error appears
./start.sh: line 24: DEBUG: unbound variable
How to fix it?
Thanks.

**Comment by gruberroland** [comment]
Please check that "DEBUG" is set in your docker-compose.yml. E.g.

  
 environment:

      - LAM_PASSWORD=${LAM_PASSWORD}

      - LAM_LANG=en_US

      - LDAP_SERVER=${LDAP_SERVER}

      - LDAP_DOMAIN=${LDAP_DOMAIN}

      - LDAP_BASE_DN=${LDAP_BASE_DN}

      - ADMIN_USER=cn=admin,${LDAP_BASE_DN}

      - DEBUG=true

**Comment by Magisdn** [comment]
environment:
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LAM_LANG=ru_RU
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - ADMIN_USER=cn=admin,${LDAP_BASE_DN}
      - DEBUG=true

**Comment by gruberroland** [comment]
Please remove line 24 from start.sh as a workaround. We will fix this for next version.

**Comment by Magisdn** [comment]
I removed line 24 from start.sh but nothing changed. :(

**Comment by gruberroland** [comment]
True, the Docker image needs to be rebuilt first. Please use the non-composer Docker commands for the meantime or package installation.
https://www.ldap-account-manager.org/static/doc/manual/ch02.html#idm363

**Comment by cociweb** [comment]
well, 
@gruberroland the docker image is still broken. Do you have any updates/hints?
with 8.2 (latest/stable) I still get error on line 24: 
/usr/local/bin/start.sh: line 24: false: unbound variable

but there was no issue with 8.0.1 - so I reverted the line to `[ "$DEBUG" ] && set -x` with mount tricks and it's working again...

**Comment by gruberroland** [comment]
You mean this is not working for you?
`[[ -n "$DEBUG" ]] && [[ "$DEBUG" = "true" ]] && set -x`

**Comment by cociweb** [comment]
Exactly. It fails to bootloop and continously restart with the above mentioned unbound error. It is worth to mention that I use `DEBUG=false` environmental variable.

**Comment by gruberroland** [comment]
Does this line work for you?
`[ "${DEBUG:-false}" = "true" ] && set -x`

**Comment by cociweb** [comment]
> Does this line work for you? `[ "${DEBUG:-false}" = "true" ] && set -x`

Yes, it's working for me!

**Comment by gruberroland** [comment]
Perfect, will be changed in next release (March).
