### ISSUE TITLE
Self Service Portal

### ISSUE THREAD

**Issue by bdunn1100** [LDAPAccountManager/lam#194]
Hello Support! This is a quick question, but within the Self Service Portal is there a way that a user can choose what groups they would want to be in? Or even create a new group to be in? I know that this might seem to be a strange request, but with the system that we are using we would like to have the users control that. Let me know if this is possible or not.

**Comment by gruberroland** [comment]
Hi,
indeed, this sounds a bit exotic. I guess you control something like mailinglist memberships or personal interests via these groups? Maybe you can provide some more details about your use-case to understand this better.
