### ISSUE TITLE
LAM Pro not setting attributes correctly on password changes

### ISSUE THREAD

**Issue by raramsbu** [LDAPAccountManager/lam#197]
We have a license and are using LAM Pro. LDAP admins are using the interface to change users' passwords. Users are then forced to change their password immediately, but must wait a day before they are able to do so. 

It should be changing these attributes: 
shadowLastChangeTime to zero
passwordExpirationTime to "19700101000000Z"
passwordAllowChangeTime to the current time.

We recently updated to v8.1 thinking that it would resolve this issue, but it did not.

**Comment by gruberroland** [comment]
Do you really mean "shadowLastChangeTime" or "shadowlastchange"?
Where do passwordExpirationTime and passwordAllowChangeTime come from? It looks like they are specific to your LDAP server software. Which one is it? Then we can check how to support this.

**Comment by raramsbu** [comment]
Sorry for the lag in my reply on this thread, I'm an admin in contact with a developer who built our previous LDAP instance. 
Here is a more complete description of the problem we are trying to solve: 
When LDAP Admins reset a user account's password, we would like two of our "custom" LDAP attributes to be changed. This will allow users to change their passwords immediately after reset. We have two "custom" LDAP attributes that are specific to our LDAP schema, which we would like LAM Pro to change during a password reset: "passwordExpirationTime" and "passwordAllowChangeTime". 
After password reset, we would like LAM Pro to set our custom attribute "passwordExpirationTime" to UNIX epoch; this is because under certain circumstances the directory server derives the shadowLastChange value from the value of passwordExpirationTime. 
Also, to enable users to change their passwords immediately after a password reset, we would like LAM Pro to set our custom attribute "passwordAllowChangeTime" to either the current time or the beginning of UNIX epoch. 
Is this possible?

**Comment by gruberroland** [comment]
There are two possible solutions for such a setup:
* custom scripts module that runs an external script to set the attributes: https://www.ldap-account-manager.org/static/doc/manual/ch04s27.html
* custom module to manage your attributes: https://www.ldap-account-manager.org/lamcms/develdocs
For custom modules we offer fixed price projects. Please contact us via email if you are interested.
