### ISSUE TITLE
hard to read PDF password font

### ISSUE THREAD

**Issue by bleeptrack** [LDAPAccountManager/lam#2]
Hi,
I got some feedback from my users that the password's font in the generated pdf can be hard to read. Especially combinations of i,I,l,o,O,0 can be hard to distinguish because of the sans serif font.

I changed the lamPDF.inc and pdf.inc file to use a second font (I chose InconsolataLGCMarkup, which is open source and optimized for distinguishing different symbols). It would be nice if this could be implemented in the next version. I added my code but I'm not sure if this is the best way to implement it.

[pdf.zip](https://github.com/LDAPAccountManager/lam/files/455005/pdf.zip)

**Comment by gruberroland** [comment]
Thanks a lot for your patch. I plan to change LAM's internal PDF interface to be more object oriented in 5.6/5.7. This will also include the possibility for modules to specify if a serif font should be used.

**Comment by bleeptrack** [comment]
Thank you very much :)
