### ISSUE TITLE
Error when using volumes for saving config...

### ISSUE THREAD

**Issue by Ludo-code** [LDAPAccountManager/lam#200]
Hello, when i use a volume to save config file, in the case of my computer go down and the container must be recreated, i have wanted my config file in docker volume but i have an error when i set it....

The error is : 

```
Configuring LAM
PHP Notice:  A non well formed numeric value encountered in Command line code on line 1
ls: cannot access '/var/lib/ldap-account-manager/config/lam.conf': No such file or directory
cp: cannot stat '/var/lib/ldap-account-manager/config/unix.sample.conf': No such file or directory
```

Thanks for our support...

**Comment by gruberroland** [comment]
Did you run docker as described in https://hub.docker.com/r/ldapaccountmanager/lam?
Please post your command and the file listing of the volume.

**Comment by gruberroland** [comment]
Did you run docker as described in https://hub.docker.com/r/ldapaccountmanager/lam?
Please post your command and the file listing of the volume.

**Comment by Ludo-code** [comment]
I post this after my school week when I come back to work.
Ps : I don't use command line, I'm using portainer.

**Comment by Ludo-code** [comment]
Issue have been solved by reinstalling docker.

**Comment by fsdrw08** [comment]
I have the same error, after check with the env var config, I found that it seems some logic conflic between script and env var description
in the [lam/lam-packaging/docker/start.sh](https://github.com/LDAPAccountManager/lam/blob/205f0e188a99da651bae1652ac73e280596d6971/lam-packaging/docker/start.sh#L41)
```shell
if [ "$LAM_SKIP_PRECONFIGURE" != "true" ]; then
```
but in the [lam/lam-packaging/docker/.env](https://github.com/LDAPAccountManager/lam/blob/fa714646b741919bbe3a115bd919935cb85f408c/lam-packaging/docker/.env#L5-L6):
```
# If set to false the other variables below have no effect.
LAM_SKIP_PRECONFIGURE=false
...
```
I have to set `LAM_SKIP_PRECONFIGURE=true` to make the app run

**Comment by Ludo-code** [comment]
Yes but if skip preconfigure is set, i lose all environnement variable to auto set good value... 
And for me with the preconfigure to on it's not working too...

**Comment by gruberroland** [comment]
@fsdrw08 True, there was a typo in the .env file. Thanks for the hint.
