### ISSUE TITLE
Unable to import with uid instead of cn

### ISSUE THREAD

**Issue by Ludo-code** [LDAPAccountManager/lam#201]
Hello, i have wanted to import user from web interface and, with uid attribute but i have the following error...

![image](https://user-images.githubusercontent.com/56892223/208378849-898f425d-d35f-43e0-99e5-5103949f394f.png)

And if I set back to cn it's working fine...

but some user have the same name and i can't import all users in.... So why uid import doesn't work but in previous version...

**Comment by gruberroland** [comment]
Please attach a sample CSV file that produces this error. Then we can check what is going on.

**Comment by Ludo-code** [comment]
> Please attach a sample CSV file that produces this error. Then we can check what is going on.


[import_exemple.csv](https://github.com/LDAPAccountManager/lam/files/10266814/import_exemple.csv)
Here is it...

**Comment by gruberroland** [comment]
You need to have "inetOrgPerson_userName" as column in the CSV. If you do not specify a user name you cannot use uid as RDN value. See the sample CSV that can be downloaded during the file upload process.
