### ISSUE TITLE
POST fails when float precision is too low

### ISSUE THREAD

**Issue by chusopr** [LDAPAccountManager/lam#202]
I was finding that when I was submitting a form (for example, when creating a new user), the response I was getting was a blank page and the operation was not being done.

After some debugging, I found that the execution was being aborted in the `validateSecurityToken()` function from `lib/security.inc` that is run with every POST request:

https://github.com/LDAPAccountManager/lam/blob/653913768f0007027570478e8b66671d45515dbf/lam/lib/security.inc#L665

Although var_dumping the two variables that are being compared there shows they have the same value, they have different type as the one in $_POST is a string but the one in $_SESSION is a float.

I suspected it could be a locale issue as my locale in PHP is `es_ES` and the decimal separator in Spanish is the comma and not the dot, but str_replacing commas with dots didn't fix the issue.

What did fix the issue was converting the float to string with `strval` before comparing:

```php
if (empty($_POST[getSecurityTokenName()]) || ($_POST[getSecurityTokenName()] != strval($_SESSION[getSecurityTokenName()]))) {
```

**Comment by chusopr** [comment]
Actually, I just found the issue again while editing entries and noticing the `editKey` was having the same issue.
Those values shouldn't have any decimal separator at all, but they are getting one because [precision](https://www.php.net/manual/en/ini.core.php#ini.precision) is too small.

The `precision` value in my php.ini was the default 14 which was making the value of those keys to have a scientific notation like `2,7979840641616E+14` instead of a expected integer like `1672704142110808786503250`.
Increasing `precision` to 25 fixed all these issues.

Maybe something that should be added to the documentation as a requirement or even checked as part of the initial setup / runtime?

**Comment by gruberroland** [comment]
Thanks a lot for the hint and your analysis. We will check how to fix this for next version.
Probably, there will be a switch to numbers + letters to avoid these kind of issues.

**Comment by gruberroland** [comment]
There were several changes done now as this could happen at multiple places. They will be included in the next regular release.
