### ISSUE TITLE
Modification of mailLocalAddress check

### ISSUE THREAD

**Issue by GrueneNeun** [LDAPAccountManager/lam#204]
The check for mailLocalAdress (https://github.com/LDAPAccountManager/lam/blob/20bbb37b6d43ec7754d8d77518ee1e9f6c3f8426/lam/lib/account.inc#L621) allows entries which are formed like "name@domain.tld" and prevents entries like "@domain.tld". The latter would be useful since it is for example the default format for catchall addresses in postfix.

I would like to suggest changing the + in front of the @-symbol to an * to allow "empty" names and so support catchall addresses.

**Comment by gruberroland** [comment]
Thanks a lot for the hint. The requested change was done and will be part of the March release.
