### ISSUE TITLE
No option to enable start_tls connection to ldap server

### ISSUE THREAD

**Issue by hartmannILA** [LDAPAccountManager/lam#205]
Hello,

i can't find an option to enable a start_tls connection between the lam and the openldap-server. Is it possible to set this within the lam.conf or through the web GUI?

**Comment by gruberroland** [comment]
Yes, you can find the TLS checkbox on the top of the first tab of the server profile. Directly under the server address:

https://www.ldap-account-manager.org/static/doc/manual/ch03s02.html#idm862

**Comment by hartmannILA** [comment]
Thank you for the swift response. I actually found that setting before. However, this is only allows completely unencrypted connections (default port: 389) and completely encrypted communication (default port: 636). I am looking for a way to enable `STARTTLS` in order to upgrade an established unsecure LDAP connection on 389 to an encrypted SSL/TLS connection which is the standard LDAP operation for initiating TLS/SSL according to OpenLDAP.

**Comment by gruberroland** [comment]
But this is exactly what the checkbox does. LAM then connects unencrypted and starts TLS directly afterwards.

**Comment by hartmannILA** [comment]
Thanks for the clarification. I wasn't sure that this is what the checkbox does. This issue is closed then.
