### ISSUE TITLE
LAM 8.2 - locking389ds - Option to display "Delete" button (passwordExpirationTime)

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#208]
Hello,
In locking389ds module, a "Delete" button is displayed which enables to delete the "passwordExpirationTime" attribute.
In RHDS, the "passwordExpirationTime" attribute is operation one, maintained by the system, as it is part of the password policy attributes. Removing this attribute is also nor recommended by Red Hat.
Could you, please, add an option in the profile definition for module locking389ds which will enable or disable the display of the button "Delete" ?
Thank you in advance.
Kind regards,
Roland
![LAM_locking389ds_DeleteButton](https://user-images.githubusercontent.com/125443876/218980130-64cecb14-eb1c-4f75-900c-a1e4651eb809.png)

**Comment by gruberroland** [comment]
Hi Roland,

do you have a link to the docs where it is stated that the attribute should not be deleted?
How can the expiration be cleared then? Is there any other way to achieve this?

Best regards
Roland
