### ISSUE TITLE
Can't connect to TLS LDAP

### ISSUE THREAD

**Issue by ForceFaction** [LDAPAccountManager/lam#209]
I'm using the stable docker image of lam.

I can connect to the ldap server with ldapsearch -Z and mediawiki can also connect to it (both TLS), the ldap is setup to _only_ allow tls connections; nothing else.

lam says "Cannot connect to specified LDAP server. Please try again." 

I set a debug file in the general settings tab, made sure it's a location that gets mounted from outside of the container for persistence and restartet the container. There are no logs.

Are there permissions or other things i need to keep in mind?

**Comment by gruberroland** [comment]
Please make sure that you have activated "Activate TLS" on the first tab of your server profile.
The server name in "Server address" must match your certificate, e.g. "ldap://server.company.com" (uses port 389).
If you have a certificate that is not signed by a well-known CA then add your certificate in LAM or your system:

https://www.ldap-account-manager.org/static/doc/manual/apbs03.html

If you mean LDAPS instead of TLS then make sure the server address starts with "ldaps://" (uses port 636).

**Comment by ForceFaction** [comment]
I have activated "Activate TLS" otherwise the error is "Confidentiality required" as the ldap server itself doesn't allow non-tls connections.

I'll have to check the exact name in the certificate, that seems to be the problem here (on first thought, can only test it tomorrow -- to late now). Though i'm pretty sure this is the problem. The certificate itself is an ACME-acquired certifiacte from sectigo, so the standard system certificates should include that.

The only question left is:  Why doesn't lam generate a config file, even though i set it in the settings page?

**Comment by gruberroland** [comment]
Ok, so network connection is fine and only the certificate check fails.

About the config file. It is created when you save LAM's main 
configuration. If no file is generated please check your container file 
system. Maybe the volume mapping is wrong or write access for the 
web-server is not given.

/var/lib/ldap-account-manager/config/config.cfg


Am 16.02.23 um 19:54 schrieb Malte:
> I have activated "Activate TLS" otherwise the error is "Confidentiality required" as the ldap server itself doesn't allow non-tls connections.
> 
> I'll have to check the exact name in the certificate, that seems to be the problem here (on first thought, can only test it tomorrow -- to late now). Though i'm pretty sure this is the problem. The certificate itself is an ACME-acquired certifiacte from sectigo, so the standard system certificates should include that.
> 
> The only question left is:  Why doesn't lam generate a config file, even though i set it in the settings page?
>

**Comment by ForceFaction** [comment]
Thanks for your time, everything works now; includeing the logging :)
