### ISSUE TITLE
LAM doesn't work with PHP > 8.0

### ISSUE THREAD

**Issue by Ekouyoja** [LDAPAccountManager/lam#210]
Hello,
LAM version : 8.2
I get this error when using php version > 8.0

```[Fri Feb 17 08:54:03.248003 2023] [proxy_fcgi:error] [pid 103951:tid 104077] [client 10.203.134.18:41000] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function syslog() in /app/data/lam/lib/security.inc:301\nStack trace:\n#0 /app/data/lam/lib/config.inc(95): logNewMessage()\n#1 /app/data/lam/templates/login.php(192): setlanguage()\n#2 {main}\n  thrown in /app/data/lam/lib/security.inc on line 301', referer: https://pp-lam.toto.pro/index.html```

I got only a warning in version 7.4

Ask me if you need more info

**Comment by gruberroland** [comment]
The function syslog() is a core PHP function and should be present in 
any case. Do you use any custom-compiled PHP? If not, what is your 
operating system/Linux distribution?


Am 17.02.23 um 08:59 schrieb Ekouyoja:
> I get this error when using php version > 8.0
> 
> ```[Fri Feb 17 08:54:03.248003 2023] [proxy_fcgi:error] [pid 103951:tid 104077] [client 10.203.134.18:41000] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function syslog() in /app/data/lam/lib/security.inc:301\nStack trace:\n#0 /app/data/lam/lib/config.inc(95): logNewMessage()\n#1 /app/data/lam/templates/login.php(192): setlanguage()\n#2 {main}\n  thrown in /app/data/lam/lib/security.inc on line 301', referer: https://pp-lam.toto.pro/index.html```
> 
> I got only a warning in version 7.4
> 
> Ask me if you need more info
>

**Comment by Ekouyoja** [comment]
This is a Rocky Linux 9
PHP installed from remi repo
I can provide you my php configuration if needed

**Comment by gruberroland** [comment]
Maybe Rocky Linux does some strange patches to PHP. Try file or remote 
logging instead.

According to PHP docs this function is always present. I was not able to 
find any other case where such a problem occurred.

https://www.php.net/manual/en/network.installation.php

Am 17.02.23 um 09:14 schrieb Ekouyoja:
> This is a Rocky Linux 9
> PHP installed from remi repo
> I can provide you my php configuration if needed
>

**Comment by Ekouyoja** [comment]
I have figured out what's my problem.
In my php.ini i have the syslog function disabled in disable_functions property. By default we disable a tons of function and enable them gradually.
What i don't understand is that it's not properly displayed in error log, normally it does specify to enable the needed function. PHP maybe didn't display it anymore.
What surprise me is that it works with 7.4 php version.
