### ISSUE TITLE
LAM enhancement - OpenID auth

### ISSUE THREAD

**Issue by Ekouyoja** [LDAPAccountManager/lam#211]
Hi,

Is there a way to authenticate by OpenID and use service account to do the modification in place of users ?
With OpenId we can send some groups/roles so the users that is authenticated will be able to choose between different lam profiles in accordance with the content of the token.

For the administration part we can stay with the old systems part (lam master users) with redirection exclusions (so that admin will be not redirected to OpenId provider)

Thanks in advance

**Comment by gruberroland** [comment]
We support OpenID as a 2nd factor for authentication to admin interface 
and self service.

For admin interface you cannot use it to login with a service user.

For self service you can specify a bind user and select the checkbox to 
use it for all operations. In this case, LDAP changes are done with 
exactly this service user. The service user is not bound to any OpenID 
groups.


Am 17.02.23 um 09:12 schrieb Ekouyoja:
> Hi,
> 
> Is there a way to authenticate by OpenID and use service account to do the modification in place of users ?
> With OpenId we can send some groups/roles so the users that is authenticated will be able to choose between different lam profiles in accordance with the content of the token.
> 
> For the administration part we can stay with the old systems part (lam master users) with redirection exclusions (so that admin will be not redirected to OpenId provider)
> 
> Thanks in advance
>

**Comment by Ekouyoja** [comment]
I think I'm not expressing myself correctly.

I have a keycloak where all my internal users connect (they are in a separate LDAP from the users they manage.)
And with LAM i want to manage an LDAP with external users (so my internal users didn't have accounts in)

Now, if want to work with lam properly i need to create them an account in this LDAP (external).
What I would like to do is to connect my internal users (with keycloak/OpenId) to lam interface without having account in external ldap.

**Comment by gruberroland** [comment]
This is not possible with LAM. You will need to have accounts for your 
admins in your external user LDAP.
Maybe you can create a service user in the external LDAP and then use 
2FA with OpenID+KeyKloak. If KeyKloack allows this kind of 
authentication on behalf of someone else.

Another option could be to use an LDAP proxy that combines both LDAP 
databases as a virtual one. Maybe there are rules possible like this.

Am 17.02.23 um 09:37 schrieb Ekouyoja:
> I think I'm not expressing myself correctly.
> 
> I have a keycloak where all my internal users connect (they are in a separate LDAP from the users they manage.)
> And with LAM i want to manage an LDAP with external users (so my internal users didn't have accounts in)
> 
> Now, if want to work with lam properly i need to create them an account in this LDAP (external).
> What I would like to do is to connect my internal users (with keycloak/OpenId) to lam interface without having account in external ldap.
> 
> 
>
