### ISSUE TITLE
Running docker container on new Apple hardware

### ISSUE THREAD

**Issue by lalelunet** [LDAPAccountManager/lam#213]
On systems with the new M1/M2 CPU docker did not start the container without --platform=linux/amd64 parameter. 
Maybe you can give a hint on the docker docs.

Inside the container in the apache config is missing a parameter that result in apache panic and prevent apache from starting. (Operation not supported: AH00023: Couldn't create the mpm-accept mutex. (95)Operation not supported: could not create accept mutex)

The (my) solution was to add the parameter to the config
echo "Mutex posixsem" >> /etc/apache2/apache2.conf

Then apache and the rest of the services start and I get a functional container.

**Comment by gruberroland** [comment]
We will check if a multi-platform build can be supported for the Docker images.

About the Apache issue, please report to Apache itself. The config change might get it working but this only a workaround that cannot be supported by us.

**Comment by gruberroland** [comment]
Please try to run ghcr.io/ldapaccountmanager/lam:testing. This one has multi-arch support.
The next regular release will also be multi-arch.

**Comment by lalelunet** [comment]
I can confirm that this image starts without parameter --platform
Even Apache is starting without the posixsem workaround

Looks good

**Comment by gruberroland** [comment]
Perfect, thanks for the feedback!
