### ISSUE TITLE
Help link 404

### ISSUE THREAD

**Issue by lalelunet** [LDAPAccountManager/lam#214]
In the current stable docker container the help link in the UI links to a not existing target

Link target:
http://127.0.0.1:8080/lam/docs/manual/index.html

Result apache server:
fc00:127::242:ac11:2:80 172.17.0.1 - te [21/Feb/2023:10:16:10 +0000] "GET /lam/docs/manual/index.html HTTP/1.1" 404 490 "http://127.0.0.1:8080/lam/templates/tools/treeView.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

**Comment by gruberroland** [comment]
Thanks, there was an issue due to the special handling of documentation files on Debian Docker. These files are deleted after installation.
The next release will not show the link anymore.
