### ISSUE TITLE
Application becomes unresponsive after few minutes of use. Just white page.

### ISSUE THREAD

**Issue by bohdantverdyi** [LDAPAccountManager/lam#217]
Description:
Summary: When using the application, after a few minutes of normal operation, the application becomes unresponsive and only displays a blank white page. Refreshing the page does not help, and deleting the path from the URL causes the user to be logged out. There are no errors or issues in the application logs. The application is deployed using Kubernetes.

Steps to reproduce:

1. Open the application and start using it.
2. Wait for a few minutes while continuing to use the application.
3. Notice that the application becomes unresponsive and only displays a blank white page.
4. Attempt to refresh the page, but the issue persists.
5. Try deleting the path from the URL, but this only logs the user out of the application.

Expected result: The application should continue to function normally without becoming unresponsive or logging the user out.

Actual result: After a few minutes of use, the application becomes unresponsive and only displays a blank white page. Refreshing the page does not help, and deleting the path from the URL logs the user out.

Screenshot: 
![Screenshot 2023-03-02 at 19 19 08](https://user-images.githubusercontent.com/52817778/222505128-43c124e1-916e-4fc3-8cb4-402760207585.png)

Thank you for your help in resolving this issue.

**Comment by bohdantverdyi** [comment]
This issue looks almost same. #69

When i use without ingress, just `kubectl port-forward ` , it works good.

**Comment by gruberroland** [comment]
Unfortunately, the solution was not reported in the old ticket. It could be related to not enough memory. Or the session files cannot be written because the file system is full.

**Comment by bohdantverdyi** [comment]
@gruberroland I have checked resources. More than 2gb of RAM is availabe. Same with storage 10gb is availabe.

I have no idea where is the issue.

**Comment by gruberroland** [comment]
Please configure LAM to use a remote logger (LAM main configuration). Then you can check if there is anything reported. E.g. invalid session or LAM detects an IP source address change.

**Comment by bohdantverdyi** [comment]
@gruberroland Hmm, really , i've got warning Client IP changed. 
Is it possible to enable ip changing ?
`2023-03-09 19:22:34: LDAP Account Manager (gn1v7h3cXXXXXfp96agvhechq - 10.0.65.3,10.0.0.100,10.0.0.100 - CN=Administrator,CN=Users,DC=org,DC=com) - WARNING: Client IP changed, access denied (10.0.65.3,10.0.0.100,10.0.0.100)`

**Comment by gruberroland** [comment]
The question is why 10.0.65.3 is not static? Maybe you have a load balancer that is not sticky or some web proxy cluster?

**Comment by bohdantverdyi** [comment]
I have a nginx controller which is deployed as DaemonSet, so there is multiple pods for traffic income, each pod has different ip.

**Comment by bohdantverdyi** [comment]
@gruberroland is it possible to allow connection from different ip? It would be easier, thant other solutions)

**Comment by gruberroland** [comment]
The IP check is a security instrument. It prevents the ability to steal cookies and reuse them on another system.
LAM 8.3 will logoff the user instead of just showing a blank page.

**Comment by bohdantverdyi** [comment]
I have fixed this with adding this line to my nginx config: `fastcgi_param REMOTE_ADDR 127.0.0.1`

From security side, it's not the best. But at least it works. Thank you.
