### ISSUE TITLE
Users import with CSV don't create member in Groups if we don't use "additional groups"

### ISSUE THREAD

**Issue by timiti29** [LDAPAccountManager/lam#218]
Hi,

I've created 3 Groups (classical posixGroup) :
- Administrateurs
- Comptabilite
- Test

I've try to import 2 Users with CSV file, i only fill required field and i would like to associate user to one group.

If i only fill "posixAccount_group" and get "posixAccount_additionalGroups" empty the two users are created, when i go to the user profile check "Unix" tabs i can see association to principal group BUT when i go to Group list users are not added as member.

If i fill "posixAccount_group" with the same value and fill "posixAccount_additionalGroups" with "Test" the users are created and showed as group members in the group list.

Edit i use the commit 3820a0f92d20b64b0bc699c55205efaeb291974d for version 8.3RC1

Best Regards

**Comment by gruberroland** [comment]
By default, LAM works the same way as local groups and users. In this case, a primary group membership (posixAccount_group) is not set in /etc/group but only in /etc/passwd.

You can enforce to duplicate the primary membership as additional groups via your server profile. On tab Module settings select Unix -> Options -> Set primary group as memberUid.
This will enforce that a user is also added on the group side.

**Comment by timiti29** [comment]
Hi

I've already check this because the membership of groups doesn't work when creating users without activate this checkbox.

The issue is only when i import users from a CSV file.

It's seems to not check this functionnality when the users is created without additionalgroup and with only primary group.

Best regards

**Comment by gruberroland** [comment]
Thanks a lot for the clarification. This will be fixed in the final 8.3 release.
