### ISSUE TITLE
Bug filter group 

### ISSUE THREAD

**Issue by vinifa** [LDAPAccountManager/lam#223]
Bug when adding or removing a group from a user using the filter. When I filter a group it appears correctly, but when I click to move or remove, the page is refreshed and the group does not go to the defined location. When I don't use the filter, I select the group and set it to move and it works correctly. I have attached a short video with the problem.

https://user-images.githubusercontent.com/106326495/229518912-6884c003-2ee1-4056-9579-5afb373462ea.mp4

LDAP Account Manager - 8.3

**Comment by Radical-Egg** [comment]
I am also running into this issue with LDAP Account Manager Pro - 8.3

**Comment by gruberroland** [comment]
Please enter the following directory:

/usr/share/ldap-account-manager/templates/lib

There is a file starting with "100_lam". Please replace it with the attached file (uncompress it first).
Clear the browser cache afterwards.
[100_lam.8.3.min.tar.gz](https://github.com/LDAPAccountManager/lam/files/11141458/100_lam.8.3.min.tar.gz)

**Comment by vinifa** [comment]
> Please enter the following directory:
> 
> /usr/share/ldap-account-manager/templates/lib
> 
> There is a file starting with "100_lam". Please replace it with the attached file (uncompress it first). Clear the browser cache afterwards. [100_lam.8.3.min.tar.gz](https://github.com/LDAPAccountManager/lam/files/11141458/100_lam.8.3.min.tar.gz)

Tested and working, thank you!
