### ISSUE TITLE
Cannot import user with CSV files

### ISSUE THREAD

**Issue by timiti29** [LDAPAccountManager/lam#224]
Hi

When i try to import users with csv files i got the error "One or more values of the required column "dn_rdn" are missing."

I've check all required data are present and valid.

Here my csv with 1 line head and 1 user:
"dn_suffix";"dn_rdn";"overwrite";"inetOrgPerson_firstName";"inetOrgPerson_lastName";"inetOrgPerson_email";"posixAccount_group";"posixAccount_additionalGroups";"posixAccount_password";"inetOrgPerson_initials";"inetOrgPerson_description";"inetOrgPerson_title";"inetOrgPerson_employeeNumber";"inetOrgPerson_type";"inetOrgPerson_manager";"inetOrgPerson_businessCategory";"inetOrgPerson_street";"inetOrgPerson_postalCode";"inetOrgPerson_address";"inetOrgPerson_registeredAddress";"inetOrgPerson_postOfficeBox";"inetOrgPerson_telephone";"inetOrgPerson_homePhone";"inetOrgPerson_mobile";"inetOrgPerson_fax";"inetOrgPerson_labeledURI";"inetOrgPerson_roomNumber";"inetOrgPerson_departmentNumber";"inetOrgPerson_ou";"inetOrgPerson_o";"inetOrgPerson_l";"inetOrgPerson_st";"inetOrgPerson_carLicense";"inetOrgPerson_physicalDeliveryOfficeName";"posixAccount_cn";"posixAccount_uid";"";"posixAccount_homedir";"posixAccount_shell";"posixAccount_passwordDisabled";"posixAccount_gecos";"shadowAccount_warning";"shadowAccount_ignoreExpire";"shadowAccount_minAge";"shadowAccount_maxAge";"shadowAccount_expireDate";"shadowAccount_lastChange"

"ou=Users,dc=myorg,dc=org";"uid";"";"Tutu";"T";"TutuT@myorg.org";"MyGroup";"";"secret";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";""

I use the last commit e19b14b2064517cc2b84fe5916d1f7680eb11be8

Best regards

**Comment by gruberroland** [comment]
Hi,

you selected RDN to be "uid" but the column "posixAccount_uid" is empty. 
Please set a value or use "cn" as RDN value.


Best regards

Roland


Am 04.04.23 um 18:37 schrieb timiti29:
> Hi
> 
> When i try to import users with csv files i got the error "One or more values of the required column "dn_rdn" are missing."
> 
> I've check all required data are present and valid.
> 
> Here my csv with 1 line head and 1 user:
> "dn_suffix";"dn_rdn";"overwrite";"inetOrgPerson_firstName";"inetOrgPerson_lastName";"inetOrgPerson_email";"posixAccount_group";"posixAccount_additionalGroups";"posixAccount_password";"inetOrgPerson_initials";"inetOrgPerson_description";"inetOrgPerson_title";"inetOrgPerson_employeeNumber";"inetOrgPerson_type";"inetOrgPerson_manager";"inetOrgPerson_businessCategory";"inetOrgPerson_street";"inetOrgPerson_postalCode";"inetOrgPerson_address";"inetOrgPerson_registeredAddress";"inetOrgPerson_postOfficeBox";"inetOrgPerson_telephone";"inetOrgPerson_homePhone";"inetOrgPerson_mobile";"inetOrgPerson_fax";"inetOrgPerson_labeledURI";"inetOrgPerson_roomNumber";"inetOrgPerson_departmentNumber";"inetOrgPerson_ou";"inetOrgPerson_o";"inetOrgPerson_l";"inetOrgPerson_st";"inetOrgPerson_carLicense";"inetOrgPerson_physicalDeliveryOfficeName";"posixAccount_cn";"posixAccount_uid";"";"posixAccount_homedir";"posixAccount_shell";"posixAccount_passwordDisabled";"posixAccount_gecos";"shadowAccount_warning";"shadowAccount_ignoreExpire";"shadowAccount_minAge";"shadowAccount_maxAge";"shadowAccount_expireDate";"shadowAccount_lastChange"
> 
> ***@***.***";"MyGroup";"";"secret";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";""
> 
> I use the last commit e19b14b2064517cc2b84fe5916d1f7680eb11be8
> 
> Best regards
>

**Comment by timiti29** [comment]
Hi, i don't understand.

The users DN need to have UID not CN but i want to let LAM to set the posix UID generated "If empty UID number will be generated automatically." so i let the "posixAccount_uid" empty to auto generate.

I already successfully import user with "uid" as RDN and empty posix_uid, few weeks ago.

Best Regards

**Comment by gruberroland** [comment]
I think you mix up uid and uidNumber. uidNumber can be autogenerated (it 
is a numeric value). But "uid" is the user name. This cannot be generated.



Am 04.04.23 um 19:30 schrieb timiti29:
> Hi, i don't understand.
> 
> The users DN need to have UID not CN but i want to let LAM to set the posix UID generated "If empty UID number will be generated automatically." so i let the "posixAccount_uid" empty to auto generate.
> 
> I already successfully import user with "uid" as RDN and empty posix_uid, few weeks ago.
> 
> Best Regards
>

**Comment by timiti29** [comment]
I've specified "posixAccount_userName" as username or UID associated to UID "LDAP" field in doc (templates/help.php?module=posixAccount&HelpNumber=uid&scope=user) "Nom technique: uid	"

EDIT: I've found the issue, when i extract to CSV from excel i need to change ";" to "," as separator.


Best regards
