### ISSUE TITLE
LAM 8.3 : Add groups to user is impossible with active filter on available groups (groupOfNamesUser)

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#225]
Hello,

On the Add User Groups screen (from module groupOfNamesUser), when the filter on the available groups is active, we cannot add the selected group(s) by clicking the add arrow. This issue has been reproduced on multiple environments on multiple different LDAP servers.
We don't have any relevant error message in our httpd log files.

Could you have a look at this issue, please ?
Thanks in advance.

Kind regards,

Roland - ZAS

**Comment by gruberroland** [comment]
Hi Roland,

please check if the patch in 
https://github.com/LDAPAccountManager/lam/issues/223 works for you.

Best regards

Roland


Am 12.04.23 um 14:35 schrieb gio-zas:
> Hello,
> 
> On the Add User Groups screen (from module groupOfNamesUser), when the filter on the available groups is active, we cannot add the selected group(s) by clicking the add arrow. This issue has been reproduced on multiple environments on multiple different LDAP servers.
> We don't have any relevant error message in our httpd log files.
> 
> Could you have a look at this issue, please ?
> Thanks in advance.
> 
> Kind regards,
> 
> Roland - ZAS
>

**Comment by gio-zas** [comment]
Hi Roland,
Seems the patch solves our problem. Thank you for prompt response!
Cheers,
Roland
