### ISSUE TITLE
AD : Foreign Security display

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#226]
Hi Roland,

We have two AD (AD1 and AD2) and AD1 is configured for LAM (profile with basic users and groups). The AD1 is configured to read the second AD2 (special user from AD2 configured in AD1).

But, some groups on AD1 are refering to users from AD2 but LAM displays those users in an not user-friendly way : 
"S-1-5-21-3993060671-4215906946-993041443-1174 > ForeignSecurityPrincipals > AD1" for example

Is there a way to add an extra LDAP Connector (or more if many AD) in the LAMs profil and tell LAM to try to resolve the foreign reference in a user friendly way with this connector ? Actualy, we do not want to to more than display, but adding or removing from groups will be the next step...
"AD2 connector" can be replaced by a "on the fly credential" form to fill in credentials for AD2

Some performances problems may occurs as well.
Hope everything is understandable. Please get back to me if questions.

Many thanks in advance for answers.
Kind regards,

Roland G - ZAS

**Comment by gruberroland** [comment]
Hi Roland,

for these kind of setups you can use an LDAP proxy. This allows to make multiple LDAP servers visible as one virtual.

Best regards
Roland
