### ISSUE TITLE
Problem with caracter '

### ISSUE THREAD

**Issue by Ekouyoja** [LDAPAccountManager/lam#228]
LAM PRO Version : latest
PHP Version : 8.2.5
How to reproduce :
Create profile with customTypes modules
In module settings, create new attribute and try to set labels with ' in the word like "nom d'usage"
The ' caracter will be transformed to amp;#039;
It's not a problem when it's a label because i can remove it and go on, but the real problem is that the ' caracter is also transformed in the regex field.

I have some error in my php and httpd but don't know if it's related : 
This error appear for all my attributes
PHP Warning:  Undefined array key "birthdate" in /app/data/lam/lib/lists.inc on line 573
PHP Warning:  Undefined array key "rnanomusage" in /app/data/lam/lib/lists.inc on line 1217

**Comment by gruberroland** [comment]
True, there was a double escaping in place. This will be fixed in June (RC version end of May).

**Comment by Ekouyoja** [comment]
I just tried lam pro 8.4 pre-release and i always have the problem @gruberroland

**Comment by gruberroland** [comment]
Can you provide a screenshot of the issue?

**Comment by Ekouyoja** [comment]
Yes you can see that my regex : 
/[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜŸŒÆ'-]+(?:\\s+[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜŸŒÆ'-]+)*$/
is transformed to 
/[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜŸŒÆ&#039;-]+(?:\\s+[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜŸŒÆ&#039;-]+)*$/
The same happen in other tab like label
my ' is transformed when i save the configuration
![image](https://github.com/LDAPAccountManager/lam/assets/16814142/3f819a8a-412e-4a26-bc25-2ffc2dc2a15e)

![image](https://github.com/LDAPAccountManager/lam/assets/16814142/66bc76a0-ccd8-4683-aec7-2f39eae5ce43)

**Comment by gruberroland** [comment]
I do not see any change in the regex. Can you provide a screenshot including the type of field?

**Comment by Ekouyoja** [comment]
![image](https://github.com/LDAPAccountManager/lam/assets/16814142/f40334da-bdd6-4780-b5d9-9d1bed28c016)
![image](https://github.com/LDAPAccountManager/lam/assets/16814142/c4556b3f-9fa9-4f06-8113-7bc652ae3b49)
My regex is /[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜŸŒÆ'-]+(?:\\s+[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜŸŒÆ'-]+)$/ but transformed in my screenshot above

**Comment by gruberroland** [comment]
Unfortunately, I cannot reproduce this with 8.4.RC1. Tried Firefox+Chrome and even set the language to French.
Can you post your php.ini file?

**Comment by Ekouyoja** [comment]
I have try with edge and chrome, language set to French and the same happen. Even in private mode.
Yes here is my php.ini and my php-fpm configuration.
[php_conf.zip](https://github.com/LDAPAccountManager/lam/files/11597293/php_conf.zip)

**Comment by gruberroland** [comment]
Did you restart Apache **and** PHP FPM? Just to be sure that this is not caused by a cached script in FPM.

**Comment by Ekouyoja** [comment]
I have but didn't solve my problem.
So i have reinstall from scratch and it works now.
Thank you for your help
