### ISSUE TITLE
Unable to search customAttribute from server ldap

### ISSUE THREAD

**Issue by bany-hue** [LDAPAccountManager/lam#229]
LAM PRO Version : latest
PHP Version : 8.2.5
Symptoms : Unable to search customAttributes like telephoneNumber from the list

Temporary fix : 
edit lib/lists.inc and add telephonenumber in the list

  protected $serverSideFilterAttributes = array(
                'cn', 'commonname', 'uid', 'description',
                'sn', 'surname', 'gn', 'givenname', 'company', 'mail', 'telephonenumber'
        );

is there another way to do this without modify the file lists.inc

**Comment by gruberroland** [comment]
The custom attributes are searched client-side (just like most other attributes). I was not able to reproduce an issue with the search. Can you provide more details what happens when you enter a search value?
