### ISSUE TITLE
Problems with UNIX user authentication

### ISSUE THREAD

**Issue by josephnoir** [LDAPAccountManager/lam#231]
Hi,

we have a problem with our user login on Linux systems. Our systems use SSSD for authentication using an access filter similar to this one:

```
ldap_access_filter = (|(memberOf=cn=GROUP_1,ou=groups,dc=example)(memberOf=cn=GROUP_2,ou=groups,dc=example))
```

Since we updated our openldap and LAM installation, *new* users cannot get access to our servers anymore. We can assign them either of `GROUP_1` and `GROUP_2` in the LAM, but the query does not see these changes.

Over the last few days, we tracked this down to a conflict between the `memberUid` and `member` attributes in the LDAP data. When we make changes via the LAM frontend, the `memberUid` of the related groups changes, but `member` stays the same.

*A group example:*

```
dn: cn=GROUP_1,ou=groups,dc=example
cn: GROUP_1
objectClass: groupOfNames
objectClass: posixGroup
objectClass: top
gidNumber: 10005
member: uid=user1,ou=people,dc=example
member: uid=user2,ou=people,dc=example
member: uid=user3,ou=people,dc=example
member: uid=user4,ou=people,dc=example
member: uid=user5,ou=people,dc=example
memberUid: user2
memberUid: user3
memberUid: user4
memberUid: user5
memberUid: newUser6
memberUid: newUser7
description: A group description.
```

Here, the new users get added with the `memberUid` attribute, but do not get the corresponding `member` attribute assigned. Similarly, if we remove a user only its `memberUid` is removed.

Before the update this worked without a problem. We updated the LAM from version 6.7 to 8.3. Our OpenLDAP is now version 2.6.2.

Any help would be appreciated.

Kind regards

**Comment by gruberroland** [comment]
For these kind of groups please use the modules (server profile -> tab "Modules"):

* Unix (rfc2307bisPosixGroup)
* Group of names (groupOfNames)

You can edit both member (used for "memberOf" generation) and memberUid. On tab "Module settings" there is also an option to sync both memberships if needed.

**Comment by josephnoir** [comment]
Thank you for the quick answer. I don't see either of those there. For "Groups" the selected module is "posixGroup".

**Comment by gruberroland** [comment]
Both modules are part of LAM Pro. If you have an active LAM Pro subscription please redownload from https://www.ldap-account-manager.org/lamcms/LAMProReleases (looks like you installed the free version).

**Comment by josephnoir** [comment]
Thank you for the clarification.
