### ISSUE TITLE
Issue in File Upload

### ISSUE THREAD

**Issue by vanken18** [LDAPAccountManager/lam#232]
Hi,

We have an issue in the File Upload module when we are uploading CSV file with more than 20 rows. Can't see any error logs regarding the issue. After uploading the CSV file, the page just loading then after 2 to 3 minutes the page will be just display white screen.

**Comment by gruberroland** [comment]
This could be caused by hitting PHP's memory limit. Try to increase "memory_limit" in your php.ini to "512M". Please restart Apache afterwards.

**Comment by vanken18** [comment]
Already set the memory_limit to -1.

**Comment by vanken18** [comment]
No error in php or apache logs and syslog regarding the issue. The white screen displays in the process of /templates/upload/massBuildAccounts.php.

**Comment by gruberroland** [comment]
Solved via email
