### ISSUE TITLE
bug when creating Group of Names

### ISSUE THREAD

**Issue by domaracky** [LDAPAccountManager/lam#233]
When you are creating Group of Names and you want to add Owners or Members using filter, it wont select them and you won't be able to create a group. If you just select the owner(without filter) you can select the owners and create a group.

**Comment by gruberroland** [comment]
Hi,

please try 8.4.RC1: https://github.com/LDAPAccountManager/lam/releases

This should fix the issue.

**Comment by domaracky** [comment]
Just installed 8.4 and filter is working as expected. Thanks!
