### ISSUE TITLE
Not Able to Login

### ISSUE THREAD

**Issue by SolutionsDEV** [LDAPAccountManager/lam#234]
I have OpenDLAP installed, I copied LAM 8.4 file, but it gave me error not connecting to LDAP server, although I tried different settings for the LDAP server, I kept trying, but the error is not showing anymore when I installed ldap-utils, during installation it asks for the administrator password.

When I had the LDAP server error and after the utils installation, LAM prompts for Manager credentials, while in OpenLDAP there is an administrator password and within LAM there is server profile password. I also used "lam" as the password, but no changes.
The error says "Wrong password/user name combination. Please try again.
LDAP error, server says: Invalid credentials"

How can log into LAM?

Thanks,

**Comment by gruberroland** [comment]
I guess you need to configure the account that is used to login to LAM. This is in your server profile, first tab, security settings. Enter your LDAP admin account there. The password "lam" is for LAM's configuration only.

**Comment by SolutionsDEV** [comment]
Thanks for your reply, your answer is really helpful, I know now that I can change the name that appears on the login page, but I am connecting to OpenLDAP which was installed, but I ignore the username and password to access it, I tried to find out on OpenLDAP website the default credentials, but could not find any details. So, I am still trying to access it even in SSH.

Can you help in this regard?

Thanks,

**Comment by gruberroland** [comment]
If you lost your admin password for OpenLDAP then you should ask for help on the OpenLDAP mailinglist. The OpenLDAP maintainers will be able to help you.
