### ISSUE TITLE
Allowing to change the field id for Custom Attributes

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#235]
Hello,
When adding a new field of custom attributes type in a group, with a name of an existing field in another group, both fields will be deleted when deleting only one, which is really annoying.
A great feature will be to be able to change the "Name" of the field. This can be achieved by replacing the actual "Name" by an internal id ; the actual "Name" will be then an alias of this very id and could be changed easily.
Could you add this in the next release ? Thank you.
Kind regards,
Roland

**Comment by gruberroland** [comment]
Thanks for the hint. We will fix the delete issue in the next release.

About "Name" we think about hiding it (as it is more an internal ID) and to display the label and attribute name at this place.

**Comment by gio-zas** [comment]
Great news!
Do you plan to implement an automatic adaptation of the ID of existing fields?
I can provide an export of our largest profile to test if needed.
Kind regards,

**Comment by gruberroland** [comment]
Exactly, old IDs will not be changed. There is no need for a migration or resetup of the fields.

**Comment by gruberroland** [comment]
Implemented, will be published with 8.5.RC1.

**Comment by gio-zas** [comment]
Labels and attribute name are pretty in 8.5.RC1, thanks a lot !
