### ISSUE TITLE
Custom field : group tab for design

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#236]
Hi Roland,
In Custom field module, is it possible to regroup the fields of each groups in tabs dedicated to the each groups? Each tab would allow to modify the attributes of its group and to add/modify/delete its fields.
We would then gain in readability and ergonomics. This would also reduce the size of the (our) html pages.
Thank you in adavnce.
Regards,
Roland

**Comment by gruberroland** [comment]
I am not sure where exactly you want to have tabs displayed? On the edit page of e.g. a user the fields can already be shown as tabs. There is an option in server profile.

**Comment by gio-zas** [comment]
The option you mentionned is at runtime and is very usefull.
I meant the same but at "design" time in "Module setings" : group the attributes in tabs/accordeon at design moment of the profile.
Hope this is a little bit more clear.
Regards,

**Comment by gruberroland** [comment]
Good point! I will put it on the list for 8.6.

**Comment by gruberroland** [comment]
Will be part of 8.6 release.
