### ISSUE TITLE
Custom field form : Stay on the page after saving

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#237]
Hi Roland,
We do sometime several "save" for backup purpose when designing our profile, as we use Custom Field module.
Will it be complicated to change the behavior of the "Save" button and keep the form design screen open after saving ?
A "Close' button, to be added, will replace the current close behavior in the current save process. As option, another button, "Save and close" will keep the current behavior of the "Save" button.
Thank you in advance for the answer.
Regards,
Roland

**Comment by gruberroland** [comment]
I think this is more an edge case that would be only useful for a few users. Therefore, we cannot implement this right now. :(
