### ISSUE TITLE
Opening edit type dhcp returns an epty page

### ISSUE THREAD

**Issue by ygaillard** [LDAPAccountManager/lam#239]
Currently I'm trying to implement the DHCP options. However the PHP call to edit the dhcp entries end nowhere. Whenn calling
<my-domain>/lam/templates/account/edit.php?type=dhcp an empty page opens up. I assume the php Get function cannot call the dhcp options and entries. 
Doing the same with type=user works like a charm.

**Comment by gruberroland** [comment]
Please do not try to enter some URL manually. You need to configure DHCP in account types and account modules of your server profile. Then you can select it in the account type menu inside LAM.

https://www.ldap-account-manager.org/static/doc/manual/ch04s12.html

**Comment by ygaillard** [comment]
I followed these instructions. But when I want to define New DHCP an empty Page opens up

**Comment by gruberroland** [comment]
What are the exact steps to the blank page? Then we can try to reproduce it.
Is the LDAP suffix that you configured for DHCP existing? Are there any existing entries? 

Am 14. Juli 2023 16:02:15 MESZ schrieb Yann Gaillard ***@***.***>:

**Comment by ygaillard** [comment]
I definitely have the schema implemented
![image](https://github.com/LDAPAccountManager/lam/assets/125824751/ae6bdf6e-0d02-4083-8638-f1c8ea6df483)

**Comment by ygaillard** [comment]
I implemented the schema.
![image](https://github.com/LDAPAccountManager/lam/assets/125824751/d8823ab9-cbfa-4a25-8bc5-f1c7dae517a5)
Added in the account schema
![image](https://github.com/LDAPAccountManager/lam/assets/125824751/6c7b1d75-1308-46b1-b26a-395b92a599fb)
Defined the module
![image](https://github.com/LDAPAccountManager/lam/assets/125824751/903e86e6-3570-4f95-8022-b58dbfb8c5b4)
Clicking on new DHCP
![image](https://github.com/LDAPAccountManager/lam/assets/125824751/9c7201e1-73dc-4b62-aae7-840b644ea4b6)

opens an empty page

**Comment by ygaillard** [comment]
I also defined a dummy dhcp from command line but it is not appearing in the list

**Comment by gruberroland** [comment]
Please provide the LDIF export of your dummy entry. Then we can check if 
the object class and attributes are supported.

Am 18.07.23 um 08:29 schrieb Yann Gaillard:

**Comment by ygaillard** [comment]
version: 1

dn: cn=dhcp,ou=Services,dc=example,dc=de
objectClass: dhcpServer
objectClass: top
cn: dhcp

**Comment by ygaillard** [comment]
Second try with information of manual

dn: cn=dhcp,ou=Services,dc=example,dc=de
objectClass: dhcpOptions
objectClass: dhcpServer
objectClass: dhcpService
objectClass: top
cn: dhcp
dhcpComments: Test
dhcpOption: ddns-update-style interim
dhcpOption: default-lease-time 3600
dhcpOption: domain-name "ldap-account-manager.org"
dhcpOption: domain-name-servers 192.168.1.1
dhcpOption: ignore client-updates
dhcpOption: include "mykey"
dhcpOption: max-lease-time 7200
dhcpOption: netbios-name-servers 192.168.1.1
dhcpOption: netbios-node-type 8
dhcpOption: routers 192.168.1.1
dhcpOption: subnet-mask 255.255.255.0
dhcpOption: update-static-leases true

**Comment by ygaillard** [comment]
Is a poosible to enable debug loogging? it's look like lam has some access issues

**Comment by gruberroland** [comment]
You can enable debug logging in LAM's main config: 
https://www.ldap-account-manager.org/static/doc/manual/ch03.html#conf_logging


Am 20.07.23 um 08:35 schrieb Yann Gaillard:
> Is a poosible to enable debug loogging? it's look like lam has some access issues
>

**Comment by gruberroland** [comment]
The LDIF export looks fine. Please use 
cn=dhcp,ou=Services,dc=example,dc=de as LDAP suffix for DHCP in your LAM 
server profile (tab Account types).

Am 20.07.23 um 08:35 schrieb Yann Gaillard:
> Second try with information of manual
> 
> dn: cn=dhcp,ou=Services,dc=example,dc=de
> objectClass: dhcpOptions
> objectClass: dhcpServer
> objectClass: dhcpService
> objectClass: top
> cn: dhcp
> dhcpComments: Test
> dhcpOption: ddns-update-style interim
> dhcpOption: default-lease-time 3600
> dhcpOption: domain-name "ldap-account-manager.org"
> dhcpOption: domain-name-servers 192.168.1.1
> dhcpOption: ignore client-updates
> dhcpOption: include "mykey"
> dhcpOption: max-lease-time 7200
> dhcpOption: netbios-name-servers 192.168.1.1
> dhcpOption: netbios-node-type 8
> dhcpOption: routers 192.168.1.1
> dhcpOption: subnet-mask 255.255.255.0
> dhcpOption: update-static-leases true
> 
> 
>

**Comment by ygaillard** [comment]
> The LDIF export looks fine. Please use cn=dhcp,ou=Services,dc=example,dc=de as LDAP suffix for DHCP in your LAM server profile (tab Account types). Am 20.07.23 um 08:35 schrieb Yann Gaillard:

This solved the problem for the setting, now I can change the DHCP setting from GUI

However new dhcp still don't enables me to set a new one or a new subnet, only opens blank page. The log strangely also does not write out the file. I disable selinux and tried again but in /tmp no file is written...

**Comment by gruberroland** [comment]
Please note that if you have a systemd-based system then /tmp might be 
mapped to a special directory.
Try some other place to be sure. You should see e.g. a message for the 
login.

Am 21.07.23 um 08:20 schrieb Yann Gaillard:
>> The LDIF export looks fine. Please use cn=dhcp,ou=Services,dc=example,dc=de as LDAP suffix for DHCP in your LAM server profile (tab Account types). Am 20.07.23 um 08:35 schrieb Yann Gaillard:
> This solved the problem for the setting, now I can change the DHCP setting from GUI
> 
> However new dhcp still don't enables me to set a new one or a new subnet, only opens blank page. The log strangely also does not write out the file. I disable selinux and tried again but in /tmp no file is written...
>
