### ISSUE TITLE
Editing a new Self Service returns empty page upon trying to save config

### ISSUE THREAD

**Issue by tealey** [LDAPAccountManager/lam#240]
LAM Pro version 8.4 

I m trying to set up a new self service profile and evrytime I attempt to save the config I get a blanke page returned. Tried multiple browsers. Turned up logging and I am seeing this in the Apache error_log:

[Tue Jul 18 14:04:48.933703 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactor in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 106, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933741 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorURL in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 111, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933745 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorClientId in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 113, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933748 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorSecretKey in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 114, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933752 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorLabel in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 117, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933755 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorCaption in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 118, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933758 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorAttribute in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 119, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933761 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorDomain in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 120, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php
[Tue Jul 18 14:04:48.933764 2023] [php7:notice] [pid 22360] [client 10.207.103.219:2241] PHP Notice:  Undefined index: twoFactorRememberDevicePassword in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 123, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php

[Tue Jul 18 14:04:48.933781 2023] [php7:error] [pid 22360] [client 10.207.103.219:2241] PHP Fatal error:  Uncaught TypeError: Typed property selfServiceProfile::$twoFactorRememberDevicePassword must be string, null used in /usr/share/ldap-account-manager/templates/selfService/adminMain.php:123\nStack trace:\n#0 /usr/share/ldap-account-manager/templates/selfService/adminMain.php(300): updateProfileWithPOSTData()\n#1 {main}\n  thrown in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 123, referer: http://dcldapt1.hpc.amslabs.hpecorp.net/lam/templates/selfService/adminMain.php

**Comment by tealey** [comment]
Tried to create a new Self Service profile and still the same errors and blank page when attempting to save.

**Comment by gruberroland** [comment]
Please contact us at ***@***.*** for a patch.

Am 18.07.23 um 21:29 schrieb tealey:

**Comment by tealey** [comment]
Can I get that email address for contact?

**Comment by gruberroland** [comment]
Sorry, Github blocks email addresses in comments now. You can find it here: https://www.ldap-account-manager.org/lamcms/legalInfo

**Comment by gruberroland** [comment]
Fixed via individual patch. Will be part of 8.5 release.
