### ISSUE TITLE
Blank page and login.php as download

### ISSUE THREAD

**Issue by bloodhunterd** [LDAPAccountManager/lam#241]
After I installed the LDAP Account Manager 8.4 (*Debian package from website*) using the documentation, when I go to the web frontend, I am only shown a white page and the `login.php` is downloaded. I am using **Apache 2**, the **PHP 8.2** module is enabled and `phpinfo()` is displayed correctly. Currently I am a bit at a loss.

**Comment by gruberroland** [comment]
Looks like the Apache config is broken. If you get a download of the 
source code of login.php then the Apache PHP module is not used.

You can try to purge Apache and LAM and reinstall. Also, make sure that 
it is not a problem with the browser cache.

Am 25.07.23 um 11:45 schrieb BloodhunterD:
> After I installed the LDAP Account Manager 8.4 (*Debian package from website*) using the documentation, when I go to the web frontend, I am only shown a white page and the `login.php` is downloaded. I am using **Apache 2**, the **PHP 8.2** module is enabled and `phpinfo()` is displayed correctly. Currently I am a bit at a loss.
>

**Comment by bloodhunterd** [comment]
I started again with a fresh installation and unfortunately the same problem occurs. After that I tried with NGINX and again the problem occurred. PHP itself works, both with Apache and with NGINX.

Unfortunately I have no further information, because the page is white and no error is shown. Also in the log files is only the call of the web page recorded, but no error.

**Comment by gruberroland** [comment]
What is your PHP version? Maybe this is the issue. Please check that it 
is something between 7.4 and 8.2.

Am 27.07.23 um 10:55 schrieb BloodhunterD:
> I started again with a fresh installation and unfortunately the same problem occurs. After that I tried with NGINX and again the problem occurred. PHP itself works, both with Apache and with NGINX.
> 
> Unfortunately I have no further information, because the page is white and no error is shown. Also in the log files is only the call of the web page recorded, but no error.
>

**Comment by bloodhunterd** [comment]
As I wrote in my first post, I am using **PHP 8.2**.

**Comment by gruberroland** [comment]
Please try to replace /usr/share/ldap-account-manager/lib/selfservice.inc with https://raw.githubusercontent.com/LDAPAccountManager/lam/develop/lam/lib/selfService.inc. 

Am 27. Juli 2023 23:59:45 MESZ schrieb BloodhunterD ***@***.***>:
