### ISSUE TITLE
Issue with the LDAP Account Manager

### ISSUE THREAD

**Issue by ghost** [LDAPAccountManager/lam#242]
Hello everyone,

I hope you are doing well. As a beginner IT Admin, I am currently working on setting up domain control using OpenLDAP and LDAP Account Manager for our organization. I have encountered some challenges during the setup process and would greatly appreciate your expert guidance and support.

Query 1: Creating Various Groups and Applying Different Policies for Each Group of Users from a Remote Location

I am unsure about the steps to create multiple groups in OpenLDAP and apply distinct policies for each group of users from a remote location. Could you please help me with a detailed walk through to achieve this?

Query 2: Granting Limited Access to Linux Users Managed via LDAP

As a beginner, I am seeking your assistance in understanding how to provide limited access to Linux users when managing their accounts through LDAP. I want to ensure that certain users have restricted permissions and access on Linux systems.

Query 3: Preventing Package/Software Installation

I am facing difficulties in configuring OpenLDAP or LDAP Account Manager to prevent users from installing packages or software on Linux systems. I would like to implement a policy that restricts software installations for specific user groups. Can you kindly guide me through the necessary steps?

Query 4: Restricting USB Port/Device Usage

I need help with configuring LDAP settings to disable or restrict the usage of USB ports or devices for certain user groups. Implementing this security measure is essential to prevent unauthorized data transfer. Any advice or instructions would be incredibly helpful.

I have attached some images of my current setup to provide you with a better understanding of the environment.

![Screenshot from 2023-08-03 12-25-15](https://github.com/LDAPAccountManager/lam/assets/138443110/6b7fe880-05c4-4edd-af53-c44fb356f86b)
![Screenshot from 2023-08-03 12-26-05](https://github.com/LDAPAccountManager/lam/assets/138443110/51755388-00d6-49bb-bd54-786c0fe3d9ee)

I truly appreciate your support and understanding of my beginner's level of knowledge in this field. Your expertise will be invaluable in helping me navigate through these challenges effectively.

Thank you all so much for your time and willingness to assist.

Best regards,
Vaishnavi GHuge

**Comment by gruberroland** [comment]
What kind of permissions do you mean exactly? If it is about permissions 
to LDAP itself (e.g. write access to an LDAP tree) then this is done via 
ACLs. ACLs are set LDAP server-side and cannot be managed by LAM.

Am 01.08.23 um 07:28 schrieb fti-vg:
> I want to ask for help with assigning permissions to users and groups through the ldap account manager.I have already set up the ldap server and client and created users and groups in the ldap account manager. However, I'm unable to assign permissions
>

**Comment by ghost** [comment]
Hello! @gruberroland, 

I hope this message finds you well. Thank you so much for taking the time to reply to my query regarding the domain control setup with OpenLDAP and LDAP Account Manager. Your guidance and support are deeply appreciated.
Based on your suggestions, I have prepared a more detailed query for further assistance. To provide you with a better understanding of my current environment, I have attached a link to a document with additional information and screenshots.
https://github.com/LDAPAccountManager/lam/issues/242#issue-1830492443
Looking forward to your valuable insights and guidance.

Best regards,
Vaishnavi Ghuge

**Comment by gruberroland** [comment]
I am sorry but we can only support the LAM application itself. For such questions you could reach out to our partners for commercial support on such functionality.

https://www.ldap-account-manager.org/lamcms/partners
