### ISSUE TITLE
Not seeing configured questions on self service registration page

### ISSUE THREAD

**Issue by tealey** [LDAPAccountManager/lam#243]
I am not seeing the self service configured questions on the self service registration page. I can see them in the admin page and configured them for a user and also see them by performing a ldapsearch on that use after initial config via administration UI. 

passwordSelfResetQuestion: In what city does your nearest sibling live?
passwordSelfResetQuestion2: What is your favorite food?
passwordSelfResetQuestion3: What was your childhood nickname?
passwordSelfResetAnswer: {CRYPT-SHA512}$6$sPfZGvVI311oWbZZ$GY34r.1hvgZVEZxnbxw
 AbLiewYvEcuxjnsFcAzBuDiL23C4Wmxe/JICQVlGotW86ZKQBoXLGNW74ROOf052X60 c1BmWkd2V
 kkzMTFvV2JaWg==
passwordSelfResetAnswer2: {CRYPT-SHA512}$6$lgbvco.H9o/j/xrz$6rQCejOKKyqSvR7USz
 DJgodbTK7pCgDlUPjdGone4kBUamd53EqL9FJTbljAeWD6.dLyF26Jd2851YHP51iAc/ bGdidmNv
 Lkg5by9qL3hyeg==
passwordSelfResetAnswer3: {CRYPT-SHA512}$6$hbK79nMBJkSazkAa$nA7V1YS/LLGbLRz4Wz
 PycWq.CEzFL5PKz6A8SzKpnhHNrYr6wR0TyjdNDqW01vyvkbYHuZKAGOv6ONJ/J9o/h1 aGJLNzlu
 TUJKa1NhemtBYQ==

The end user should be able to change their questions/answers using the registration page (/lam/templates/selfService/selfServiceLogin.php?scope=user&name=xxx) but they do not appear. How do I make the questions visible to the end user so they can initially answer and later change those answers?

**Comment by gruberroland** [comment]
Did you add them on the self service profile -> tab "Page layout"?
The user also needs to have the object class "passwordSelfReset" to show 
them.


Am 01.08.23 um 21:02 schrieb tealey:
> I am not seeing the self service configured questions on the self service registration page. I can see them in the admin page and configured them for a user and also see them by performing a ldapsearch on that use after initial config via administration UI.
> 
> 
> 
> 
> passwordSelfResetQuestion: In what city does your nearest sibling live?
> passwordSelfResetQuestion2: What is your favorite food?
> passwordSelfResetQuestion3: What was your childhood nickname?
> passwordSelfResetAnswer: {CRYPT-SHA512}$6$sPfZGvVI311oWbZZ$GY34r.1hvgZVEZxnbxw
>   AbLiewYvEcuxjnsFcAzBuDiL23C4Wmxe/JICQVlGotW86ZKQBoXLGNW74ROOf052X60 c1BmWkd2V
>   kkzMTFvV2JaWg==
> passwordSelfResetAnswer2: {CRYPT-SHA512}$6$lgbvco.H9o/j/xrz$6rQCejOKKyqSvR7USz
>   DJgodbTK7pCgDlUPjdGone4kBUamd53EqL9FJTbljAeWD6.dLyF26Jd2851YHP51iAc/ bGdidmNv
>   Lkg5by9qL3hyeg==
> passwordSelfResetAnswer3: {CRYPT-SHA512}$6$hbK79nMBJkSazkAa$nA7V1YS/LLGbLRz4Wz
>   PycWq.CEzFL5PKz6A8SzKpnhHNrYr6wR0TyjdNDqW01vyvkbYHuZKAGOv6ONJ/J9o/h1 aGJLNzlu
>   TUJKa1NhemtBYQ==
> 
> 
> The end user should be able to change their questions/answers using the registration page (/lam/templates/selfService/selfServiceLogin.php?scope=user&name=xxx) but they do not appear. How do I make the questions visible to the end user so they can initially answer and later change those answers?
> 
>
