### ISSUE TITLE
The list of groups is not displayed in PHP 8.X

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#244]
**Context :**
- We are currently running LAM 8.4 on RHEL 7 and Php 7.4.
- We want to migrate to RHEL > 7 and to Php 8.x. We had an anomaly that seems to be related to the Php 8.x. Indeed, LAM 8.4 works well on RHEL 8/9 and Php 7.4 while the anomaly occurs with RHEL 8/9 and Php 8.x.

**Our configuration:**
- Our profiles use for users the modules "CustomBaseType", "customFields" and the "groupOfNamesUser".
- To display groups, our profiles use the "groupOfUniqueNames" module. 

**Anomaly:**
- If the list of users is displayed and everything is functional, however, for groups, the list of groups is not displayed and only the banner giving the number of groups and pagination links is displayed.
- The table with class="accountlist responsive-table" is not built (absent from the Html code).
- There is no httpd server side error message.

Could you look at this problem, please? Thank you.

[SKY-8319.pdf](https://github.com/LDAPAccountManager/lam/files/12369312/SKY-8319.pdf)

**Comment by gio-zas** [comment]
More info : lib/lists.inc is involved at line 430 ==> $this->addDataElements($data, $info, $onClickEvents, $onDoubleClickEvents);"

[SKY-8319.debug.pdf](https://github.com/LDAPAccountManager/lam/files/12369607/SKY-8319.debug.pdf)

**Comment by gio-zas** [comment]
More info : the real problem is in addDataElements function at line 617 of lib/lists.inc file ==>"$attributeName = strtolower($attributeName);"

Third element "description" of the Array "$this->attrArray" hangs the function.

[SKY-8319.debug2.pdf](https://github.com/LDAPAccountManager/lam/files/12371026/SKY-8319.debug2.pdf)

**Comment by gruberroland** [comment]
The problem is related to "dn" in the list of columns. Please remove "dn" from the view for the moment.
We will fix this in the next release.

**Comment by gio-zas** [comment]
We've installed the 8.5.RC1 on Php 7.2. We have to upgrade to Php 8.2 next days... Stay tuned for feedback !

**Comment by gio-zas** [comment]
The 8.5.RC1 solved this issue : tested with Php 8.1. Thanks.
