### ISSUE TITLE
Custom Scripts: LAM thinks changes were not saved when postModify/postCreate script fails

### ISSUE THREAD

**Issue by m-bach** [LDAPAccountManager/lam#245]
When a postModify/postCreate script exits with an exit code other than 0, the error is displayed at the top and the form page stays open (just like it is when a preCreate/preModify script fails).
The problem is that the changes are already applied to the LDAP but when hitting "Save" again, LAM tries to apply the changes again, which leads to error messages like:
![MicrosoftTeams-image](https://github.com/LDAPAccountManager/lam/assets/88787401/83e35f9e-daff-43ee-984f-6b7398430843)

**Comment by gruberroland** [comment]
Thanks a lot for your report. The next release will no longer allow to save again in such cases.
