### ISSUE TITLE
Custom scripts fails (LAM 8.5 RC1 Pro)

### ISSUE THREAD

**Issue by werkmana** [LDAPAccountManager/lam#246]
Hello,
when I add a Custom script "user preDelete" an error message  is displayed when I delete an user.
Test script:
user preDelete /bin/true

Error: (German)
Fehler beim Löschen von DN: .......
Ausgabe des Kommandos "/bin/true" mit Returncode 0

This error also occurred in version 8.4

**Comment by gruberroland** [comment]
Thanks a lot for your report, this will be fixed in the final 8.5 release.
