### ISSUE TITLE
Feature request: Option to blend-out "Remove extension"

### ISSUE THREAD

**Issue by werkmana** [LDAPAccountManager/lam#247]
Hello,
It wold be very nice to be able to blend-out the button "Remove extension" (Shadow, Custom fields, ..)
Maybe in combination with an option to "Automatically add this extension" in the server profile settings. (I know it is possible to do this in the "Profile editor" right now)
Greetings
Alex

**Comment by gruberroland** [comment]
You could add a custom CSS file and hide elements with id "btn_remObjectClass".
This would hide all those buttons.

See also here for integrating custom CSS/JS:
https://www.ldap-account-manager.org/static/doc/manual/apf.html

As this seems more an exotic case we do not plan to add an option to LAM for the moment.

**Comment by werkmana** [comment]
added a file /usr/share/ldap-account-manager/style/900_test.css

### content start ###
[id^='btn_customFields_delGroup'] {
 display: none !important;
}

[id^='btn_form_subpage_shadowAccount_attributes_remObjectClass'] {
 display: none !important;
}
### content end ###

Now the buttons are gone :-) Thanks

**Comment by gruberroland** [comment]
Perfect :)
