### ISSUE TITLE
Feature request: Hide "Create PDF file" in listview

### ISSUE THREAD

**Issue by werkmana** [LDAPAccountManager/lam#248]
Hello,
I want to hide the button "Create PDF file" from the User-List / Group-List.

I tried it with the file style/900_test.css

[id^='btn_createPDF_'] {
 display: none !important;
}

that did not work.

I can remove it by editing the file lib/lists.inc (PDF button), but this will be overwritten by the next update.

Is it possible to hide it with css?
when not, an option in the config to hide the pdf button would be nice :-)
Greetings,
Alex

**Comment by werkmana** [comment]
Found a solution :-)

templates/lib/900_test.js
#### Content
document.addEventListener("DOMContentLoaded", function() {
        const elem = document.querySelectorAll('[id^=btn_createPDF]');
        for (const ele of elem) {
        ele.style.display = 'none';
        }
});
####

**Comment by gruberroland** [comment]
The CSS from first post worked for me. Maybe browser caching issue?

**Comment by werkmana** [comment]
after deleting the browser cache, the first solution worked for me to.
Thanks
