### ISSUE TITLE
"RDN identifier" to be configured not to be editable for certain profiles

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#249]
Hello,

When creating/modifying an account, we want the "RDN identifier " attribute not to be editable by the user, for certain profiles.

This function should be configurable in the profile and in the template profile (creation template profile, "Profile editor"), because we want, for some profiles, to be able to modify the value of "RDN identifier".

Thank you in advance,
Kind regards,

Roland

**Comment by gio-zas** [comment]
![LAM_249](https://github.com/LDAPAccountManager/lam/assets/125443876/da895f5e-6135-4df5-bc48-c73a94a24353)

**Comment by gruberroland** [comment]
This is not possible as the used profile is not stored anywhere for accounts. This means when an account is edited LAM does not know about a profile.
I think you need to solve this on an organizational level rather then by LAM.

**Comment by gio-zas** [comment]
I think you misunderstand our request.

What we are asking for is to add an option to account profile in order to freeze the "RDN identifier " attribute ; ie the user will not be able to change displayed value when creating/updating account.
Based on this option, we would like to add 'disabled = "disabled"' to Form attribute "accountContainerRDN"  "<select class="" name="accountContainerRDN" id="accountContainerRDN" size="1">"
==> should it be at line 1109/1110 of lib/modules.inc file ?

Indeed, we don’t want to store the used profile for accounts in profile as you mentionned.

Hope this complement will clarify our request

**Comment by gruberroland** [comment]
In this case I suggest to use a custom JavaScript to disable the dropdown.

https://www.ldap-account-manager.org/static/doc/manual/apf.html

**Comment by gio-zas** [comment]
It looks good... but we have several profiles by apache uri in which we want to have this feature, and for others, not.
By using custom css, all uris will be impacted, as there is only one program environment for all account profiles.
Did I understand well how custom css worked?

**Comment by gruberroland** [comment]
Yes, custom CSS+JS will be executed for all server environments. In this case you might want to deny account creation in specific sub-DNs using ACLs for specific user groups.

**Comment by gio-zas** [comment]
Well, we don't want to deny account creation in fact, only disable the change of value of accountContainerRDN attribute.
Could this be in LAM ?

**Comment by gruberroland** [comment]
The RDN selection is a very basic setting in LAM. Therefore, we would like to avoid to add such a logic.
You can preset the field with the profile editor and if no changes should be possible then ACLs would be the way to go.

If there is an important use-case for this please provide more details. E.g. why a user should be able to create entries in a subDN for server profile A but not for server profile B.

**Comment by gio-zas** [comment]
We had private mail exchanges with LAM Dev on the subject and we aggreed to use custom scripts with PreCreate an PreModify to check the RDN and the business key accordance.
Nevertheless, we still miss the variable of "Account subtype" info in custom script.

**Comment by gruberroland** [comment]
8.6 will allow to specify the subtype (e.g. user:user_1). The subtypes are listed in help text of the field.
