### ISSUE TITLE
No cut/move icon

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#250]
Hi Roland, sorry, this is not a bug, it's a request.

I see there is a copy user accounts icon and I think we should also have a cut/move one.

In our case we do not delete the user accounts when they end their relationship with the entity, what we do is move them to another branch of the ldap ou=Nousers and they remain there in case they are needed in the future.

I think it would be very good to have the cut/move user button and a custom script with that action.

Thanks in advance and greetings

**Comment by gruberroland** [comment]
Hi,
to move entries you can edit them and then change the LDAP suffix of the entry. This will move it to the new suffix.

**Comment by gruberroland** [comment]
There is also a cron job to move users if that helps:

https://www.ldap-account-manager.org/static/doc/manual/ch03s02.html#idm1172

**Comment by informaticavera** [comment]
Sounds good, we can use the shadow object and the "Delete or move expired accounts" jobs.

From the shadow object we only need to use the "expired" field. Can the other fields be hidden?
And the last question, in my configuration I cannot move the entries to another suffix, where is the option to enable it?

Sorry for the inconvenience Roland and thank you very much for your help

**Comment by gruberroland** [comment]
Unfortunately, the other shadowAccount fields cannot be hidden via configuration. Could be done using custom CSS:

https://www.ldap-account-manager.org/static/doc/manual/apf.html

The suffix can be selected when you edit a user. It is in the top bar (dropdown "Suffix"). Please note that only subsuffixes under the suffix for the given account type are shown.

**Comment by informaticavera** [comment]
Ok Roland, why are there two identical entries in the job list?

![Captura desde 2023-10-09 08-01-04](https://github.com/LDAPAccountManager/lam/assets/32567126/b05c3250-3317-4af7-a660-47d4d7394b48)

**Comment by gruberroland** [comment]
Can you provide a screenshot in English? Maybe the translation is wrong.

**Comment by informaticavera** [comment]
Yes you're right

lam/lam/locale/es_ES/LC_MESSAGES/messages.po
9641 msgstr "Notificar a los usuarios el vencimiento de la cuenta"

**Comment by gruberroland** [comment]
Thanks, the translation will be fixed in the next release.
