### ISSUE TITLE
LDAP filter for GroupOfName under User

### ISSUE THREAD

**Issue by m-bach** [LDAPAccountManager/lam#252]
Hi,

In the LAM profile we have configured an "Additional LDAP filter" under "Account types" for "Groups of names".
This works great.

But when editing a user under "Unix" -> "Edit groups" all groupOfNames can be seen. Is there any possibility to add a ldap filter here?

**Comment by gruberroland** [comment]
Which version do you use? I was not able to reproduce this with 8.5.

**Comment by m-bach** [comment]
I am sorry while trying to create a minimal reproducible example I realised that the issue is not what I thought it is. It indeed is working as expected.

We are using the Account type "Group of names" twice. And the list under edit groups contains results from both. Is there any way to limit the list to one of those account types?

**Comment by gruberroland** [comment]
There is no possibility to limit the search to only one of the group of names account types. In this case it would be better to create separate server profiles. 

Am 11. Oktober 2023 12:56:52 MESZ schrieb Markus Bach ***@***.***>:
