### ISSUE TITLE
Allow the addition of files as attachments to emails to be referenced in emails

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#257]
Hi Roland,

The configurations of mail messages do not offer the addition of attachment. Attachments are useful when they concern image files that are referenced in the body of the email message (usually HTML). This allows a "friendly" display of the mail message, without having to allow the mail client to access the resource "externally" (image).

Would it be possible to include a file list in the email message? list of "local" files separated by ";", for example?

Is a solution with a custom script possible?

Thank you in advance.

Kind regards,

Roland

**Comment by gruberroland** [comment]
This seems more of an edge case. Therefore, we will not support attached images directly.
But you can embed them already inline with the data source:

https://sendgrid.com/en-us/blog/embedding-images-emails-facts#2-html-inline-embedding-base64-encoding

**Comment by gio-zas** [comment]
We apply the base64 encoded image in html template and it solves this issue.
Thank for the prompt reply.
Cheers
