### ISSUE TITLE
Adding custom classes to SelfServices + Display technical info

### ISSUE THREAD

**Issue by gio-zas** [LDAPAccountManager/lam#258]
Hi Roland,

The Self Service does not offer to manage the attributes of custom classes and therefore only the standard attributes are proposed to be modified and/or displayed.

Is it possible to propose to manage one or more custom classes in Self Service? We would like to be able to modify the cn attribute that belongs to a custom class.

In addition, the current list of attributes proposed, does not allow to know what is the underlying class and attribute, and we had to edit the html source to know.

Would it be possible to add in addition to the current display, the class and attribute reference to the proposed elements?

Thank you in advance for your answers to both questions.

Kind regards,

Roland

**Comment by gruberroland** [comment]
Hi Roland,

custom fields are supported in self service, too:

https://www.ldap-account-manager.org/static/doc/manual/ch07s03.html#idm5955

Please note that the predefined self service fields do not check the object class by default. This means you can use the Unix: Common name field to manage cn even if the user has no posixAccount.

I will update the docs to include the attribute names here:

https://www.ldap-account-manager.org/static/doc/manual/ch07s03.html#idm5398

Best regards

Roland

**Comment by gio-zas** [comment]
Forgot this feature in module parameter : we add the "cn" in custom field, without class name and it works.
Thanks again for prompt reply for this trivial question...
Regards
