### ISSUE TITLE
Ability to change password change method to EXOP?

### ISSUE THREAD

**Issue by e-alfred** [LDAPAccountManager/lam#26]
Hello,

is it possible to change the password using the PASSMOD operation instead of a MOD operation? I am using smbkrb5pwd (https://github.com/opinsys/smbkrb5pwd) to keep passwords between LDAP and Kerberos in sync, this LDAP overlay executes after a PASSMOD operation to change the password in Kerberos. This works well with ldapscripts as well as executing passwd for a logged in user, but LDAP Account Manager is the only tool I use that does not use that operation and instead modifies just the userPassword attribute.

Here is the difference I can see in the log entries if I change a passrod in LAM and using passwd, respectively:

> Mar  6 13:20:48 ldapserver slapd[3250]: conn=2235 op=3 MOD attr=userPassword

> Mar  6 13:25:13 ldapserver slapd[3250]: conn=2242 op=1 PASSMOD id="cn=testuser,ou=People,dc=my,dc=domain" new

Thank you

**Comment by gruberroland** [comment]
Hi,

the problem is that PHP currently does not support this password change method. I can only ask you to regularly vote for it here:

https://bugs.php.net/bug.php?id=69445

**Comment by gruberroland** [comment]
PHP finally fixed this but it will only be part of PHP 7.2. So still some time till this can be used.

**Comment by gruberroland** [comment]
Implemented, will be published with 6.5.
PHP 7.2 is required for this feature.
