### ISSUE TITLE
LamPro Manager

### ISSUE THREAD

**Issue by rohani2255** [LDAPAccountManager/lam#261]
After installation of LamPro manager, I updated my configuration via CLI and also LamPro Module Manager. However, there is no changes reflect and Lampro still taking the default info. When try to upload/add user credentials it gives error that, Failed to create entry, Server unwilling to perform

Please help, I did reinstall the package but still working

Best Regards,

**Comment by gruberroland** [comment]
Please provide more details about the issue (e.g. screenshots). I am unsure what exactly you mean with "still taking the default info" and "upload/add user credentials".

**Comment by rohani2255** [comment]
We are able to solved the problem. Thank u do much

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
