### ISSUE TITLE
Problem to access LDAP via simple authentication

### ISSUE THREAD

**Issue by rohani2255** [LDAPAccountManager/lam#263]
We have issue to access LDAP via SASL (simple authentication), we have checked the password and this is correct. Please find the below screenshot.
root@tenang:/etc/ldap# ldapsearch -x -H Ldaps://tenang.perkeso.gov.my:636 -b "dc=perkeso,dc=gov,dc=my" -D "cn=admin,dc=perkeso,dc=gov,dc=my" -W
Enter LDAP Password:
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

**Comment by gruberroland** [comment]
Try "ldaps://" instead of "**L**daps://"
The error message is a bout a connection problem, not wrong password. If the fix above does not work then maybe your LDAP server certificate is not trusted.

**Comment by rohani2255** [comment]
Still same issue after run the command base on your input. We use a wildcard cert from Digicert and tested working for other servers

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gruberroland** [comment]
Try adding the debug level to the command, e.g. "-d 1".
You can also temporarily set "TLS_REQCERT never" in /etc/ldap/ldap.conf to disable certificate check.
