### ISSUE TITLE
Can not login account admin

### ISSUE THREAD

**Issue by piseydba** [LDAPAccountManager/lam#274]
Can not login account admin/adminpw on LDAPAccontManger

LDAP error, server says: Invalid credentials 

![111111111](https://github.com/LDAPAccountManager/lam/assets/26401587/a86e5b92-923c-4e87-8505-945a9cea9ce5)

**Comment by gruberroland** [comment]
Please check your server profile, first tab, "List of valid users". Maybe the DN entered there does not match what is in LDAP.

**Comment by piseydba** [comment]
> Please check your server profile, first tab, "List of valid users". Maybe the DN entered there does not match what is in LDAP.

you're right, I set LDAP_DOMAIN=my-dev.example.gov.kh  in .env file. 

the ldap server container used the full LDAP_DOMAIN as DN, but LdapAccountmanager use DN only this dc=example,dc=gov,dc=kh.
