### ISSUE TITLE
export telefonlists to pdf

### ISSUE THREAD

**Issue by BurtGummer** [LDAPAccountManager/lam#28]
Hello,

i use Lam Pro 5.4. Is it possible, to export Telefon Lists as pdf, for example:

Max Mustermann    00000000000000
Klaus Mustermann  111111111111
Sabine Musterfrau   33333333333

I think i can just export one user per pdf?

To select a Account (has telefonnumber) i can create a new group.

**Comment by gruberroland** [comment]
Hi,

you can use the export feature in tree view for this:
https://www.ldap-account-manager.org/static/doc/manual/ch04s27.html

This allows CSV export that is similar to your example.

PDF export is one LDAP entry per page. It also provides no text export.
