### ISSUE TITLE
Problem with credentials

### ISSUE THREAD

**Issue by Doujinx28** [LDAPAccountManager/lam#286]
Hello, my name is Norbert.
I have issue with login into LAM manager.
Cant really get to work my ldap.

<img width="326" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/6c9e3834-a2e2-4736-9472-c463f1d81723">

My lam profile settings
<img width="473" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/9388bd64-29db-4df3-9fe8-c3644a8762ca">

My ldap.conf file
<img width="407" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/ffb5d14c-60a4-44d8-8dd8-ce991edaac4b">

When im doing ldapsearch -x
<img width="263" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/8bfa75cc-9cd3-4baa-bebd-2c8435b0851b">

When im doing ldapwhoami 
<img width="635" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/ec3521bd-087b-4648-a945-7065dfb36d64">

My /etc/ldap-account-manager/config.cfg
<img width="541" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/7cc66ae4-3030-4fe3-bdca-2c3acfc50e9c">

When im doing slapcat
<img width="331" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/3d693326-6d4d-4562-903e-b2a92bed463e">

**Comment by gruberroland** [comment]
Hi, please enter the configuration -> server profiles and edit your server profile. On top of first tab you can set which DNs should be shown on the login page. In your case this would be cn=admin,dc=ubuntuserverthree,dc=com.
Please also check the other tabs to avoid you have invalid example values set.

**Comment by Doujinx28** [comment]
Hi again, Thanks, its workded ! 
<img width="663" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/152737992/857233f4-6f2a-4ffe-8e14-6c814b804c52">
