### ISSUE TITLE
HASH PASSWORD SELF SERVICE REG

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#287]
Hello Roland, when you create an account from the self-registration portal, the password hash is SSHA, however we have the MD5 option checked in the configuration. We only see this in the log.

root@ayuntamiento:~# more /var/log/apache2/error.log
[Tue Jan 16 00:00:01.529014 2024] [ssl:warn] [pid 1157] AH01909: 10.200.1.100:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jan 16 00:00:01.529210 2024] [mpm_prefork:notice] [pid 1157] AH00163: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Tue Jan 16 00:00:01.529216 2024] [core:notice] [pid 1157] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 16 12:59:56.972828 2024] [php:warn] [pid 184853] [client 10.200.1.19:32493] PHP Warning:  Undefined array key 2 in /usr/share/ldap-account-manager/lib/baseModule.inc on line 747, referer: http://10.200.1.100/lam/templates/config
/moduleSettings.php
[Tue Jan 16 12:59:56.975066 2024] [php:warn] [pid 184853] [client 10.200.1.19:32493] PHP Warning:  Undefined array key 2 in /usr/share/ldap-account-manager/lib/baseModule.inc on line 747, referer: http://10.200.1.100/lam/templates/config
/moduleSettings.php
[Tue Jan 16 12:59:56.975074 2024] [php:warn] [pid 184853] [client 10.200.1.19:32493] PHP Warning:  Undefined array key 3 in /usr/share/ldap-account-manager/lib/baseModule.inc on line 747, referer: http://10.200.1.100/lam/templates/config
/moduleSettings.php
[Tue Jan 16 12:59:56.975077 2024] [php:warn] [pid 184853] [client 10.200.1.19:32493] PHP Warning:  Undefined array key 4 in /usr/share/ldap-account-manager/lib/baseModule.inc on line 747, referer: http://10.200.1.100/lam/templates/config
/moduleSettings.php
[Tue Jan 16 12:59:56.975081 2024] [php:warn] [pid 184853] [client 10.200.1.19:32493] PHP Warning:  Undefined array key 5 in /usr/share/ldap-account-manager/lib/baseModule.inc on line 747, referer: http://10.200.1.100/lam/templates/config
/moduleSettings.php
[Tue Jan 16 13:01:02.326549 2024] [php:warn] [pid 243308] [client 10.200.1.19:32520] PHP Warning:  Undefined array key "selfService_password" in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 39, referer: htt
p://10.200.1.100/lam/templates/selfService/adminLogin.php
[Tue Jan 16 13:01:05.591701 2024] [php:warn] [pid 243308] [client 10.200.1.19:32520] PHP Warning:  Undefined array key "selfService_password" in /usr/share/ldap-account-manager/templates/selfService/adminMain.php on line 39

**Comment by gruberroland** [comment]
The self service has its own configuration for the hash type. You can change it in **self service profile** -> tab Module settings -> Unix -> Password hash type.

There is no connection between a server profile and the self service profiles. This is why the setting needs to be done twice.

Did this help?

**Comment by informaticavera** [comment]
We have the hash type configured to md5 and yet the users are created with SSHA

![Captura desde 2024-01-17 07-12-22](https://github.com/LDAPAccountManager/lam/assets/32567126/db86db97-faf5-4f41-9249-c0a91b2741e7)
![Captura desde 2024-01-17 07-12-15](https://github.com/LDAPAccountManager/lam/assets/32567126/6579fcbd-1a25-4e4a-be0a-78ac45e655c7)

**Comment by gruberroland** [comment]
Thanks for the update. I will take a closer look what is going wrong.

**Comment by gruberroland** [comment]
Thanks a lot for your report. There was a small typo in the code. I sent you a patch via email.
