### ISSUE TITLE
Version 8.6: invalid PDF

### ISSUE THREAD

**Issue by cosine-measurement-systems** [LDAPAccountManager/lam#290]
Using 8.6. When I create a PDF for a user the file is invalid (okular on Linux cannot open it). tried Firefox and Chromium.
Opening the PDF file with a text editor shows that at the top some HTML text that probably does not belong there. I enclose a couple of images to show the problem.
Giuseppe
![Screenshot from 2024-01-26 17-47-00](https://github.com/LDAPAccountManager/lam/assets/117782832/a8aec516-4ce2-4318-b296-0cd50372376b)
![Screenshot from 2024-01-26 17-47-27](https://github.com/LDAPAccountManager/lam/assets/117782832/d175db82-8466-49c7-a335-046018a75077)

**Comment by gruberroland** [comment]
I was not able to reproduce this. Can you attach such a file? What is your operating system and PHP version?

**Comment by cosine-measurement-systems** [comment]
Hi, I now understand how I can reproduce the problem. We have LAM behind an Apache reverse proxy, and the problem occurs when the PDF is generated via the proxy interface. The problem appeared when we went from 8.2 to 8.6. So the problem is mine, not yours. If you have any advice as to what might have changed to cause this let me know.
Giuseppe
