### ISSUE TITLE
Can't contact LDAP server on CentOS7/RHEL7

### ISSUE THREAD

**Issue by vanloswang** [LDAPAccountManager/lam#3]
Setup a openldap server by following https://www.certdepot.net/rhel7-configure-ldap-directory-service-user-connection/.

And setup apache+php environment, then setup LAM, but it fails and report the following error when I login as manager.

``` bash
LDAP error, server says:
(-1) Can't contact LDAP server
```

The ldap client work ok by search the Manager user in ldap:

``` bash
# ldapsearch -x -h localhost -b cn=Manager,dc=example,dc=com
```

It returns:

``` bash
# extended LDIF
#
# LDAPv3
# base <cn=Manager,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# Manager, example.com
dn: cn=Manager,dc=example,dc=com
objectClass: organizationalRole
cn: Manager
description: Directory Manager

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

So how to fix it?

**Comment by vanloswang** [comment]
It is a selinux issue, turn it off by following cmd will login into LAM:

``` bash
setenforce 0
```

I don't know which selinux policy to set for LAM. After reading manual for selinux related content, I found:

``` bash
Please note that LAM does not ship with a selinux policy. Please disable selinux or create your own policy.
```

Disabling selinux is not a good idea, does anyone knows howto setup a selinux policy for LAM?

**Comment by gruberroland** [comment]
Maybe the problem is not LAM but your web server? Since LAM seems to be able to read and write its config files.
Try setting selinux to permissive mode and check the violations that are logged.

http://www.selinuxproject.org/page/Guide/Mode

**Comment by gruberroland** [comment]
I added a section to the manual:

https://www.ldap-account-manager.org/static/doc/manual/apbs04.html

**Comment by vanloswang** [comment]
@gruberroland It's webserver permission issue. By following the manual you added, it works for me. Thank you very much.
