### ISSUE TITLE
mcrypt_encrypt() is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by luckyao** [LDAPAccountManager/lam#30]
Hi, when i use tree view, LAM give me blow error!

Error
Unrecognized error number: 8192: Function mcrypt_encrypt() is deprecated
PHP Debug Backtrace
File	/data/www/lam/templates/3rdParty/pla/lib/functions.php (161)
 	Function	error (a:5:{i:0;s:72:"Unrecognized error number: 8192: Fu...)
File	/data/www/lam/lib/security.inc (591)
 	Function	app_error_handler (a:5:{i:0;i:8192;i:1;s:39:"Function mcrypt_encrypt(...)
File	/data/www/lam/lib/modules.inc (2209)
 	Function	lamEncrypt (a:1:{i:0;s:2:"N;";})
File	/data/www/lam/lib/modules.inc ()
 	Function	__sleep (a:0:{})

**Comment by gruberroland** [comment]
Hi,

thanks a lot for your report. This is already fixed in the development version and will be published with next release in June. If possible you can downgrade to PHP 7.0 or remove the MCrypt module from PHP 7.1 (optional feature).
