### ISSUE TITLE
Fatal error: Uncaught TypeError: usort(): Argument #1 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by Username-is-really-not-available** [LDAPAccountManager/lam#302]
Hi there,

I've installed version 8.6 on a server, LAM told me, it needs php >=8.0.2. OK, fine! So I've move the code to another machine. The other machine has PHP 8.2.7.
After entering login details all I can see is an empty/white page ...
The reason is an programming error: OK, let me try 8.7.RC1! still the same problem:

`Fatal error: Uncaught TypeError: usort(): Argument #1 ($array) must be of type array, null given in /srv/www/lam/app/lib/modules/freeRadius.inc:761 Stack trace:
 #0 /srv/www/lam/app/lib/modules/freeRadius.inc(761): usort()
  #1 /srv/www/lam/app/lib/modules/freeRadius.inc(182): freeRadius->getProfiles()
  #2 /srv/www/lam/app/lib/baseModule.inc(118): freeRadius->get_metaData()
  #3 /srv/www/lam/app/lib/modules/freeRadius.inc(58): baseModule->__construct()
  #4 /srv/www/lam/app/lib/account.inc(1657): freeRadius->__construct()
  #5 /srv/www/lam/app/lib/modules.inc(307): moduleCache::getModule()
  #6 /srv/www/lam/app/lib/config.inc(1257): getAvailableModules()
  #7 /srv/www/lam/app/lib/config.inc(647): LAMConfig->removeInvalidModules() 
  #8 /srv/www/lam/app/lib/config.inc(354): ServerProfilePersistenceStrategyFiles->loadProfile()
  #9 /srv/www/lam/app/lib/profiles.inc(136): ServerProfilePersistenceManager->loadProfile()
 #10 /srv/www/lam/app/templates/main.php(51): LAM\PROFILES\AccountProfilePersistenceManager->installAccountProfileTemplates()
 #11 {main} thrown in /srv/www/lam/app/lib/modules/freeRadius.inc on line 761`
 
 There were also some Deprecated warnings:
 `Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /srv/www/lam/app/lib/modules.inc on line 741
  Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /srv/www/lam/app/lib/account.inc on line 181`
  
Ping me, if you need more information

Best Regards,
Pascal

**Comment by gruberroland** [comment]
Thanks a lot for your report. Both issues will be fixed in 8.7.
