### ISSUE TITLE
Warning: Undefined array key "xxx" in lib/lists.inc on line 627

### ISSUE THREAD

**Issue by Username-is-really-not-available** [LDAPAccountManager/lam#303]
Hi There,

when I sign in to LAM, I see a php warning for each column in each table row:

**Warning**:  Undefined array key "_xxx_" in **/srv/www/lam/app/lib/lists.inc** on line **627**

Where xxx is one out of (gidnumber|givenname|lam_virtual_account_status|sn|uiduidnumber)

Best Reagrds,
Pascal

**Comment by gruberroland** [comment]
Thanks a lot for your report. This will be fixed in the final 8.7 release.
