### ISSUE TITLE
LAM Pro: add shadowlastchange when first shadow password is set in the self service

### ISSUE THREAD

**Issue by rattei** [LDAPAccountManager/lam#306]
When a user is created with shadow extension but without setting a password, no shadowlastchange is added to the dn of the new user. If this user requests a password changes through the "Forgot password" option of the self service, a new password is stored to LDAP but no shadowlastchange attribute is added. Consequently, the user cannot login on Unix systems based on the LDAP database.

Please make sure that, when a password is set in the self service, the shadowlastchange attribute always exists and is updated.

Thanks!

**Comment by gruberroland** [comment]
Thanks for your report. This will be fixed in 8.7.
