### ISSUE TITLE
UBUNTU 22 DEPENDENCIAS INCUMPLIDAS LDAP-ACCOUNT-MANAGER_8.1-1_all

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#309]
Desempaquetando ldap-account-manager (8.7-1) sobre (8.6.RC0-1) ...
dpkg: problemas de dependencias impiden la configuración de ldap-account-manager:
 ldap-account-manager depende de php-phpseclib3; sin embargo:
  El paquete `php-phpseclib3' no está instalado.
 ldap-account-manager depende de php-psr-log (<< 2.0); sin embargo:
  El paquete `php-psr-log' no está instalado.
 ldap-account-manager depende de php-monolog (<< 3.0); sin embargo:
  El paquete `php-monolog' no está instalado.
 ldap-account-manager depende de php-voku-portable-ascii (<< 3.0); sin embargo:
  El paquete `php-voku-portable-ascii' no está instalado.
 ldap-account-manager depende de libphp-phpmailer (<< 7.0); sin embargo:
  El paquete `libphp-phpmailer' no está instalado

////////////////////////////////////////////////////////////////////////////
php-voku-portable-ascii SOLO ESTA DISPONIBLE EN 
https://packages.ubuntu.com/search?keywords=php-voku-portable-ascii&searchon=names&suite=all&section=all

/////////////////////////////////////////////////////
dpkg: problemas de dependencias impiden la configuración de ldap-account-manager:
 ldap-account-manager depende de php-psr-log (<< 2.0); sin embargo:
  La versión de `php-psr-log' en el sistema es 3.0.0-1.
LA VERSION DE php-psr-log EN LOS REPOSITORIOS DE 22 ES SUPERIOR, ES NECESARIO DESCARGAR LA VERSION DE http://mirrors.kernel.org/ubuntu/pool/universe/p/php-psr-log/php-psr-log_1.1.2-1_all.deb Y MARCAR EL PAQUETE COMO HOLD

apt-mark hold php-psr-log

**Comment by gruberroland** [comment]
Please see https://github.com/LDAPAccountManager/lam/issues/308#issuecomment-2002098392

**Comment by informaticavera** [comment]
Thanks, and sorry, i should read before
