### ISSUE TITLE
DOCUMENTACION DE NUEVA FUNCIONALIDAD

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#310]
DONDE ESTA LA DOCUMENTACION DE ESTA FUNCIONALIDAD??
new cron job can deactivate inactive accounts based on lastBind overlay data.

HEMOS ATUALIZADO A LA ULTIMA VERSION PERO PARECE QUE NO HAY NINGUN TRABAJO NUEVO DE CRON???

![Captura desde 2024-03-18 07-51-58](https://github.com/LDAPAccountManager/lam/assets/32567126/ba76f04e-afce-4f55-95ce-4ff7f2e0059a)

**Comment by gruberroland** [comment]
Please see here: https://www.ldap-account-manager.org/static/doc/manual/ch03s02.html#job_lastBind_deactivate
If you need additional support please write in English that we can better help you.

**Comment by informaticavera** [comment]
Perfect, thanks. A great job.

What does "This job deactivates all users that did not perform a successful login for a given time" mean?

Does it execute the action configured in "Shadow: Delete or move expired accounts"?

**Comment by gruberroland** [comment]
The account will be deactivated using the PPolicy overlay. There is no action done regarding Shadow account extension.

**Comment by informaticavera** [comment]
OK
