### ISSUE TITLE
LAM 8.7: Unable to lock an account -> PHP Warning

### ISSUE THREAD

**Issue by Username-is-really-not-available** [LDAPAccountManager/lam#311]
When I try to lock an account, with checked options 'Shadow: Account expiration' and 'Shadow: Password expiration', the green lock gets replaced by a hourglass. Right after that a php warning is logged:

`[Mon Mar 18 17:22:55.036322 2024] [proxy_fcgi:error] [pid 13023:tid 139939578713792] [remote 2001:db8::d123:53908] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "shadowmax" in /srv/www/lam/app/lib/modules/shadowAccount.inc on line 991; PHP message: PHP Warning:  Trying to access array offset on value of type null in /srv/www/lam/app/lib/modules/shadowAccount.inc on line 991; PHP message: PHP Warning:  Undefined array key "shadowinactive" in /srv/www/lam/app/lib/modules/shadowAccount.inc on line 991; PHP message: PHP Warning:  Trying to access array offset on value of type null in /srv/www/lam/app/lib/modules/shadowAccount.inc on line 991', referer: https://lam.berlin.example.com/templates/account/edit.php?type=user&DN=cn%3DJohn+%C3Doe%2Cou%3Dpeople%2Cdc%3Dberlin%2Cdc%3Dexample%2Cdc%3Dcom`

After saving the changes and a click on the `Edit again' button a green lock is displayed in the top left corner,

**Comment by gruberroland** [comment]
Will be fixed in 8.8. As a workaround set values in "Password expiration" and "Maximum password age".
