### ISSUE TITLE
User self registration: support registration without password

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#313]
When the self-registration process is carried out by the company's personnel department, they must complete the password field and I will then give it to the user. Ideally, the password field should be generated randomly and sent to the user upon account creation.

**Comment by gruberroland** [comment]
This sounds like someone is requesting the account on behalf of the user. Would it be an option to use the regular admin interface for this? E.g. you can create a second server profile for HR that has limited functionality and allows to create users in a certain area?

If this is not an option how do you make sure that the random password is received by the user? I guess the user cannot access the mailbox without knowing the password.

**Comment by informaticavera** [comment]
Exactly, our HR department requests user registrations through self-service. The solution you propose may work, although let's see what you think:

- The password field can be a special attribute (autogenerate::password) and perhaps you can use the same functions that generate the password on the users page of the administration part.

![password1](https://github.com/LDAPAccountManager/lam/assets/32567126/af785649-b42e-4d15-891b-903b385dab40)


Sending the auto-generated password is not a problem, in our case user registration requires approval and the corporate email is not created until the process is finished and the user is created. We use users' personal email during self-registration. That is to say:

- SELF-SERVICE SEND MAIL TO PERSONAL USER MAIL

![Captura desde 2024-03-20 07-03-26](https://github.com/LDAPAccountManager/lam/assets/32567126/b7fd6500-4c76-4c86-b503-41262e8c1461)


- THE USER CONFIRMS THAT THEIR PERSONAL EMAIL ACCOUNT EXISTS and WITH @@creationLink@@
 REQUEST APPROVAL

- ADMINISTRATORS APPROVE THE ACCOUNT AND A MESSAGE IS SENT TO THE USER WITH THE REGISTRATION DATA:

First and Last Name: @@givenName@@ @@sn@@
User: @@uid@@
Email: @@mail@@

(HERE WE COULD INCLUDE THE AUTOGENERATED PASSWORD)

**Comment by gruberroland** [comment]
Thanks a lot for the extra info. Give us some days to check if and how this use-case can be supported.

**Comment by gruberroland** [comment]
Probably, the most easy solution would be to add an option in self service profile for random password generation. I put it on the list for 8.9.
