### ISSUE TITLE
Self service login not possible with 8.7.0 Pro

### ISSUE THREAD

**Issue by nblock** [LDAPAccountManager/lam#314]
The login to the self service portal does no longer work in 8.7.0 Pro. Error message: Username/password invalid.

The following is available in Apache's `error.log`:

```
[proxy_fcgi:error] [pid 3284457] [client 10.0.0.1:38330] AH01071: Got error 'PHP message: PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/ldap-account-manager-
8.7/lib/selfService.inc on line 875', referer: https://ldap.example.com/templates/selfService/selfServiceLogin.php?scope=user&name=example-self-service
```

A downgrade to 8.6.0 Pro fixed the issue.

**Comment by gruberroland** [comment]
There were two self service changes in 8.7 that require to be checked on upgrade: https://www.ldap-account-manager.org/static/doc/manual/ch02s02.html#a_versUpgrade

Can you check if this solves the issue?

**Comment by nblock** [comment]
> There were two self service changes in 8.7 that require to be checked on upgrade: https://www.ldap-account-manager.org/static/doc/manual/ch02s02.html#a_versUpgrade

Thanks for the pointer! The first step "Self service profiles that were not saved with a LAM Pro version of the past 3 years must be saved with LAM Pro 8.6 before upgrading to LAM Pro 8.7." fixed the login issue.
