### ISSUE TITLE
LAM 8.3 not autoincrement uid always 10000

### ISSUE THREAD

**Issue by Mad-Soft** [LDAPAccountManager/lam#319]
I don't know why, but when i create a user always LAM give a 10000 uid number, i have to change uid manually.

![Screenshot_20240402_134459-1](https://github.com/LDAPAccountManager/lam/assets/3355580/7f709edf-8ea2-4d2d-83fa-8ccfe80cbe85)

**Comment by gruberroland** [comment]
What did you configure in your server profile -> module settings -> Unix -> UID generator?

**Comment by Mad-Soft** [comment]
I apologize for my delay, work has not left me free time.
I attach a screenshot of how I have configured the module
![Captura de pantalla_20240424_171121](https://github.com/LDAPAccountManager/lam/assets/3355580/85ee331d-99c8-4894-81c8-db9ceeee43ea)

**Comment by gruberroland** [comment]
I was not able to reproduce this. Can you recheck with LAM 8.7?
