### ISSUE TITLE
Add ObjectClass to new and all old users

### ISSUE THREAD

**Issue by BurtGummer** [LDAPAccountManager/lam#32]
Hello,
i write a own schema:

> attributetype ( 1.3.6.1.4.1.xxxxx.1.1.1.1
>         NAME 'sapuser'
>         DESC 'SAP Benutzer'
>         EQUALITY caseIgnoreMatch
>         SUBSTR caseIgnoreSubstringsMatch
>         SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
>         SINGLE-VALUE )
> 
> attributetype ( 1.3.6.1.4.1.xxxxx.1.1.1.2
>         NAME 'saplizenz'
>         DESC 'SAP Lizenz'
>         EQUALITY caseIgnoreMatch
>         SUBSTR caseIgnoreSubstringsMatch
>         SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
>         SINGLE-VALUE )
> 
> objectclass     ( 1.3.6.1.4.1.xxxxx.2.1.1.1
>     NAME 'sap'
>         DESC 'SAP Daten'
>         SUP top
>         AUXILIARY
>         MAY (
>                 sapuser $ saplizenz )
>         )

but how can i add this new ObjectClass to new and all existing users?
Manual everything works: i add the new ObjectClass to a user and with the LAM Modul "Custom Fields" i can write in this fields, but ONLY on users there have the new ObjectClass "sap".

Any ideas?

**Comment by gruberroland** [comment]
Hi Burt,

you can use the Multi edit tool to roll-out your new object class:

https://www.ldap-account-manager.org/static/doc/manual/ch05s03.html


For custom fields you can open Tools -> Profile editor and edit the profile "default". Here select "Automatically add this extension". This will add the object class to each new user.

Best regards

Roland

**Comment by BurtGummer** [comment]
Hello Roland,
thank you for your answer. In the profile editor, default profile, i have only this screen:

![image](https://cloud.githubusercontent.com/assets/1249295/26616958/ade23c8c-45d2-11e7-9928-66a665380fa6.png)

![image](https://cloud.githubusercontent.com/assets/1249295/26616965/b5b31e54-45d2-11e7-954d-822c795a7538.png)

There is no "Automatically add this extension"? I have LAM Pro 4.5. Any idea?

**Comment by BurtGummer** [comment]
I have install our latest Version LAM Pro 5.7, its the same. And the Multi Edit Tool, i try at a testuser "GustavGans". Our new objectClass is "sap":

![image](https://cloud.githubusercontent.com/assets/1249295/26618303/30a0067a-45da-11e7-8150-2e3093fb258a.png)

![image](https://cloud.githubusercontent.com/assets/1249295/26618106/2d61786e-45d9-11e7-82c5-35e5224cb59d.png)

![image](https://cloud.githubusercontent.com/assets/1249295/26618178/af4502e2-45d9-11e7-8f01-61581e74d27f.png)

![image](https://cloud.githubusercontent.com/assets/1249295/26618190/bee18e46-45d9-11e7-9455-617c8169ff85.png)

**Comment by gruberroland** [comment]
For multi edit the attribute name must be "objectclass" and value "sap".

If the checkbox in profile editor is missing then you might not have set the object class in server profile. It is above the "Add new field" button.

https://www.ldap-account-manager.org/static/doc/manual/images/customFields16.png

**Comment by BurtGummer** [comment]
Great, that was is, thank you very very much Roland!
