### ISSUE TITLE
php-psr-log upgrade cause delete ldap-account-manager

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#331]
root@ayuntamiento:~# apt-cache show php-psr-log
Package: php-psr-log
Architecture: all
Version: 3.0.0-1
Priority: optional
Section: universe/php
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian PHP PEAR Maintainers <pkg-php-pear@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 31
Depends: php-common
Filename: pool/universe/p/php-psr-log/php-psr-log_3.0.0-1_all.deb
Size: 6862
MD5sum: ab24b4be5239d4c4ae7b1f0f2c20a141
SHA1: 25aea5c53fca5a308b8d12a706089d7edca2baaf
SHA256: e834ddbc660b355924599d66fd8dcf16a8517a76bb2f20e95af9f8c2c7be1fbc
SHA512: 5c9094d93e069fc4f00dabc90b9158d04f6a8d278c23bd95488bea5a10fd8b77b89f02a8b373e5b1d6cad30f9a0d73c445b7861afe2967cbe1db522bcf8aab36
Homepage: https://www.php-fig.org/psr/psr-3/
Description-en: common interface for logging libraries
 The main goal is to allow libraries to receive a Psr\Log\LoggerInterface object
 and write logs to it in a simple and universal way. Frameworks and CMSs that
 have custom needs MAY extend the interface for their own purpose, but SHOULD
 remain compatible with this document. This ensures that the third-party
 libraries an application uses can write to the centralized application logs.
 .
 The LoggerInterface exposes eight methods to write logs to the eight RFC 5424
 levels (debug, info, notice, warning, error, critical, alert, emergency).
 .
 A ninth method, log, accepts a log level as first argument. Calling this method
 with one of the log level constants MUST have the same result as calling the
 level-specific method. Calling this method with a level not defined by this
 specification MUST throw a Psr\Log\InvalidArgumentException if the
 implementation does not know about the level. Users SHOULD NOT use a custom
 level without knowing for sure the current implementation supports it.
 .
 Note that this is not a logger of its own. It is merely an interface that
 describes a logger. See the specification for more details.
Description-md5: 61027d449ef97a57be423befc11f2312

Package: php-psr-log
Status: hold ok installed
Priority: optional
Section: php
Installed-Size: 45
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 1.1.2-1
Depends: php-common
Description-en: common interface for logging libraries
 The main goal is to allow libraries to receive a Psr\Log\LoggerInterface object
 and write logs to it in a simple and universal way. Frameworks and CMSs that
 have custom needs MAY extend the interface for their own purpose, but SHOULD
 remain compatible with this document. This ensures that the third-party
 libraries an application uses can write to the centralized application logs.
 .
 The LoggerInterface exposes eight methods to write logs to the eight RFC 5424
 levels (debug, info, notice, warning, error, critical, alert, emergency).
 .
 A ninth method, log, accepts a log level as first argument. Calling this method
 with one of the log level constants MUST have the same result as calling the
 level-specific method. Calling this method with a level not defined by this
 specification MUST throw a Psr\Log\InvalidArgumentException if the
 implementation does not know about the level. Users SHOULD NOT use a custom
 level without knowing for sure the current implementation supports it.
 .
 Note that this is not a logger of its own. It is merely an interface that
 describes a logger. See the specification for more details.
Description-md5: 61027d449ef97a57be423befc11f2312
Original-Maintainer: Debian PHP PEAR Maintainers <pkg-php-pear@lists.alioth.debian.org>
Homepage: https://www.php-fig.org/psr/psr-3/

root@ayuntamiento:~# dpkg --list php-psr-log
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre         Versión      Arquitectura Descripción
+++-==============-============-============-======================================
hi  php-psr-log    1.1.2-1      all          common interface for logging libraries

**Comment by gruberroland** [comment]
Please see here for a solution: https://github.com/LDAPAccountManager/lam/issues/308#issuecomment-2002098392
Version 8.9 will support more PSR LOG versions and work on Ubuntu again.
