### ISSUE TITLE
CustomFields: LDAP search select List: wrong value for empy option

### ISSUE THREAD

**Issue by m-bach** [LDAPAccountManager/lam#334]
While working with a LDAP search select list field I hit a case where the empty option has a (seemingly random) value of another option. Which led to users unknowingly setting an arbitrary value for that field instead of not setting it all.

I debugged the issue a bit and found out, that this happens when the LDAP filter returns some entries that do not have the attribute.

**Comment by gruberroland** [comment]
Thanks a lot for your report. This will be fixed in the June release.
As a workaround you can add the display/value attributes to the LDAP filter to make sure they are available.
