### ISSUE TITLE
Needed star or required icon in user registration of first name and email , in 6.8 version this feature is available

### ISSUE THREAD

**Issue by BhaskarraoP** [LDAPAccountManager/lam#338]
Hello Team,
I am upgrading my lam to 6.8 to 8.7, rightnow i have noticed the following thing i need the required icon or start icon in the user registration form in the fields of first name and email. Here is the reference can you please give me the details like were can i get this feature enabled in code.
<img width="503" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/52959161/a490dce8-6790-4f77-ab07-f2a772062460">
Any help would be helpfull.
Thanks

**Comment by gruberroland** [comment]
For user self registration you can simply use "required" instead of "optional" for your field definition.
See: https://www.ldap-account-manager.org/static/doc/manual/ch07s03.html#idm5928

The screenshot shows the admin interface. Here, there is no configuration option to make the field required. You could use a custom JavaScript for this: https://www.ldap-account-manager.org/static/doc/manual/apf.html

**Comment by BhaskarraoP** [comment]
Hello @gruberroland 
Thanks for the details i am gone with second approach as we are not using the first you mentioned. So can you mention the the files and line no of the code were this first and email id is present so that i can add the changes there. As i want to make it as required field. In earlier lam 6.8 this fields are mandatory.

Thanks..

**Comment by gruberroland** [comment]
Please see /usr/share/ldap-account-manager/lib/modules/inetOrgPerson.inc and function display_html_attributes() if you would like to patch the code.

**Comment by BhaskarraoP** [comment]
Hello @gruberroland 
Thanks for the suggestion it worked. I am not good at php it was good experience. But i encountered another issue as this fields first,email are required, i can create the user without adding details. Is there any clue were to look in the code base or function.
Thanks

Also one suggestion for lam UI. In the user creation form the fields of personal and unix section, if it could be placed in left it would be better.
<img width="842" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/52959161/2baa3164-0a87-4ce4-a474-cd77b57c2807">
<img width="901" alt="image" src="https://github.com/LDAPAccountManager/lam/assets/52959161/36a66338-3496-4041-8c3e-28f8d8737208">

Thanks once again

**Comment by gruberroland** [comment]
Not sure if I got you right, did you mean that saving is possible even if star icon is displayed? Please check process_attributes() in this case. This includes all the checks for the input data.
For the layout I will create a separate issue. As the fields are very different per module this is not that easy to be perfectly aligned.

**Comment by BhaskarraoP** [comment]
Hello @gruberroland 
Thanks for the support. One final question after that i will close the request. Is there any possibility to make the UID Number field readonly?
Thanks

**Comment by gruberroland** [comment]
There is no option to make uidNumber read-only. In this case, you would need to adapt posixAccount.inc (display_html_attributes()).
