### ISSUE TITLE
Windows user: add personalTitle attribute

### ISSUE THREAD

**Issue by paschulke** [LDAPAccountManager/lam#343]
Hello,

is it possible to the default `personalTitle` ldap-attribute to the modifiable properties in the Active Directory Module (`windowsUser`)?
It is by default available in a Active Directory environment and used for the either the academic title (Prof., PhD., etc.) or the gender (Mr., Ms., etc.).

**Comment by gruberroland** [comment]
Thanks for the suggestion, I added it for 8.9.

As a workaround, you can manage the attribute via custom fields in LAM Pro: https://www.ldap-account-manager.org/static/doc/manual/ch04s26.html
