### ISSUE TITLE
Windows user: add roomNumber attribute

### ISSUE THREAD

**Issue by paschulke** [LDAPAccountManager/lam#344]
Hello,

is it possible to add the default `roomNumber` ldap-attribute to the modifiable properties in the Active Directory Module (`windowsUser`)?
While `physicalDeliveryOfficeName` is already available, it does not by default allow multiple inputs unlike `roomNumber` and therefore covers a different use case (`roomNumber` default value is an array in an Active Directory).

**Comment by gruberroland** [comment]
Planned for 8.9 :)

**Comment by paschulke** [comment]
Great! Thank you so much!
