### ISSUE TITLE
Getting following warnings and error in bulk upload of users.

### ISSUE THREAD

**Issue by BhaskarraoP** [LDAPAccountManager/lam#349]
Hello @gruberroland,

I hope this message finds you well.

I have encountered a potential bug in the bulk upload or file upload feature of LAM. Specifically, when I download the lam.csv file and then upload it, some values occasionally go missing. This issue is reflected in the logs and error messages I receive consistently.

Here are the relevant log entries:

[Tue Jul 09 12:57:46.149353 2024] [core:notice] [pid 1] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Tue Jul 09 13:02:53.233395 2024] [php:warn] [pid 215] [client IP:53234] PHP Warning: Undefined array key "posixAccount_createHomeDir" in /usr/share/ldap-account-manager/lib/modules/posixAccount.inc on line 2784,
[Tue Jul 09 13:07:06.538910 2024] [php:warn] [pid 212] [client IP:53222] PHP Warning: Undefined array key "posixAccount_createHomeDir" in /usr/share/ldap-account-manager/lib/modules/posixAccount.inc on line 2784, 
[Tue Jul 09 13:07:25.314505 2024] [php:warn] [pid 216] [client IP:42920] PHP Warning: Undefined array key "typeId" in /usr/share/ldap-account-manager/templates/upload/massBuildAccounts.php on line 108, referer: 
[Tue Jul 09 13:07:25.314612 2024] [php:error] [pid 216] [client IP:42920] PHP Fatal error: Uncaught Error: Call to a member function isHidden() on null in /usr/share/ldap-account-manager/templates/upload/massBuildAccounts.php:113\nStack trace:\n#0 {main}\n thrown in /usr/share/ldap-account-manager/templates/upload/massBuildAccounts.php on line 113, 
[Tue Jul 09 13:07:33.747177 2024] [php:warn] [pid 210] [client IP:41270] PHP Warning: Undefined array key "posixAccount_createHomeDir" in /usr/share/ldap-account-manager/lib/modules/posixAccount.inc on line 2954,
I would greatly appreciate it if you could review these logs and help identify the underlying issue. Thank you for your time and assistance.

Best regards,
Bhaskar

**Comment by gruberroland** [comment]
Hi,
please provide the following:
* screenshot of active user modules in server profile
* sample CSV file with one entry that results in the error above

If you are not yet on LAM 8.8 please upgrade so that we have the right line numbers in the errors.

**Comment by BhaskarraoP** [comment]
Hello @gruberroland 
I am already using LAM 8.7. 
Please look into the lam.csv file i uploaded. The user got uploaded and i can see the details of user no issues but the unwanted logs and fatal error logs being generated. For users bulk upload it generated 7 lines of logs.
Also the current active user is admin. We also have not changed anything in server profiles. We just upgraded the dockerfile and some code changes for the user form which i earlier created ticket with you.
[lam.csv](https://github.com/user-attachments/files/16202876/lam.csv)

If anything missed in the files please tell me also documents would be more readable will be usable.

**Comment by gruberroland** [comment]
Thanks a lot for the file, this will be fixed in the next release 8.9.

**Comment by BhaskarraoP** [comment]
Hello @gruberroland 
Now it seems to be stable and upload works normally but still this warning appears
[Mon Jul 15 15:50:59.129624 2024] [php:warn] [pid 215:tid 215] [client IP:36818] PHP Warning: Undefined array key "users" in /usr/share/ldap-account-manager/lib/modules/posixAccount.inc on line 2984, referer: URL

Thanks. for your continuous support

**Comment by gruberroland** [comment]
Please check posixAccount_group. Seems like you have the example value "users" there. You need to replace it with a Unix group name.
