### ISSUE TITLE
Issue with files 

### ISSUE THREAD

**Issue by umerjillani** [LDAPAccountManager/lam#357]
I hope you're doing well. I'm currently working on a project using your Docker image `ekellercu/network-testing:v0.1` on Containerlab, but I'm encountering an issue when attempting to pull the image. The process gets stuck at:

```
Containerlab v0.44.0 started
INFO[0000] Parsing & checking topology file: 4node-part1.clab.yml
INFO[0000] Pulling docker.io/ekellercu/network-testing:v0.1 Docker image
```

Here are some troubleshooting steps I've tried so far:
- Manually pulling the image using `docker pull ekellercu/network-testing:v0.1`
- Verified internet connection within my environment
- Checked Docker logs for any errors
- Verified system disk space
- Restarted the Docker service

Despite these efforts, the image pull remains stuck. I'd appreciate any guidance or suggestions you might have to resolve this issue.

In addition, I’m using a Vagrant image on VirtualBox running Ubuntu, and I noticed that the folders (demo1, demo2, demo3) don't mount automatically. I have to manually upload them to the Ubuntu environment, which is an additional step that might be causing issues with the environment setup.

Thanks in advance for your help!

Umer Jillani

**Comment by umerjillani** [comment]
update 
 I am receiving a score of 0/100. Here is the output from the script:

INFO[0000] Containerlab v0.44.0 started
INFO[0000] Parsing & checking topology file: 4node-part1.clab.yml
INFO[0000] Creating docker network: Name="clab", IPv4Subnet="172.20.20.0/24", IPv6Subnet="2001:172:20:20::/64", MTU="1500"
INFO[0002] Creating lab directory: /home/vagrant/lab1/part1/clab-lab1-part1
WARN[0002] SSH_AUTH_SOCK not set, skipping pubkey fetching
INFO[0002] Creating container: "switch"
INFO[0007] Creating container: "host1"
INFO[0010] Creating link: host1:eth1 <--> switch:eth1
INFO[0010] Creating container: "host2"
INFO[0013] Creating link: host2:eth1 <--> switch:eth2
INFO[0013] Creating container: "host3"
INFO[0016] Creating link: host3:eth1 <--> switch:eth3
INFO[0016] Creating container: "host4"
INFO[0019] Creating link: host4:eth1 <--> switch:eth4
INFO[0020] Adding containerlab host entries to /etc/hosts file
INFO[0020] 🎉 New containerlab version 0.57.0 is available! Release notes: [https:](https://containerlab.dev/rn/0.57/)[/](https://containerlab.dev/rn/0.57/)[/](https://containerlab.dev/rn/0.57/)[containerlab.dev](https://containerlab.dev/rn/0.57/)[/](https://containerlab.dev/rn/0.57/)[rn](https://containerlab.dev/rn/0.57/)[/](https://containerlab.dev/rn/0.57/)[0.57](https://containerlab.dev/rn/0.57/)[/](https://containerlab.dev/rn/0.57/)
Run 'containerlab version upgrade' to upgrade or go check other installation options at [https:](https://containerlab.dev/install/)[/](https://containerlab.dev/install/)[/](https://containerlab.dev/install/)[containerlab.dev](https://containerlab.dev/install/)[/](https://containerlab.dev/install/)[install](https://containerlab.dev/install/)[/](https://containerlab.dev/install/)
+---+------------------------+--------------+--------------------------------+-------+---------+----------------+----------------------+
| # |          Name          | Container ID |             Image              | Kind  |  State  |  IPv4 Address  |     IPv6 Address     |
+---+------------------------+--------------+--------------------------------+-------+---------+----------------+----------------------+
| 1 | clab-lab1-part1-host1  | cb9b22fe90ee | ekellercu/network-testing:v0.1 | linux | running | 172.20.20.3/24 | 2001:172:20:20::3/64 |
| 2 | clab-lab1-part1-host2  | c199a9ad3c66 | ekellercu/network-testing:v0.1 | linux | running | 172.20.20.4/24 | 2001:172:20:20::4/64 |
| 3 | clab-lab1-part1-host3  | b36f22e1caae | ekellercu/network-testing:v0.1 | linux | running | 172.20.20.5/24 | 2001:172:20:20::5/64 |
| 4 | clab-lab1-part1-host4  | dcd8a235c967 | ekellercu/network-testing:v0.1 | linux | running | 172.20.20.6/24 | 2001:172:20:20::6/64 |
| 5 | clab-lab1-part1-switch | 03b8c156e6f0 | ekellercu/network-testing:v0.1 | linux | running | 172.20.20.2/24 | 2001:172:20:20::2/64 |
+---+------------------------+--------------+--------------------------------+-------+---------+----------------+----------------------+
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
Running as user "root" and group "root". This could be dangerous.
Running as user "root" and group "root". This could be dangerous.
Running as user "root" and group "root". This could be dangerous.
Running as user "root" and group "root". This could be dangerous.
Capturing on 'eth1'
Capturing on 'eth1'
Capturing on 'eth1'
 ** (tshark:41) 16:18:38.592554 [Main MESSAGE] -- Capture started.
 ** (tshark:41) 16:18:38.607184 [Main MESSAGE] -- File: "/lab-folder/h4.pcap"
 ** (tshark:39) 16:18:38.664948 [Main MESSAGE] -- Capture started.
 ** (tshark:39) 16:18:38.682420 [Main MESSAGE] -- File: "/lab-folder/h3.pcap"
 ** (tshark:40) 16:18:38.896694 [Main MESSAGE] -- Capture started.
 ** (tshark:40) 16:18:38.905606 [Main MESSAGE] -- File: "/lab-folder/h2.pcap"
Capturing on 'eth1'
 ** (tshark:40) 16:18:40.924220 [Main MESSAGE] -- Capture started.
 ** (tshark:40) 16:18:40.951516 [Main MESSAGE] -- File: "/lab-folder/h1.pcap"
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
context canceled
context canceled
context canceled
context canceled
INFO[0002] Parsing & checking topology file: 4node-part1.clab.yml
INFO[0002] Destroying lab: lab1-part1
INFO[0010] Removed container: clab-lab1-part1-host1
INFO[0010] Removed container: clab-lab1-part1-host2
INFO[0011] Removed container: clab-lab1-part1-host3
INFO[0012] Removed container: clab-lab1-part1-host4
INFO[0012] Removed container: clab-lab1-part1-switch
INFO[0012] Removing containerlab host entries from /etc/hosts file
Issues Noted:

Permission Errors:

Errors such as permission denied for /lab-folder/onepkt.py and ./do-lab.sh suggest that there might be permission issues with the scripts and files being executed within the containers.
File and Directory Checks:

The script requires the existence of certain directories and files. Ensure that all necessary files, including ./provided/onepkt.py and /lab-folder/ directories, are correctly set up and have the proper permissions.
Please let me know if there are specific issues or additional steps I can take to address the problems and improve the submission.

Thank you for your assistance.

**Comment by gruberroland** [comment]
The mentioned Docker image is not provided by us. Please see here for the official image: https://github.com/LDAPAccountManager/docker
