### ISSUE TITLE
Number of Users wrong

### ISSUE THREAD

**Issue by BurtGummer** [LDAPAccountManager/lam#36]
Hello,

the "number of users" is wrong:

![image](https://user-images.githubusercontent.com/1249295/29407807-0043c198-8346-11e7-9e9a-7c7ec16c263a.png)

but in the tree view:

![image](https://user-images.githubusercontent.com/1249295/29407760-d87f0c1c-8345-11e7-8979-3c506e57332a.png)

Any ideas?

**Comment by gruberroland** [comment]
The number shown in the list is the number of found supported users. This can be different to the number of entries. Reasons are:
* entries are not a user but some other entry
* users have different set of object classes that is not supported by currently selected modules
* you set an additional LDAP filter in server profile that removes some entries from the list

The best would be to check some entries how they differ from the rest. Especially regarding object classes.

**Comment by BurtGummer** [comment]
Thank you very much, Roland! I have found the problem:

not displayed users:

![image](https://user-images.githubusercontent.com/1249295/29456468-063553e8-8416-11e7-9ff4-de7fa6829ea3.png)

displayed:

![image](https://user-images.githubusercontent.com/1249295/29456487-189928de-8416-11e7-9b92-3403875f7d8e.png)
