### ISSUE TITLE
Empty login screen, configuration not parsed?

### ISSUE THREAD

**Issue by jasminl303** [LDAPAccountManager/lam#37]
I'm in the process of migrating from LAM 5.x to LAM 6.0 on PHP 7/ Apache / CentOS 7. The previously working .conf is not taken into account or not parsed correctly in LAM 6.x. I can select the profile but the username and ldap url remain blank at the login screen. When trying to log in, I get an LDAP login error. The log files show that a blank user tried to log in...  I tried increasing the debug level but nothing new shows up.

I tried 6.0.1 thinking that this bug was solved as the issue fixed in changelog looked a lot like my current problem... sadly the result is the same as 6.0.

I event uninstalled and reinstalled the package to revert the entire configuration and doing them again... still the same bug happens. I'm running out of ideas... is there something else I can do to solve this issue?

**Comment by gruberroland** [comment]
Hi,

sorry for that. Can you change the passwords and attach the config file? You can find it here:

  /var/lib/ldap-account-manager/config/

Do I understand correctly that if you create a new profile it also does not work?

**Comment by jasminl303** [comment]
Yes. It's exactly the same config file as our production LAM 5.x.  They are both connecting to the same OpenLDAP directory with samba and posix accounts. 

```
serverURL: ldap://localhost:389

admins: cn=Admin,dc=ticfga,dc=ca
password: {SSHA}BIGSSHASTRING
treesuffix: dc=ticfga,dc=ca
defaultLanguage: en_GB.utf8:UTF-8:English (Great Britain)
scriptPath:
scriptServer:
scriptRights: 750
cachetimeout: 5
searchLimit: 0
modules: posixAccount_minUID: 10000
modules: posixAccount_maxUID: 30000
modules: posixAccount_minMachine: 50000
modules: posixAccount_maxMachine: 60000
modules: posixGroup_minGID: 10000
modules: posixGroup_maxGID: 20000
modules: posixGroup_pwdHash: SSHA
modules: posixAccount_pwdHash: SSHA
activeTypes: user,group,host,smbDomain
types: suffix_user: ou=users,dc=ticfga,dc=ca
types: modules_user: inetOrgPerson,posixAccount,shadowAccount,sambaSamAccount
types: suffix_group: ou=group,dc=ticfga,dc=ca
types: modules_group: posixGroup,sambaGroupMapping
types: suffix_host: ou=machines,dc=ticfga,dc=ca
types: modules_host: account,posixAccount,sambaSamAccount
types: suffix_smbDomain: dc=ticfga,dc=ca
types: attr_smbDomain: sambaDomainName:Domain name;sambaSID:Domain SID
types: modules_smbDomain: sambaDomain
lamProMailSubject: Your password was reset
lamProMailText: Dear @@givenName@@ @@sn@@,+::++::+your password was reset to: @@newPassword@@+::++::++::+Best regards+::++::+deskside support+::+
```

**Comment by gruberroland** [comment]
Please set "ServerURL" instead of "serverURL" and "Admins" instead of "admins". Then it should work again. Also it should be "Passwd" instead of "password".

**Comment by jasminl303** [comment]
It works!
Thanks for the support!
