### ISSUE TITLE
Incorrect Date adn time format

### ISSUE THREAD

**Issue by frantz28** [LDAPAccountManager/lam#370]
Hello I have a problem configuring the expiration date of my ldap accounts.
it seems like the dates are not correctly formatted an i don't knwo what to do to solve this problem

![Capture d’écran 2024-10-08 152416](https://github.com/user-attachments/assets/c67da13e-32cc-4d45-a62e-b323054acaeb)

![Capture d'écran 2024-10-08 151132](https://github.com/user-attachments/assets/2680da8c-7feb-4c86-8a64-bc5e083b8f23)

**Comment by gruberroland** [comment]
This looks like you built your own custom module. Do you need a code example to format the LDAP timestamp?

**Comment by frantz28** [comment]
Hello, yes please, and i want to know in which file i can insert it. Because my colleague who did this work is no longuer in the company and I dont really know how to edit it

**Comment by frantz28** [comment]
heelo, thank you for your response, i want the date to be formatted this way YYYYMMDDhhmmssZ so that it can match my ldap schema
![image](https://github.com/user-attachments/assets/d99c63e1-837f-46aa-a746-a76121321a9d)

instad, I have this format and it cannot be parsed 
![image](https://github.com/user-attachments/assets/79fa0250-9b88-4e29-8b53-db81e47a0f3e)

This is how was formatted the date on the older versions of LAM
![image](https://github.com/user-attachments/assets/3607e1b3-5fcf-4aac-a73f-6a7f689b7b7a)

**Comment by gruberroland** [comment]
The calendar format in the module should be 'YmdHi\\Z'.

We offer to maintain custom modules. If you are interested please contact us for a quote: lampro@ldap-account-manager.org
