### ISSUE TITLE
Unable to specify custom $HOME parent directory

### ISSUE THREAD

**Issue by patvdv-smo** [LDAPAccountManager/lam#371]
Hi,

We are using LAM Pro 8.7 and I cannot find a way to specify a different default `$HOME` path for all new users. I know it was possible in the very old LAM version we used before (5.4) via the Profile Editor > Users > Unix

Am I missing something?

**Comment by gruberroland** [comment]
What do you mean with "different default $HOME"? Is this the home directory in profile editor?
![grafik](https://github.com/user-attachments/assets/7ab9ecca-425f-4292-b1d2-cf00ff812c34)

**Comment by patvdv-smo** [comment]
Hi Roland,

I am not sure where to look, the documentation is incomplete on this part. We have following modules enabled in the server profile:
![lam_01](https://github.com/user-attachments/assets/b977dab0-d378-4d1a-ac27-3a88da4f98ab)

And the settings for the Unix module do not show any HOME directory configuration:
![lam_02](https://github.com/user-attachments/assets/222ce15c-d25f-45e5-b4b5-7e4e74715076)

In LAM 5.4 we had this:
![lam_03](https://github.com/user-attachments/assets/6c3938aa-ea0a-4060-8589-19f757509c37)

Where can I find this into LAM 8.7? We do not use the `/home/$user` convention at user creation.

**Comment by gruberroland** [comment]
Your screenshot from 8.8 shows the server profile but you need to go to profile editor. It is in the tools menu after you login to LAM (top right).

**Comment by patvdv-smo** [comment]
Indeed, found it! Thank you.
