### ISSUE TITLE
Unable to add or see the UbuntuC font

### ISSUE THREAD

**Issue by BhaskarraoP** [LDAPAccountManager/lam#376]
Hello @gruberroland 

In lam 6.8 we have font of UbuntuC using to display in lam when i upgarded to lam 8.7, I can't see the UbuntuC font on UI.
I have checked using inspect code. How can i add this again in 8.7 and above. what would be the current path for webfonts now.
In 6.8 inside teh dockerfile i copied from my local to `/usr/share/ldap-account-manager/style/webfonts` .

Thanks

**Comment by gruberroland** [comment]
I guess you had some custom CSS in 6.8. Here is how you can add additional CSS to LAM:

https://www.ldap-account-manager.org/static/doc/manual/apf.html
