### ISSUE TITLE
PASSWORD GENERATION

### ISSUE THREAD

**Issue by informaticavera** [LDAPAccountManager/lam#378]
Use the password policy set in general settings when randomly generating passwords for accounts.

Now a password is generated 
EO6Q.IwiPoN4DW

And this is my policy:

Minimum password length. 8
Minimum characters with lower case. 1
Minimum characters with capital letters. 1
Minimum number of numerical characters. 1
Minimal characters with symbols. 1
Minimum character classes. 4
Number of rules that must match. all

Why doesn't it respect the length of my policy in the random establishment?

**Comment by gruberroland** [comment]
Actually, the password fulfills your policy. LAM generates random 
passwords with a minimum length of 14 for security reasons (even if your 
policy has minimum length of only 8). If the policy has e.g. a minimum 
length of 20 then random passwords will also be 20 characters. But it 
will not go lower than 14.
I hope that this is fine for you.
