### ISSUE TITLE
Incorrect error message "Your password does not meet the password strength qualifications. Please retry with another one."

### ISSUE THREAD

**Issue by WilliamDEdwards** [LDAPAccountManager/lam#381]
LAM says:

```
Was unable to modify attributes of DN: cn=williamedwards1730111969258,CN=Users,DC=ldaptest,DC=nl.

LDAP error, server says: Server is unwilling to perform - Your password does not meet the password strength qualifications. Please retry with another one.
```

... but the LDAP server actually says:

"Password modification over LDAP must be over an encrypted connection"

Taking a quick look at the LAM source code, it seems to do some loosely-matched parsing of the response: https://github.com/LDAPAccountManager/lam/blob/14fc027e4dc5c55fea976831c4ad9907b9a6989f/lam/lib/account.inc#L1723

This probably needs some finetuning.

**Comment by gruberroland** [comment]
Unfortunately, AD does not provide any kind of meaningful errors or documentation. Therefore, LAM can only do a best guess. :(
E.g. 5003 is also sent when the password is too short.
