### ISSUE TITLE
Ambigious tooltip on Profile Editor for Users

### ISSUE THREAD

**Issue by mckinnon** [LDAPAccountManager/lam#394]
**Context**
In the _Profile Editor_ for Users (`/lam/templates/profedit/profilepage.php?type=user&edit=${name}`), the tooltips for "Minimum password age" and "Maximum password age" say:

> Number of days a user has to wait until he is allowed to change his password again. If set value must be >0. Can be left empty.

and

> Number of days after a user has to change his password again. If set value must be >0. Can be left empty.

**Bug:**
Either "Minimum password age" or "Maximum password age" may be left empty or set to 0. If "Maximum password age" is >0, "Minimum password age" cannot be set to empty without triggering an error:

> Maximum password age
> Password maximum age must be bigger than password minimum age.

**Comment by gruberroland** [comment]
Thanks a lot for your report. This will be fixed in 9.1.
Happy new year!
