### ISSUE TITLE
Self-Service login screen is missing German translation for "Forgot password?"

### ISSUE THREAD

**Issue by konsumate** [LDAPAccountManager/lam#4]
Switched language to German, but the "forgotten password?" link is still in english.

![lam_pw](https://cloud.githubusercontent.com/assets/736666/18465435/2070bd7c-7997-11e6-8eaf-df37814095f1.png)

**Comment by gruberroland** [comment]
Hi,

maybe you set a label for the link in you self service profile? The link is only translated if you do not overwrite the label. The setting is called "Linktext".

**Comment by konsumate** [comment]
The "Link Text" label field is empty.
All configuration fields which set languages are set to German.

I'm using 5.5-1 (pro)

**Comment by gruberroland** [comment]
Cannot reproduce. Please try to restart Apache. Maybe a caching issue.
If it does not help please provide a screenshot of your self service profile (language setting on first tab + self reset settings).

**Comment by konsumate** [comment]
Restarting, clearing browser cache did not fix the issue. I've used the workaround by filling in the Link Text field instead.

**Comment by konsumate** [comment]
Maybe this bit of information might be useful as well:

The URL for the end-user self-service login includes the language settings:

`${host}/lam/templates/selfService/selfServiceSP.php?scope=user&name=default&page=passwordSelfReset&language=de_DE.utf8`

But the page is shown still in English - the browser agents default language is also set to de_DE. Any ideas?

**Comment by konsumate** [comment]
Fixed, by adding de_DE.utf8 locale as documented in the configuration steps.
