### ISSUE TITLE
got Undefined offset: 64

### ISSUE THREAD

**Issue by lezab** [LDAPAccountManager/lam#42]
https://github.com/LDAPAccountManager/lam/blob/7146be7ecf4f9474927e4cb7b980df7a3bffab38/lam/lib/createntlm.inc#L296

think should be replaced by:
` for ($i = 0; $i < 64; $i++) {`

**Comment by gruberroland** [comment]
True, thanks a lot for your report. Fix will be part of 6.2.
Btw., if you have no more Windows 98 in your network LM hashes can also be disabled in your server profile (module settings).
