### ISSUE TITLE
Null config object causes error on fresh install

### ISSUE THREAD

**Issue by callumstrubi** [LDAPAccountManager/lam#44]
Fresh install on PHP 7.1 CentOS 7.4

See following error:

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to LAM\\LOGIN\\display_LoginPage() must be an instance of LAMConfig, null given, called in /var/www/vhosts/ldap/templates/login.php on line 609 and defined in /var/www/vhosts/ldap/templates/login.php:178\nStack trace:\n#0 /var/www/vhosts/ldap/templates/login.php(609): LAM\\LOGIN\\display_LoginPage(NULL, Object(LAMCfgMain), NULL, 'No default prof...')\n#1 {main}\n  thrown in /var/www/vhosts/ldap/templates/login.php on line 178

**Comment by callumstrubi** [comment]
PHP 7.1 null type hinting can fix this, but the chances of backwards compatibility are low.

To get my install to run, I simply added a ? before LAMConfig:
`function display_LoginPage(?LAMConfig $config_object, LAMCfgMain $cfgMain, $licenseValidator, $error_message) {`

**Comment by gruberroland** [comment]
Thanks a lot for your finding. I fixed the login page.Ccan you try with the changes from the referenced commit?

**Comment by callumstrubi** [comment]
I got the page to run using my hardcoded ? change, so I've now got a fully configured instance unfortunately. Though looking at the code changes I would be comfortable to say you've nailed it.

**Comment by gruberroland** [comment]
Ok, closing then. :)
Thanks again for your report.
