### ISSUE TITLE
Upgrade from 6.1.0 to 6.2.1 results in Fatal PHP error

### ISSUE THREAD

**Issue by rashkinadze** [LDAPAccountManager/lam#46]
OS: Centos 7.4
httpd-2.4.6-67.el7.centos.6.x86_64
php-5.4.16-43.el7_4.x86_64

# tail default_error.log
[Wed Feb 28 17:17:49.207451 2018] [:error] [pid 59255] [client 10.73.9.151:49668] PHP Fatal error:  Can't use method return value in write context in /usr/share/ldap-account-manager/templates/login.php on line 504, referer: http://xxxx/lam/

**Comment by gruberroland** [comment]
Hi,

you need to upgrade your PHP version to at least PHP 5.6.

**Comment by rashkinadze** [comment]
Thanks! That worked.
