### ISSUE TITLE
Tree View crashes: __autoload is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by jacksgt** [LDAPAccountManager/lam#47]
Hi there,

I'm running LDAP Account Manager 6.3 with Nginx and PHP-FPM 7.2

LAM itself works fine, but clicking on 'Tree View' results in a brief flash of the following error message, followed by an immediate logout:
```
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /var/www/ldap-account-manager/templates/3rdParty/pla/lib/functions.php on line 54

Warning: session_save_path(): Cannot change save path when headers already sent in /var/www/ldap-account-manager/lib/security.inc on line 67

Warning: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent in /var/www/ldap-account-manager/lib/security.inc on line 50

Warning: session_start(): Cannot start session when headers already sent in /var/www/ldap-account-manager/lib/security.inc on line 51

Your session expired, click here to go back to the login page.
```

As suggested in the PHP doc, `spl_autoload_register()` can be used:
https://secure.php.net/manual/en/function.autoload.php

```

**Comment by gruberroland** [comment]
LAM is not yet PHP 7.2 compatible. Please use PHP 7.1 in the meantime.
See also https://sourceforge.net/p/lam/bugs/195/

LAM 6.4 or 6.5 will support PHP 7.2.

**Comment by gruberroland** [comment]
Will be supported in 6.4

**Comment by jacksgt** [comment]
Nice!
