### ISSUE TITLE
Failed to find structural class for X

### ISSUE THREAD

**Issue by msh100** [LDAPAccountManager/lam#5]
Hello, I have a blank AWS Simple AD setup, I have installed LAM and am able to login (after which I pressed the create button for some missing stuff in the directory).

When I try and create a user I get the following:

> Was unable to create DN: cn=test,OU=group,DC=xxx,DC=yyy,DC=zzz.
LDAP error, server says: Server is unwilling to perform - Failed to find a structural class for CN=test,OU=group,DC=xxx,DC=yyy,DC=zzz

Any ideas? I am not that knowledgable on directory services. Thanks!

**Comment by gruberroland** [comment]
Which modules did you activate? See here for the standard Windows user+group module:

https://www.ldap-account-manager.org/static/doc/manual/ch04s02.html#idp71982912
https://www.ldap-account-manager.org/static/doc/manual/ch04s03.html#idp72188272

In your LAM server profile on tab Account types you might also want to change the suffixes to cn=users,DC=xxx,DC=yyy,DC=zzz. This is where Windows stores accounts by default.
