### ISSUE TITLE
Activate TLS 1.2 on LAM

### ISSUE THREAD

**Issue by agrimal** [LDAPAccountManager/lam#53]
Hello,

I'm currently using LAM 6.2-1 on Ubuntu 18.04 (installed via official ubuntu repo).

With the imapAccess module i had the following error : 
`TLS/SSL failure for <my_imap_server>: SSL negotiation failed`
when i tried to connect to the IMAP server.

The IMAP server is running cyrus 2.5.
I had to modify the parameter tls_versions in /etc/imapd.conf from
`tls_versions: tls1_2` to 
`tls_versions: tls1_0 tls1_1 tls1_2`
to make the imapAccess work, which is less secure now.

Is there a way I can make LAM use TLS 1.2 and not TLS 1.0 ?

Thanks

**Comment by gruberroland** [comment]
Hi,
this seems like a restriction of the PHP version you use. LAM cannot actively set the TLS version.
Try to upgrade PHP to 7.0 or 7.2.

Did you also try to connect via SSL by setting "Encryption protocol" in LAM server profile (tab Module settings)?

**Comment by agrimal** [comment]
When i set the encryption protocol to SSL, LAM try to connect to port 993, which is not open on the imap server, so i get as a result : `Can't connect to <my_imap_server>,993: Connection refused`, which is logic.

I'm using this version of PHP on Ubuntu 18.04.1 TLS with everything up-to-date :
```
root@lam:~# php7.2 -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```

I have the following OpenSSL version on both LAM and the IMAP server :
```
root@lam:~# openssl version
OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by agrimal** [comment]
Ok so I found that php-imap, even in version 7.2, rely on an old library `libc-client2007e` which use tls 1.0 on port 143 and tls 1.2 on port 933.
So i have to activate port 993 on my imap server just for php.
But the problem is solved, nothing can be done on the PHP side.
Thanks

**Comment by gruberroland** [comment]
Created bug at PHP: https://bugs.php.net/bug.php?id=76928
Please vote for it and add any more comments that might be useful.

**Comment by agrimal** [comment]
> Please vote for it and add any more comments that might be useful.

Done 👍
