### ISSUE TITLE
Log to stderr/stdout in Docker?

### ISSUE THREAD

**Issue by rojopolis** [LDAPAccountManager/lam#60]
I'm attempting to run LAM in a k8s deployment.  It was very easy to get going (nice work!).  One thing that doesn't work well in this situation is logging.  Is it possible to configure the application logger to write to stderr/stdout so that k8s can more easily capture the output?  I tried to set the log file to /dev/stdout, but that didn't seem to work.

**Comment by gruberroland** [comment]
Can you try to set the logger to "php://stdout" or "php://stderr"? Maybe this helps.
If this does not help do you know of any other PHP-based applications that log the way you need it?

**Comment by rojopolis** [comment]
Sorry for the ignorant followup, but where would I put those values?
This doesn't work (not surprised, but worth a try)
![2019-02-12_20-45-52](https://user-images.githubusercontent.com/39421615/52687525-3f03c900-2f07-11e9-8fef-d60a23c2a1c5.png)

I also tried this configuration with the File field set to /dev/stdout.  This configuration was accepted, but logs still didn't make it to stdout.

Unfortunately, no, I can't point to any specific PHP apps that log this way.

**Comment by gruberroland** [comment]
What about /dev/stderr as log file?

**Comment by rojopolis** [comment]
I should have mentioned previously that I also tried /dev/stderr, but the result is the same...  The only output ever produced is:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.4.0.8. Set the 'ServerName' directive globally to suppress this message
Starting Apache httpd web server: apache2.
```

**Comment by gruberroland** [comment]
Do you use Papertrail? LAM could be extended to send to it without much effort.

**Comment by gruberroland** [comment]
LAM 6.7 will support logging to remote syslog servers such as Papertrail or rsyslogd. Does this help?
