### ISSUE TITLE
Immutable config

### ISSUE THREAD

**Issue by rojopolis** [LDAPAccountManager/lam#61]
I'm attempting to run LAM in a k8s deployment. It was very easy to get going (nice work!). One thing that doesn't work well in this situation is configuration.  It's standard in k8s to use [ConfigMaps](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) to configure applications however these must be mounted read-only.  LAM seems to insist that it's config files be read/write which does not work well in the world of immutable infrastructure.  Please consider redesigning this.

**Comment by gruberroland** [comment]
Where exactly do you have issues with read-only config files? Can you provide an error message/screenshot?
E.g. the live demo works with read-only files, too. But it is not on k8s.
https://www.ldap-account-manager.org/lam/templates/login.php

**Comment by gruberroland** [comment]
@rojopolis  do you have any more information about this issue?

**Comment by rojopolis** [comment]
Sorry for the lack of followup on this...  I just got back to this project and discovered that the error was on my end...  I had mapped a volume onto the entire config directory rather than just the config file.  Thanks for the followup.
