### ISSUE TITLE
LDAP_EXOP modify ignores ppolicy rejects

### ISSUE THREAD

**Issue by dhoffend** [LDAPAccountManager/lam#63]
When using LAM with the new LDAP_EXOP password management operation, it doesn't react on exop rejects.

We tried to set an old/known password using the WebUI. The LDAP Server rejected it

```
Mar  5 13:50:49 ldap1 slapd[1251]: conn=14775 op=6 EXT oid=1.3.6.1.4.1.4203.1.11.1
Mar  5 13:50:49 ldap1 slapd[1251]: conn=14775 op=6 PASSMOD id="uid=testuser,ou=Users,dc=example,dc=net" new
Mar  5 13:50:49 ldap1 slapd[1251]: conn=14775 op=6 RESULT oid= err=19 text=Password is in history of old passwords
```
But the WebUI tells us:

- (3x) Invalid/Missing Message type. Please report this error to the Bug-Tracker at LDAP Account Manager Developement Team. Thank you
- LDAP Operation was successful

Sorry for cross posting @ SF ... found this afterwords

**Comment by dhoffend** [comment]
I've debugged the arguments in the errors error that are being passed to the StatusMessage function

1) Message

MessageTyp = E
MessageHeadline => R
MessageText = R

I guess this should be ERROR

2) Message

MessageTyp = K
MessageHeadline => o
MessageText = n

I guess this should be "Konnte Passwort nicht setzen"

3) Message

MessageTyp = P
MessageHeadline => a
MessageText = s

I guess this should be "Password fails quality checking policy".

There's a problem with the merging of messags. Found it ... Fix incoming

**Comment by gruberroland** [comment]
Thanks a lot for your report and the pull request. I merged it. :)
