### ISSUE TITLE
Account type "Groups" not saving/deleting fields

### ISSUE THREAD

**Issue by stefanschmidtpegasus** [LDAPAccountManager/lam#66]
Settings for custom fields of account  type "Groups" are not saved and cannot be deleted.

To reproduce do the following:
Under LAM Login > LAM configuration > Edit server profiles > Modules
Add "Custom fields" module

Under "Module settings" select "Create new group"
Account type: Groups
Alias: Foobar

Under Foobar group "Add new field"
Name: Foobar
Label: Foobar
Attribute name: Foobar
Type: Checkbox

Then click on the x to delete the field Foobar and see that it doesn't get deleted.

Then enter the following info for field Foobar:
Value for "checked": 1
Value for "unchecked": 0
Click the Save button at the bottom of the page
Message "Your settings were successfully saved" is displayed
Return to field Foobar and see that settings for checked/unchecked where not saved.
Settings are also not saved for other field types such as "Text field".

**Comment by gruberroland** [comment]
Thanks a lot for your report. I was able to reproduce this. But it seems to happen only in case the custom fields module is not activated for groups ("Modules" tab). So it would make no sense to define fields in this case.
Can you confirm that on modules tab you did not activate the custom fields module for groups?

I will fix the select box to show no more account types that have no active custom fields module.

**Comment by stefanschmidtpegasus** [comment]
Indeed the behaviour only occurs when the custom fields module is not activated for groups. Modifying the select box to not show account  types that have no active custom fields module should fix the issue.

**Comment by gruberroland** [comment]
Will be fixed with 6.8 release
