### ISSUE TITLE
how to configure https for docker lam

### ISSUE THREAD

**Issue by zhb127** [LDAPAccountManager/lam#69]
When i use nginx proxy docker lam with https, in most case, css js resources cannot be loaded, like this:
![image](https://user-images.githubusercontent.com/5210208/62882370-557ac800-bd64-11e9-8647-d31e606b690a.png)

![image](https://user-images.githubusercontent.com/5210208/62882203-f321c780-bd63-11e9-8e3d-734dc726b298.png)

![image](https://user-images.githubusercontent.com/5210208/62882231-046ad400-bd64-11e9-9d61-d06a21572627.png)

Just use http, everything works fine.

**Comment by gruberroland** [comment]
The screenshot shows only successful requests (all status 200). Do you get any other errors, e.g. in browser console?

**Comment by zhb127** [comment]
Thank you for your reply.

No, I didn't find other errors, this is new screenshots for https:
![image](https://user-images.githubusercontent.com/5210208/62951055-d943bb80-be1b-11e9-8576-044eaa0d662e.png)
![image](https://user-images.githubusercontent.com/5210208/62951095-e95b9b00-be1b-11e9-82cf-d8d851d103b8.png)

this is screenshots for http:

![image](https://user-images.githubusercontent.com/5210208/62951152-02fce280-be1c-11e9-8ad6-065d975657b9.png)

**Comment by zhb127** [comment]
> The screenshot shows only successful requests (all status 200). Do you get any other errors, e.g. in browser console?

Thank you for your reply.

No, I didn't find other errors, this is new screenshots for https:
![image](https://user-images.githubusercontent.com/5210208/62951055-d943bb80-be1b-11e9-8576-044eaa0d662e.png)
![image](https://user-images.githubusercontent.com/5210208/62951095-e95b9b00-be1b-11e9-82cf-d8d851d103b8.png)

this is screenshots for http:

![image](https://user-images.githubusercontent.com/5210208/62951152-02fce280-be1c-11e9-8ad6-065d975657b9.png)

**Comment by zhb127** [comment]
> The screenshot shows only successful requests (all status 200). Do you get any other errors, e.g. in browser console?

Thank you for your reply.

No, I didn't find other errors, this is new screenshots for https:
![image](https://user-images.githubusercontent.com/5210208/62951055-d943bb80-be1b-11e9-8576-044eaa0d662e.png)
![image](https://user-images.githubusercontent.com/5210208/62951095-e95b9b00-be1b-11e9-82cf-d8d851d103b8.png)

this is screenshots for http, it can load all resources:

![image](https://user-images.githubusercontent.com/5210208/62951346-68e96a00-be1c-11e9-93e5-6c8dee392846.png)

**Comment by zhb127** [comment]
I use Kubernetes to deploy lam, config ingress with tls.

**Comment by gruberroland** [comment]
I did not yet exactly understand the issue. Does the page look wrong because of missing styles? Is any data missing like no users are shown? Can you provide a screenshot of the issue?
Please also check Apache log files if there are any issues.

**Comment by zhb127** [comment]
Thank you for the replay, I have found the problem, it's my kubernetes problem.

**Comment by bohdantverdyi** [comment]
@zhb127 Hello, what was the issue ? i have almost same issue in my Kubernetes cluster.

**Comment by bohdantverdyi** [comment]
@zhb127 ping :)
