### ISSUE TITLE
When I press "change" button in group edit screen. 

### ISSUE THREAD

**Issue by alparslanozturk** [LDAPAccountManager/lam#7]
I give this error message. 

Notice: Undefined index: account in /opt/ldap-account-manager-5.6.RC1/templates/account/edit.php on line 120

Fatal error: Call to a member function continue_main() on a non-object in /opt/ldap-account-manager-5.6.RC1/templates/account/edit.php on line 120

![resim](https://cloud.githubusercontent.com/assets/9527118/21130553/6b4cf494-c11a-11e6-9b4d-932279bb70b0.png)

**Comment by gruberroland** [comment]
Please increase your memory_limit option in your php.ini (e.g. /etc/php5/apache/php.ini).
