### ISSUE TITLE
Persistent configuration

### ISSUE THREAD

**Issue by d4nicoder** [LDAPAccountManager/lam#71]
It would be nice if we can map a volume to de config data to persist all the settings.

**Comment by gruberroland** [comment]
Can you provide some more details what you want to achieve? Do you want to copy config data from one server to another?

**Comment by gruberroland** [comment]
Please reopen and provide more details if still needed.

**Comment by danielsss** [comment]
@gruberroland 

For now, All the LDAP settings will be erased when I reboot server or docker service.

Is there a settings path that can be mapped to outside docker?

**Comment by danielsss** [comment]
> It would be nice if we can map a volume to de config data to persist all the settings.

@danitetus The settings are stored in /var/lib/ldap-account-manager directory. you can try it.

**Comment by gruberroland** [comment]
I updated https://hub.docker.com/r/ldapaccountmanager/lam with the config file locations. Is there anything else that would help?

**Comment by d4nicoder** [comment]
@danielsss thenk you so much, i'll try it.
@gruberroland your link is broken

**Comment by gruberroland** [comment]
Link updated :)
