### ISSUE TITLE
6.9 on kubernetes fails

### ISSUE THREAD

**Issue by radiocastellon** [LDAPAccountManager/lam#78]
I don't know if it only appears on kubernetes, but when the container starts it crashes with this message:

> apache2: Syntax error on line 222 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/conf-enabled/ldap-account-manager.conf: No such file or directory

Maybe the path is incorrect?

**Comment by radiocastellon** [comment]
I think it is related to volume mounts for persistence, becouse if I drop the bind mounts it works

**Comment by gruberroland** [comment]
Does this mean a change is needed on LAM's side or it was caused by some local configuration?
