### ISSUE TITLE
LAM cannot update initial configuration

### ISSUE THREAD

**Issue by sogyals429** [LDAPAccountManager/lam#82]
After I setup LAM then i am not able to update the config. The page is stuck in a loop. 
I have attached the screenshot of before and after below. 
<img width="1405" alt="Screen Shot 2019-12-11 at 4 32 21 pm" src="https://user-images.githubusercontent.com/17468028/70594219-e939a380-1c33-11ea-9828-2d0e7d57bac3.png">
<img width="1408" alt="Screen Shot 2019-12-11 at 4 32 30 pm" src="https://user-images.githubusercontent.com/17468028/70594221-eb036700-1c33-11ea-9887-3c9fc03fb17a.png">

**Comment by gruberroland** [comment]
What exactly do you mean with "stuck in a loop"? Does the save button show the edit page again and again? Are values not saved?

**Comment by sogyals429** [comment]
Yes when i click on the save button it asks for the lam password and then redirects back to the same screen with the values unchanged. 

The ldap account manager is running on centos 7 and I am guessing its an issue with the OS as it was working fine on Ubunutu. The only thing is that I am not able to figure out what setting in the OS is causing the isse.

Any help would be appreciated. Thanks.

**Comment by sogyals429** [comment]
After checking the HTTPD logs i found this error that is being logged.

> PHP Notice:  Undefined index: header in /usr/share/ldap-account-manager/templates/config/confmain.php on line 153

> Undefined index: header in /usr/share/ldap-account-manager/templates/config/confmain.php on line 153, referer: https://directory.dev1.littlepay.io/lam/templates/config/moduleSettings.php

**Comment by sogyals429** [comment]
I figured the issue out. It's cause I have two ldap servers on a load balancer hence the page was switching between both the instances. Apologies for the trouble. 

@gruberroland 
**Although I would like to request a feature for allowing replication for LDAP Account Manager**

**Comment by gruberroland** [comment]
See here: https://www.ldap-account-manager.org/static/doc/manual/aph.html
Basically, you need to activate session stickiness on the LB.
