### ISSUE TITLE
LAM cannot create initial files on docker

### ISSUE THREAD

**Issue by mungaij83** [LDAPAccountManager/lam#83]
The scrip to setup docker container does not create /var/lib/ldap-account-manager/lam.conf and /etc/ldap-account-manager/config.cfg.

**Errors**
1. **lam.conf not created**- sed: can't read /var/lib/ldap-account-manager/config/lam.conf: No such file or directory
2. **config.cfg not created**- sed: can't read /etc/ldap-account-manager/config.cfg: No such file or directory

**Suggested Solution**
Create these files manually for the script to write content into them. This can be added to the script to allow it to create:
1. _config director_- Create this directory if does not exists
2. _lam.conf_ - create this file if does not exist
3. _config.cfg_ - create this file if it does not exist.

**Comment by gruberroland** [comment]
Can you check with "lam:latest"? Please also see the environment variables here:
https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/.env

**Comment by mungaij83** [comment]
Thanks for reply,

I am working with the latest release (ldapaccountmanager/lam:latest). Also checking from the current release branch, the script writes into the files without checking if the directories exists.

Regards

**Comment by gruberroland** [comment]
Can you provide your full docker command line? I guess you are calling it with volumes for /etc/ldap-account-manager and /var/lib/ldap-account-manager/config? Without volumes the directory+files are present.

Since the /var/lib/ldap-account-manager/config contains more than just lam.conf you would need to copy the whole structure from e.g. the tar.bz2 and mount it via volume.

**Comment by gruberroland** [comment]
I pushed an update that allows to skip the preconfiguration. You can set the following environment variable with "-e":
LAM_SKIP_PRECONFIGURE=true

**Comment by jokay** [comment]
> Since the /var/lib/ldap-account-manager/config contains more than just lam.conf you would need to copy the whole structure from e.g. the tar.bz2 and mount it via volume.

This should be handled by the script as stated by @mungaij83.

If `LAM_SKIP_PRECONFIGURE=false` and volumes are mounted, the needed (basic) data should be copied/created by the script before the magic of `sed` can happen :wink:
