### ISSUE TITLE
sed: cannot rename /etc/ldap-account-manager/sedL2QjK7: Device or resource busy

### ISSUE THREAD

**Issue by lanhaifeng** [LDAPAccountManager/lam#84]
1.start container
`
docker run -p 8080:80 -it -d --rm --volume /dockerData/config/ldap/config.cfg:/etc/ldap-account-manager/config.cfg --volume /dockerData/config/ldap/lam.conf:/var/lib/ldap-account-manager/config/lam.conf ldapaccountmanager/lam:stable
`
2.then container start fail
`
root@default:~# docker logs a479558654e3                                                                                                                                 
PHP Notice:  A non well formed numeric value encountered in Command line code on line 1
sed: cannot rename /etc/ldap-account-manager/sedL2QjK7: Device or resource busy
`
3.so,how to start lam container with the Mount Configuration Files from Outside

**Comment by gruberroland** [comment]
Please add this to skip the auto-configuration: --env LAM_SKIP_PRECONFIGURE=true
I updated the description on DockerHub.

**Comment by lanhaifeng** [comment]
Thanks for your help, my problem has been solved
