### ISSUE TITLE
Docker: Cannot use TLS

### ISSUE THREAD

**Issue by VincentBe** [LDAPAccountManager/lam#96]
Hi,

When trying to use TLS to connect to a OpenLDAP server, I always get:
```
openldap    | 5ecac663 conn=1000 fd=12 ACCEPT from IP=172.30.0.3:56698 (IP=0.0.0.0:389)
openldap    | 5ecac663 conn=1000 op=0 EXT oid=1.3.6.1.4.1.1466.20037
openldap    | 5ecac663 conn=1000 op=0 STARTTLS
openldap    | 5ecac663 conn=1000 op=0 RESULT oid= err=0 text=
openldap    | 5ecac663 conn=1000 fd=12 TLS established tls_ssf=256 ssf=256
lam         | [Sun May 24 19:09:23.049602 2020] [php7:warn] [pid 17] [client 81.240.4.190:51074] PHP Warning:  ldap_start_tls(): Unable to start TLS: Connect error in /usr/share/ldap-account-manager/lib/account.inc on line 733, referer: http://13.94.145.182/lam/templates/login.php
openldap    | 5ecac663 conn=1000 fd=12 closed (connection lost)

```

After some research, I found that your docker built is missing a parameter in /etc/ldap.conf. To resolve this,

- I just added a link to the /etc/ldap/ldap.conf file.
- And added a line to this file: TLS_REQCERT never.

Then, it works fine. Is it possible to add this to your Dockerfile and your docker image?

`RUN ln -s /etc/ldap/ldap.conf /etc/ldap.conf`
`RUN echo "TLS_REQCERT never >> /etc/ldap/ldap.conf`

Regards,

Vincent

**Comment by gruberroland** [comment]
I will add an option for this but disable it by default. Disabling the certificate checks is a security issue and only valid for development systems.

**Comment by gruberroland** [comment]
New environment variable LAM_DISABLE_TLS_CHECK can be set to true with next release.

**Comment by VincentBe** [comment]
Thanks.
