### ISSUE TITLE
"posixGroup_autoSyncGon" does not work for groupOfMembers

### ISSUE THREAD

**Issue by steffen-moser** [LDAPAccountManager/lam#98]
We run LAM Pro 7.2 (on Solaris 11.4 SRU 21, PHP 7.3.15 and OpenLDAP 2.4.48) and are currently in the process of testing a migration path from pure posixGroups to RFC2307bis-02 groups in order to have the "memberOf" overlay which more and more web tools need.  

We plan to use groups having the "groupOfMembers" as a structural object class and "posixGroup" as an auxiliary object class.

We came across the following bug (or missing feature?): 

Activating "posixGroup_autoSyncGon" in the profile's module settings is only possible when the type of groups which are used are 

  - groupOfNames
  - groupOfUniqueNames

When using the "groupOfMembers" variant (according to RFC2307bis-02 from 2009), the option of doing an enforced auto-synchronization between the posixGroup and the groupOfMembers records does not seem to be available in LAM Pro.

**Comment by gruberroland** [comment]
Hi Steffen,
thanks a lot for your report and the PR. I merged it. :)

Best regards
Roland

**Comment by steffen-moser** [comment]
Hi Roland,
thanks a lot!

Kind regards,
Steffen
